/*
 * JSP generated by Resin-3.1.8 (built Mon, 17 Nov 2008 12:15:21 PST)
 */

package _jsp._mobile._plugin._1;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.*;
import weaver.hrm.*;
import weaver.general.*;
import weaver.systeminfo.*;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import weaver.mobile.webservices.workflow.soa.RequestStatusLog;
import net.sf.json.JSONObject;

public class _operationrecord__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
Log log = LogFactory.getLog(page.getClass());
request.setCharacterEncoding("UTF-8");
response.setContentType("text/html;charset=UTF-8");
log.info("Follow is the QueryString:\t" + request.getQueryString());



//User user = HrmUserVarify.getUser(request , response) ;

String f_weaver_belongto_userid=Util.null2String(request.getParameter("f_weaver_belongto_userid"));//\u9700\u8981\u589e\u52a0\u7684\u4ee3\u7801
String f_weaver_belongto_usertype=Util.null2String(request.getParameter("f_weaver_belongto_usertype"));//\u9700\u8981\u589e\u52a0\u7684\u4ee3\u7801
User user  = HrmUserVarify.getUser(request, response, f_weaver_belongto_userid, f_weaver_belongto_usertype) ;//\u9700\u8981\u589e\u52a0\u7684\u4ee3\u7801

String error = Util.null2String(request.getParameter("error"));
if("error".equals(error)){
    Map errorresult = new HashMap();
    //\u62b1\u6b49,\u60a8\u6ca1\u6709\u6d41\u7a0b\u5185\u5bb9\u67e5\u770b\u6743\u9650...
    errorresult.put("error",SystemEnv.getHtmlLabelName(126351,user.getLanguage()));
    errorresult.put("errorno","126351");
    JSONObject errorjo = JSONObject.fromObject(errorresult);
    response.getWriter().write(errorjo.toString());
    return;
}
String workflowid = request.getParameter("workflowid");
String requestid = request.getParameter("requestid");
int desrequestid = Util.getIntValue(request.getParameter("desrequestid"), 0);
String isurger = Util.null2String(request.getParameter("isurger"));

int newversion = Util.getIntValue(request.getParameter("newversion"), 0);
if (newversion == 1) {
    RequestStatusLog reqstatusLog = new RequestStatusLog(workflowid, requestid);
	reqstatusLog.setUser(user);
	reqstatusLog.setDesrequestid(desrequestid);
	reqstatusLog.setIsurger(isurger);
	String str = reqstatusLog.getStatusLog4json();
	out.println(str);
} else {
	LinkedHashMap jsonskv = RequestStatusLog.getRequestStatusForMobile(workflowid, requestid, desrequestid, isurger, user);
	JSONObject jo = JSONObject.fromObject(jsonskv);
	out.println(jo);
}

    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 1886798272571451039L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("mobile/plugin/1/operationRecord.jsp"), -8361577741012251666L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string0;
  static {
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
  }
}
