/*
 * JSP generated by Resin-3.1.8 (built Mon, 17 Nov 2008 12:15:21 PST)
 */

package _jsp._cpt._maintenance;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import weaver.general.Util;
import weaver.common.util.xtree.TreeNode;
import java.util.*;
import weaver.hrm.*;
import weaver.systeminfo.SystemEnv;

public class _cptassortmenttreexml__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      weaver.cpt.maintenance.CapitalAssortmentComInfo CapitalAssortmentComInfo;
      CapitalAssortmentComInfo = (weaver.cpt.maintenance.CapitalAssortmentComInfo) pageContext.getAttribute("CapitalAssortmentComInfo");
      if (CapitalAssortmentComInfo == null) {
        CapitalAssortmentComInfo = new weaver.cpt.maintenance.CapitalAssortmentComInfo();
        pageContext.setAttribute("CapitalAssortmentComInfo", CapitalAssortmentComInfo);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      
response.setHeader("cache-control", "no-cache");
response.setHeader("pragma", "no-cache");
response.setHeader("expires", "Mon 1 Jan 1990 00:00:00 GMT");
User user = HrmUserVarify.getUser (request , response) ;
if(user == null)  return ;

      out.write(_jsp_string2, 0, _jsp_string2.length);
      
String id=Util.null2String(request.getParameter("id"));
String init=Util.null2String(request.getParameter("init"));
String checktype=Util.null2String(request.getParameter("checktype"));
String onlyendnode=Util.null2String(request.getParameter("onlyendnode")); //\u5982\u679c\u9700\u8981check\u662f\u5426\u4ec5\u4ec5\u53ea\u662f\u6ca1\u6709\u5b69\u5b50\u7684\u8282\u70b9
String showcptcount=Util.null2String(request.getParameter("showcptcount")); // \u662f\u5426\u663e\u793a\u8d44\u4ea7\u8d44\u6599\u6570\u91cf
TreeNode envelope=new TreeNode();
envelope.setTitle("envelope");

if(init.equals("y")&&!id.equals("")){
    /**
	TreeNode root=new TreeNode();
    root.setTitle(SystemEnv.getHtmlLabelName(831,user.getLanguage()));
    root.setNodeId("com_0");
    root.setHref("javascript:onClick('0')");
    root.setTarget("_self");
    root.setIcon("/images/treeimages/global_wev8.gif");
    envelope.addTreeNode(root);
    CapitalAssortmentComInfo.getTreeListById(root,id,checktype,onlyendnode,showcptcount);
    **/
    //CapitalAssortmentComInfo.getTreeList(envelope,"0",0,2,checktype,onlyendnode,showcptcount);
}else if(id.equals("")){
	/**
    TreeNode root=new TreeNode();
    root.setTitle(SystemEnv.getHtmlLabelName(831,user.getLanguage()));
    root.setNodeId("com_0");
    root.setHref("javascript:onClick('0')");
    root.setTarget("_self");
    root.setIcon("/images/treeimages/global_wev8.gif");
    envelope.addTreeNode(root);
    CapitalAssortmentComInfo.getTreeList(root,"0",0,2,checktype,onlyendnode,showcptcount);
    **/
    CapitalAssortmentComInfo.getTreeList(envelope,"0",0,2,checktype,onlyendnode,showcptcount);
}else{
    CapitalAssortmentComInfo.getTreeList(envelope,id,0,2,checktype,onlyendnode,showcptcount);
}
weaver.common.util.string.StringUtil.parseXml(out, envelope);

      out.write(_jsp_string1, 0, _jsp_string1.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 1886798272571451039L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("cpt/maintenance/CptAssortmentTreeXML.jsp"), 2640581275517111891L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string1;
  private final static char []_jsp_string0;
  private final static char []_jsp_string2;
  static {
    _jsp_string1 = "\r\n".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string2 = "\r\n\r\n".toCharArray();
  }
}
