/*
 * JSP generated by Resin-3.1.8 (built Mon, 17 Nov 2008 12:15:21 PST)
 */

package _jsp._workflow._workflow;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import weaver.general.Util;
import weaver.common.util.xtree.TreeNode;
import java.util.*;
import weaver.hrm.*;
import weaver.hrm.city.CityComInfo;
import weaver.systeminfo.SystemEnv;

public class _workflowxml__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/xml; charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    try {
      weaver.workflow.workflow.WorkFlowTree WorkFlowTree;
      WorkFlowTree = (weaver.workflow.workflow.WorkFlowTree) pageContext.getAttribute("WorkFlowTree");
      if (WorkFlowTree == null) {
        WorkFlowTree = new weaver.workflow.workflow.WorkFlowTree();
        pageContext.setAttribute("WorkFlowTree", WorkFlowTree);
      }
      weaver.hrm.company.SubCompanyComInfo SubCompanyComInfo;
      SubCompanyComInfo = (weaver.hrm.company.SubCompanyComInfo) pageContext.getAttribute("SubCompanyComInfo");
      if (SubCompanyComInfo == null) {
        SubCompanyComInfo = new weaver.hrm.company.SubCompanyComInfo();
        pageContext.setAttribute("SubCompanyComInfo", SubCompanyComInfo);
      }
      
response.setHeader("cache-control", "no-cache");
response.setHeader("pragma", "no-cache");
response.setHeader("expires", "Mon 1 Jan 1990 00:00:00 GMT");
User user = HrmUserVarify.getUser (request , response) ;
if(user == null)  return ;
String type=Util.null2String(request.getParameter("type"));
String id=Util.null2String(request.getParameter("id"));
String nodeid=Util.null2String(request.getParameter("nodeid"));
String init=Util.null2String(request.getParameter("init"));
String isTemplate=Util.null2String(request.getParameter("isTemplate"));
String subCompanyId=Util.null2String(request.getParameter("subCompanyId"));
int detachable=Util.getIntValue(String.valueOf(session.getAttribute("detachable")),0);
int operatelevel=Util.getIntValue(request.getParameter("operatelevel"));
String isWorkflowDoc = Util.null2String(request.getParameter("isWorkflowDoc"));
String workflowIds = Util.null2String(request.getParameter("workflowIds"));
String searchStr = Util.null2String(request.getParameter("searchStr"));
TreeNode envelope=new TreeNode();
envelope.setTitle("envelope");
String hasRightSub = "";
if(detachable == 1){
    hasRightSub=SubCompanyComInfo.getRightSubCompany(user.getUID(),"WorkflowManage:All",-1);
}
//\u6ca1\u6709\u5f00\u542f\u5206\u6743\uff0c\u4e14\u6709\u6d41\u7a0b\u7ef4\u62a4\u6743\u9650\u7684
if(detachable != 1 && HrmUserVarify.checkUserRight("WorkflowManage:All", user)){
    workflowIds = "";
}


if(!init.equals("")&&id.equals("")){
    TreeNode root=new TreeNode();
    String companyname ="";
    if(isTemplate.equals("1")){
        companyname=SystemEnv.getHtmlLabelName(18334,user.getLanguage());
    }else{
        companyname= SystemEnv.getHtmlLabelName(16483,user.getLanguage());
    }
    if ("multiworkflowtype".equals(type)) {
    	companyname= SystemEnv.getHtmlLabelName(33234,user.getLanguage());
    	subCompanyId=SubCompanyComInfo.getRightSubCompany(user.getUID(),"WorkflowManage:All",0);
    }
    root.setTitle(companyname);
    root.setNodeId("workflowtype_0");
    root.setTarget("_self");
    root.setIcon("/images/treeimages/global_wev8.gif");
    root.setHref("javascript:setSubCompany('"+Util.null2String(request.getParameter("subCompanyId"))+"')");
    
    if(detachable == 0 && HrmUserVarify.checkUserRight("WorkflowManage:All", user) && !"multiworkflowtype".equals(type)){
     	type = "selectAll";   
    }
    
    WorkFlowTree.getWorkflowTypeTreeList(root, type,subCompanyId,isTemplate,nodeid,detachable,isWorkflowDoc,workflowIds,Util.null2String(request.getParameter("subCompanyId")),searchStr,hasRightSub);
    int nodeCount = root.getTreeNodeCount();
    if(nodeCount > 0 ){
        envelope.addTreeNode(root);
    }else{
        TreeNode nullNode=new TreeNode();
        nullNode.setTitle(SystemEnv.getHtmlLabelName(22521,user.getLanguage()));
        envelope.addTreeNode(nullNode);
    }
}else{
    WorkFlowTree.getWorkflowTreeList(envelope,type,subCompanyId,isTemplate,id,detachable,isWorkflowDoc,workflowIds,searchStr,hasRightSub);
}

envelope.marshal(out);

      out.write(_jsp_string0, 0, _jsp_string0.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 1886798272571451039L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("workflow/workflow/WorkflowXML.jsp"), 4195185107597762172L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string0;
  static {
    _jsp_string0 = "\r\n".toCharArray();
  }
}
