/**
 * Author: wcd 
 * Version: 1.0 2014-09-04
 */
(function(d){var b=["DOMMouseScroll","mousewheel"];if(d.event.fixHooks){for(var a=b.length;a;){d.event.fixHooks[b[--a]]=d.event.mouseHooks}}d.event.special.mousewheel={setup:function(){if(this.addEventListener){for(var e=b.length;e;){this.addEventListener(b[--e],c,false)}}else{this.onmousewheel=c}},teardown:function(){if(this.removeEventListener){for(var e=b.length;e;){this.removeEventListener(b[--e],c,false)}}else{this.onmousewheel=null}}};d.fn.extend({mousewheel:function(e){return e?this.bind("mousewheel",e):this.trigger("mousewheel")},unmousewheel:function(e){return this.unbind("mousewheel",e)}});function c(j){var h=j||window.event,g=[].slice.call(arguments,1),k=0,i=true,f=0,e=0;j=d.event.fix(h);j.type="mousewheel";if(h.wheelDelta){k=h.wheelDelta/120}if(h.detail){k=-h.detail/3}e=k;if(h.axis!==undefined&&h.axis===h.HORIZONTAL_AXIS){e=0;f=-1*k}if(h.wheelDeltaY!==undefined){e=h.wheelDeltaY/120}if(h.wheelDeltaX!==undefined){f=-1*h.wheelDeltaX/120}g.unshift(j,k,f,e);return(d.event.dispatch||d.event.handle).apply(this,g)}})(_jQuery);
function DataForOrgchartBS(a,b){this.conf=a;this.context=b;this.init()}
DataForOrgchartBS.prototype={define:function(){this.tempData=[];this.tempPids={};this.adapter={};this.formatedData=[];this.source},redefine:function(){this.tempData=[];this.tempPids={};this.formatedData=[];this.source&&_jQuery.each(this.source,function(a,c){c.used=!1});return this},init:function(){this.define();this.adaptDataFormat()},formatForRank:function(a){this.tempData=a;this.tempPids={};var c=this.adapter.pid,b=this.adapter.id;if(a.constructor==Array){var d={},e;for(e in a)d[a[e][b]]=!0;for(e in a){var f=
a[e];d[f[c]]&&f[c]!=f[b]?f.rtype="sub":(f.rtype="root",this.tempPids[f[c]]=!0)}var d=this.formatedData.length,h={},k={};for(e in a)f=a[e],this.tempPids[f[c]]&&(f.rank=d,f.used=!0,k[f[b]]=!0,h[f[c]]||(h[f[c]]=[]),h[f[c]].push(f));this.formatedData[d]=h;this.tempPids=k;this._traverseDataForRank()}return this.formatedData},_traverseDataForRank:function(){var a=this.adapter.pid,c=this.adapter.id,b=this.formatedData.length,d={},e={},f;for(f in this.tempData){var h=this.tempData[f];!h.used&&this.tempPids[h[a]]&&
(h.rank=b,h.used=!0,e[h[c]]=!0,d[h[a]]||(d[h[a]]=[]),d[h[a]].push(h))}var a=!1,k;for(k in e)a=k;a&&(this.formatedData[b]=d,this.tempPids=e,arguments.callee.call(this))},addData:function(a,c){var b=this.adapter.id,d=this.source;if(!c||"rank"==c){d||(d=[]);for(var d=d.concat(a),e={},f=0;f<d.length;f++)d[f].used=!1,e[d[f][b]]?(d.splice(f,1),f--):e[d[f][b]]=!0}this.source=d},appendData:function(a,c){var b=this.adapter.id,d=this.adapter.pid,e;for(e in this.source)if(this.source[e][b]==a){this.source[e][d]=
c;break}},deleteData:function(a){function c(a,b){b[a].del=1}if(a){this.searchDataGroup(a,c);a=this.source;for(var b=0;b<a.length;b++)1==a[b].del&&(a.splice(b,1),b--)}},searchData:function(a){var c=this.adapter.id,b;for(b in this.source)if(this.source[b][c]==a)return this.source[b]},searchDataGroup:function(a,c){for(var b=this.source,d=0;d<b.length;d++)if(b[d]&&b[d][this.adapter.id]==a){this.tempData.push(b[d]);"function"==typeof c&&c(d,this.source);for(var e=0;e<b.length;e++)b[e]&&b[e][this.adapter.pid]==
a&&arguments.callee.call(this,b[e][this.adapter.id],c)}return this.tempData},adaptDataFormat:function(){var a={};this.adapter=this.conf.adapter||{id:a.id||"id",pid:a.pid||"pid",logo:a.logo||"logo"}}};function CreateOrgchartBaseBS(a,c){this.conf=a;this.context=c;this.init()}
CreateOrgchartBaseBS.prototype={subunitTree:['<td class="org_td" id="org_td_{id}" nid="{id}" rank="{r}"><table border="0" cellspacing="0" cellpadding="0" style="border-collapse:collapse;" class="line_table"><tr style="width:100%;" class="line_tr"><td class="line_ltd" style="witdh:50%"></td><td class="line_rtd" style="witdh:50%;"></td></tr><tr><td colspan="2" align="center">','\t<div class="org_group" id="org_group_{id}" nid="{id}"></div>',"</td></tr></table></td>"],subunitMFChartByTree:['<td class="org_td" id="org_td_{id}" nid="{id}" rank="{r}"><table border="0" cellspacing="0" cellpadding="0" class="line_table"><tr style="width:100%;" class="line_tr"><td class="line_ltd" style="witdh:50%"><div class="ltd_inner_div"></div></td><td class="line_rtd" style="witdh:50%;"></td></tr><tr><td colspan="2">',
'\t<div class="org_group" id="org_group_{id}" nid="{id}"><table border="0" cellspacing="0" cellpadding="0" class="line_in_table"><tr style="width:100%;" class="line_in_tr"><td class="line_in_ltd" style="witdh:50%"></td><td class="line_in_rtd" style="witdh:50%;"></td></tr><tr><td class="org_group_in_td" colspan="2"></td></tr></table></div>',"</td></tr></table></td>"],subunitMFChartByColumn:'<tr class="org_tr"><td class="org_td_{x}"></td><td class="org_td" id="org_td_{id}" nid="{id}" rank="{r}">;\t<table class="line_parent" border="0" cellspacing="0" cellpadding="0">;\t\t<tr>;\t\t\t<td class="line_tdall" style="height:100%">;\t\t\t\t<div class="org_td_zt"></div>;\t\t\t\t<div class="dTable_fLeft"><div class="org_group" id="org_group_{id}" nid="{id}"></div></div>;\t\t\t</td>;\t\t</tr>;\t\t<tr><td class="line_tdb" style="height:50%"></td></tr>;\t</table></div>;</td></tr>'.split(";"),
subunitColumn:['<tr class="org_tr org_tr_col"><td class="org_td org_td_col" id="org_td_{id}" nid="{id}" rank="{r}">','\t<div class="org_group org_group_col" id="org_group_{id}" nid="{id}"></div>',"</td></tr>"],subunitUp:['<tr class="org_tr org_tr_col"><td class="org_td org_td_col" id="org_td_{id}" nid="{id}" rank="{r}">','\t<div class="org_group org_group_col" id="org_group_{id}" nid="{id}"></div>',"</td></tr>"],subunitLeft:['<tr class="org_tr org_tr_col"><td class="org_td org_td_col" id="org_td_{id}" nid="{id}" rank="{r}">',
'\t<div class="org_group org_group_col" id="org_group_{id}" nid="{id}"></div>',"</td></tr>"],subunitRight:'<tr class="org_tr org_tr_col"><td class="org_td org_td_col" id="org_td_{id}" nid="{id}" rank="{r}" style="">,\t<table class="line_parent" border="0" cellspacing="0" cellpadding="0" style="border:1px solid white">,\t\t<tr>,\t\t\t<td class="line_tda" style="height:50%"></td>,\t\t\t<td rowspan="2" style="height:100%">,\t\t\t\t<div style="display:table;"><div class="org_group org_group_col" id="org_group_{id}" nid="{id}" style="display:table-cell">,\t\t\t\t\t<table border="0" cellspacing="0" cellpadding="0" style="border-collapse:collapse;"><tr><td class="org_group_node_td"></td><td class="org_group_tb_td"></td></tr></table>,\t\t\t\t</div></div>,\t\t\t</td>,\t\t</tr>,\t\t<tr><td class="line_tdb" style="height:50%"></td></tr>,\t</table>,</td></tr>'.split(","),
subunitRightChrome:'<tr class="org_tr org_tr_col"><td class="org_td org_td_col" id="org_td_{id}" nid="{id}" rank="{r}" style="height:100%">,\t<table class="line_parent" border="0" cellspacing="0" cellpadding="0">,\t\t<tr>,\t\t\t<td rowspan="2" class="line_ptd" style="height:100%;">,\t\t\t\t<div class="line_tra" style="height:50%;"></div>,\t\t\t\t<div class="line_trb" style="height:50%;"></div>,\t\t\t</td>,\t\t</tr>,\t\t<tr><td valign="middle">,\t\t\t<div class="org_group org_group_col" id="org_group_{id}" nid="{id}">,\t\t\t\t<table border="0" cellspacing="0" cellpadding="0" style="border-collapse:collapse;"><tr><td class="org_group_node_td"></td><td class="org_group_tb_td"></td></tr></table>,\t\t\t</div>,\t\t</td></tr>,\t</table>,</td></tr>'.split(","),
define:function(){this.dom={};this.data={};this.html={};this.dom.wrap=this.conf.wrap;this.data.source=this.conf.data;this.data.orgType=this.conf.orgType;this.data.tempOrgType=this.conf.orgType;this.onCreateGroupTreeCallback=this.conf.onCreateGroupTreeCallback;this.onCreateRankTreeCallback=this.conf.onCreateRankTreeCallback;this.onCreateAllTreeCallback=this.conf.onCreateAllTreeCallback;this.onStartCreateAllTreeCallback=this.conf.onStartCreateAllTreeCallback},init:function(){this.define()},createByRank:function(a,
c){var b=this.context.DataObject.adapter.pid,d=this.context.DataObject.adapter.id,e=this.context.DataObject.adapter.type;this.data.tempOrgType=this.data.orgType;this.data.orgType=c||this.data.orgType;var f=!1,h=$.client.browserVersion.browser,k=parseInt($.client.browserVersion.version),q;for(q in a){var r=a[q],s=!1,u;for(u in r){var v=!1,w;for(w in r[u]){var n=r[u][w];if(!_jQuery("#org_td_"+n[d]).length){v||(v=!0);s||(s=!0);f||(f=!0);var g=[],p=_jQuery("#org_td_"+n[b]),l=p.attr("rank"),l=void 0===
l?0:Number(l)+1;if("column"==this.data.orgType)_jQuery.each(this.subunitColumn,function(a,b){g.push(b)});else if("up"==this.data.orgType)_jQuery.each(this.subunitUp,function(a,b){g.push(b)});else if("left"==this.data.orgType)_jQuery.each(this.subunitLeft,function(a,b){g.push(b)});else if("right"==this.data.orgType)_jQuery.each(h&&"Chrome"==h?this.subunitRightChrome:this.subunitRight,function(a,b){g.push(b)});else if("mfchart"==this.data.orgType){var m=this.subunitTree;"company"!=n[e]&&(m="1"==l?this.subunitMFChartByTree:
this.subunitMFChartByColumn);_jQuery.each(m,function(a,b){g.push(b)})}else _jQuery.each(this.subunitTree,function(a,b){g.push(b)});g[0]=g[0].replace(/{id}/g,n[d]);g[0]=g[0].replace(/{r}/g,l);h&&"IE"==h?8==k?(m=window.navigator.platform,5==m.length&&(m=m.substr(3)),g[0]=g[0].replace(/{x}/g,"64"==m?"n":"e")):g[0]=g[0].replace(/{x}/g,"n"):g[0]=g[0].replace(/{x}/g,"n");"right"==this.data.orgType?h&&"Chrome"==h?g[9]=g[9].replace(/{id}/g,n[d]):g[5]=g[5].replace(/{id}/g,n[d]):"mfchart"==this.data.orgType?
"company"==n[e]||"1"==l?g[1]=g[1].replace(/{id}/g,n[d]):g[5]=g[5].replace(/{id}/g,n[d]):g[1]=g[1].replace(/{id}/g,n[d]);var m=_jQuery(g.join("")),t=this.context.NodeObject.createHtmlContent(n,l);t&&("right"==this.data.orgType?t.appendTo(m.find("td.org_group_node_td")):"mfchart"==this.data.orgType?"company"==n[e]?t.appendTo(m.find("div.org_group")):"1"==l?t.appendTo(m.find("td.org_group_in_td")):t.appendTo(m.find("div.org_group")):t.appendTo(m.find("div.org_group")));this.buildNode(m,p,l)}}if("function"==
typeof this.onCreateGroupTreeCallback)this.onCreateGroupTreeCallback(_jQuery("#org_td_"+u),v)}if("function"==typeof this.onCreateRankTreeCallback)this.onCreateRankTreeCallback(q,r,s)}if("function"==typeof this.onCreateAllTreeCallback)this.onCreateAllTreeCallback(a,f);this.data.orgType=this.data.tempOrgType},buildNode:function(a,c,b){"column"==this.data.orgType||"up"==this.data.orgType||"left"==this.data.orgType||"right"==this.data.orgType?this.buildNodeColumn(a,c):"mfchart"==this.data.orgType?this.buildNodeMFChart(a,
c,b):this.buildNodeTree(a,c)},buildNodeTree:function(a,c){var b=_jQuery('<table cellspacing=0  cellpadding=0 class="org_table" type="tree"><tr class="org_tr"></tr></table>'),d=null;0==a.siblings("td.org_td").length&&(d=a.closest("table.org_table"));if(c.length){var e=c.find("td.org_td:first");e.length?e.closest("tr.org_tr").append(a):(c.find("table.org_table").length&&(b=c.find("table.org_table")),b.find("tr.org_tr").append(a),c.find("div.org_group:first").append(b))}else b.find("tr.org_tr").append(a),
this.dom.wrap.append(b);d&&a.closest("table.org_table")[0]!==d[0]&&d.remove()},buildNodeColumn:function(a,c){var b=_jQuery('<table cellspacing=0 cellpadding=0 class="org_table org_table_col" type="column" style="border-collapse:collapse;"></table>'),d=null;0==a.siblings("tr.org_tr").length&&(d=a.closest("table.org_table"));if(c.length){var e=c.find(".org_tr:first");e.length?e.closest("table.org_table").append(a):(c.find("table.org_table").length&&(b=c.find("table.org_table")),b.append(a),c.find("td.org_group_tb_td").append(b))}else b.append(a),
this.dom.wrap.append(b);d&&a.closest("table.org_table")[0]!==d[0]&&d.remove()},buildNodeMFChart:function(a,c,b){b=b&&1<Number(b)?1:0;var d='<table cellspacing=0 cellpadding=0 class="org_table" type="tree">';0==b&&(d+='<tr class="org_tr"></tr>');var d=_jQuery(d+"</table>"),e=null;0==a.siblings(1==b?"tr.org_tr":"td.org_td").length&&(e=a.closest("table.org_table"));if(c.length){var f=c.find(1==b?".org_tr:first":"td.org_td:first");f.length?f.closest(1==b?"table.org_table":"tr.org_tr").append(a):(c.find("table.org_table").length&&
(d=c.find("table.org_table")),1==b?d.append(a):d.find("tr.org_tr").append(a),c.find("div.org_group:first").append(d))}else 1==b?d.append(a):d.find("tr.org_tr").append(a),this.dom.wrap.append(d);e&&a.closest("table.org_table")[0]!==e[0]&&e.remove()}};function CreateOrgchartNodeBS(a,c){this.conf=a;this.context=c;this.init()}
CreateOrgchartNodeBS.prototype={define:function(){this.dom={};this.data={};this.html={};this.dom.wrap=this.conf.wrap;this.data.source;this.data.orgType=this.conf.orgType;this.html.htmlContent=this.conf.htmlContent||['<div class="org_node_c">\u8282\u70b9\u5185\u5bb9</div>'];this.onStartMove=this.conf.onStartMove;this.onEndMove=this.conf.onEndMove;this.onAppendNodeWithData=this.conf.onAppendNodeWithData;this.onCancelOriginalPlaceholder=this.conf.onCancelOriginalPlaceholder;this.onDeleteNodeCallback=
this.conf.onDeleteNodeCallback;this._createHtmlContent=this.conf.createHtmlContent;this._addEvent=this.conf.addEventToNode;this.isBindMoveOperation=this.conf.isBindMoveOperation;this.isMoveOperation=this.conf.isMoveOperation},init:function(){this.define();this.addDragEventToDoc()},createHtmlContent:function(a,c){if("function"==typeof this._createHtmlContent)return this._createHtmlContent(a,c);var b=_jQuery(this.html.htmlContent.join(""));this.addEvent(b);return b},addEvent:function(a){var c=this;
a.bind("mousedown",function(a){if(window.chart.isWrapDraggableSubCtrl&&(a=_jQuery(this),"undefined"==typeof c.isBindMoveOperation||c.isBindMoveOperation())){var d=_jQuery(document),e=a.parents(".org_group").first();"undefined"==typeof c.isMoveOperation||c.isMoveOperation()?(d.data("orgmoveable",!0),d.data("movenode",e),d.data("refnode",c.dom.wrap.find("div.org_node_c").not("#"+a.attr("id"))),d.data("handlenode",a),d.attr("issorgtartmove",0),c.calAllNodeLayout("div.org_group,div.org_node_c"),c.setOriginalPlaceholder(e),
c.reserveMoveNodeCss(e),c.setMoveNodeCss(e),e.data("curOrgtd",e.closest(".org_td")),e.data("parOrgtd",e.closest(".org_tr").closest(".org_td")),e.appendTo(document.body)):d.data("orgmoveable",!1)}});"function"==typeof this._addEvent&&this._addEvent(a)},addDragEventToDoc:function(){var a=this;("undefined"==typeof this.isBindMoveOperation||this.isBindMoveOperation())&&_jQuery(document).bind("mousedown",function(a){if(window.chart.isWrapDraggableSubCtrl){var b=_jQuery(this);if(!0===b.data("orgmoveable")){var d=
a.pageY||0;b.data("esx",a.pageX||0);b.data("esy",d);b.data("edx",0);b.data("edy",0)}}}).bind("mousemove",function(c){if(window.chart.isWrapDraggableSubCtrl){var b=_jQuery(this);if(!0===b.data("orgmoveable")){var d=c.pageX||0;c=c.pageY||0;b.data("enx",d);b.data("eny",c);b.data("edx",d-b.data("esx"));b.data("edy",c-b.data("esy"));d=b.data("movenode");d.css({left:d.data("layout").x+b.data("edx"),top:d.data("layout").y+b.data("edy")});var e=b.data("handlenode"),f=e.offset().left,h=e.offset().top,k=e.width();
if(1!=b.attr("issorgtartmove")&&(b.attr("issorgtartmove",1),d.css({opacity:.5}),"function"==typeof a.onStartMove))a.onStartMove(e);b.data("refnode").each(function(a,b){b=_jQuery(b);f+k/2>=b.data("layout").x&&f+k/2<=b.data("layout").x+b.data("layout").w&&h>=b.data("layout").y&&h<=b.data("layout").y+b.data("layout").h?(b.css("opacity",.5),b.attr("ismatch",1),e.data("matchnode",b)):(b.css("opacity",1),b.attr("ismatch",0));return!0})}}}).bind("mouseup",function(c){if(window.chart.isWrapDraggableSubCtrl){var b=
_jQuery(this);if(!0===b.data("orgmoveable")){c=b.data("handlenode");var d=b.data("movenode");d.data("css");d.css(d.data("css"));d.width();d.height();a.cancelOriginalPlaceholder();a.appendMoveNode(c);c.data("matchnode")&&c.data("matchnode").css("opacity",1);b.data("movenode",null);b.data("orgmoveable",!1);b=d.data("parOrgtd");if("function"==typeof a.onEndMove)a.onEndMove({node:c,oparent:b})}}})},calAllNodeLayout:function(a){this.dom.wrap.data("layout",{x:this.dom.wrap.offset().left,y:this.dom.wrap.offset().top,
w:this.dom.wrap.width(),h:this.dom.wrap.height()});_jQuery(a).each(function(a,b){b=_jQuery(b);b.data("layout",{x:b.offset().left,y:b.offset().top,w:b.width(),h:b.height()})})},setMoveNodeCss:function(a){a.css({position:"absolute",left:a.data("layout").x,top:a.data("layout").y,"z-index":999})},setOriginalPlaceholder:function(a){var c=_jQuery("#orgplaceholder_o");c.length||(_jQuery('<div id="orgplaceholder_o"></div>').appendTo(document.body),c=_jQuery("#orgplaceholder_o"));c.show().css({width:a.width()-
22,height:a.height()-22,margin:"10px",border:"1px dashed #999","border-radius":"5px"});c.appendTo(a.parent())},cancelOriginalPlaceholder:function(){var a=_jQuery("#orgplaceholder_o");if("function"==this.onCancelOriginalPlaceholder)this.onCancelOriginalPlaceholder(a);else a.hide().appendTo(document.body)},reserveMoveNodeCss:function(a){a.data("css",{position:a.css("absolute")||"static",left:a.css("left"),top:a.css("top"),opacity:a.css("opacity"),"z-index":a.css("z-index")})},appendMoveNode:function(a){var c=
a.data("matchnode"),b=a.closest(".org_group");a=b.data("curOrgtd");b.appendTo(a);c&&c.length&&1==c.attr("ismatch")&&(c=c.closest(".org_td"),this.appendNodeWithData(a,c))},appendNodeWithData:function(a,c){var b=a.closest(".org_tr").closest(".org_td");this.context.DataObject.appendData(a.attr("nid"),c.attr("nid"));this.context.BaseObject.buildNode(a,c);if("function"==typeof this.onAppendNodeWithData)this.onAppendNodeWithData({node:a,oparent:b})},deleteNodeWithData:function(a){this.context.DataObject.deleteData(a);
a=_jQuery("#org_td_"+a);if(a.length){var c=a.closest(".org_table"),b=c.parents(".org_td:first");1==c.find(".org_td").length?c.remove():a.remove();if("function"==typeof this.onDeleteNodeCallback)this.onDeleteNodeCallback(b)}},addNodeWithData:function(a){this.context.DataObject.addData(a);a=this.context.DataObject.redefine().formatForRank(a);this.context.BaseObject.createByRank(a)}};function CreateOrgchartBS(a,c){this.conf=a;this.context=c}
CreateOrgchartBS.prototype={init:function(){this.conf.data&&this.conf.wrap&&this.conf.wrap.length&&(this.conf.wrap.html(""),this.render())},render:function(){this.COE=new CreateOrgchartExtendBS({},this);var a={wrap:this.conf.wrap,showtype:this.conf.showtype,shownum:this.conf.shownum,orgType:this.conf.orgType,onStartMove:this.COE.onStartMoveCallback,onEndMove:this.COE.onEndMoveCallback,htmlContent:this.COE.htmlContent,createHtmlContent:this.COE.createHtmlContent,addEventToNode:this.COE.addEventToNode,
onAppendNodeWithData:this.COE.onAppendNodeWithData,onCancelOriginalPlaceholder:this.COE.onCancelOriginalPlaceholder,onCreateGroupTreeCallback:this.COE.onCreateGroupTreeCallback,onCreateRankTreeCallback:this.COE.onCreateRankTreeCallback,onCreateAllTreeCallback:this.COE.onCreateAllTreeCallback,onStartCreateAllTreeCallback:this.COE.onStartCreateAllTreeCallback,isMoveOperation:this.COE.isMoveOperation,onDeleteNodeCallback:this.COE.onDeleteNodeCallback};_jQuery.extend(!0,a,this.conf);this.DataObject=new DataForOrgchartBS(a,
this);this.NodeObject=new CreateOrgchartNodeBS(a,this);this.BaseObject=new CreateOrgchartBaseBS(a,this);this.NodeObject.addNodeWithData(this.conf.data)}};function CreateOrgchartExtendBS(a,c){this.context=c}
CreateOrgchartExtendBS.prototype={htmlContent:['<div class="org_node_c" id="org_node_c_{id}" nid="{id}"><div class="org_node_c_inner"><span style="position:absolute;color:#fff;background:#000"></span>','\t<a class="img_corg" href="#">','\t\t<img src="{img}" />',"\t</a>","</div></div>"],onCreateGroupTreeCallback:function(a,c){c&&this.context.COE.setLine(a)},onCreateRankTreeCallback:function(a,c,b){},onCreateAllTreeCallback:function(a,c){var b=this;if(0!==a.length){var d=this.context.conf.wrap;if(c){var e=
this.context.DataObject.adapter.id,f=d.find("table.org_table:first"),h,k=d.data("scaleValue")||0,q;for(q in a[0])if(_jQuery("#org_td_"+q).length)for(var r in a[0][q]){var s=_jQuery("#org_td_"+a[0][q][r][e]);0!==k&&(h=s.find("div.org_node_c, div.org_node_c_inner, div.org_node_c .img_corg img"),h.each(function(a,c){if(c){var d=parseFloat(b.context.COE.getFinalStyle(c,"height"))+k;c.style.height=d+"px";d=parseFloat(b.context.COE.getFinalStyle(c,"width"))+k;c.style.width=d+"px"}}));s.fadeIn(800)}else{d.fadeIn(800);
break}d.unbind("mousewheel");d.bind("mousewheel",function(a,c){h=d.find("div.org_node_c, div.org_node_c_inner, div.org_node_c .img_corg img");var e=f.width(),k=f.height(),g=f.offset(),p=a.pageX-g.left,g=a.pageY-g.top;irL=p/e;irT=g/k;var l;l=0>c?-3:3;d.data("scaleValue")||d.data("scaleValue",0);d.data("scaleValue",d.data("scaleValue")+l);h.each(function(a,c){if(c){var d=parseFloat(b.context.COE.getFinalStyle(c,"width")),e=parseFloat(b.context.COE.getFinalStyle(c,"height"));c.style.width=d+l+"px";c.style.height=
e/d*(d+l)+"px"}});k=f.width();e=f.height();p-=irL*k;g-=irT*e;e=parseFloat(b.context.COE.getFinalStyle(f[0],"marginLeft"));p=(isNaN(e)?0:e)+p;e=parseFloat(b.context.COE.getFinalStyle(f[0],"marginTop"));g=(isNaN(e)?0:e)+g;f.css({"margin-left":p,"margin-top":g});return!1})}else d.find("td.org_td").fadeIn(800),d.fadeIn(800)}},onStartCreateAllTreeCallback:function(a){if(0!==a.length){var c=this.context.DataObject.adapter.id,b=this.context.conf.wrap,d;for(d in a[0])if(_jQuery("#org_td_"+d).length)for(var e in a[0][d])_jQuery("#org_td_"+
a[0][d][e][c]).hide();else{b.hide();break}}},onStartMoveCallback:function(a){a=a.closest(".org_group").data("curOrgtd");this.context.COE.setLine(a)},onEndMoveCallback:function(a){a.node.closest(".org_tr").closest(".org_td").fadeIn(500)},onAppendNodeWithData:function(a){var c=a.node.closest(".org_tr").closest(".org_td");a=a.oparent;c.hide();this.context.COE.setLine(c);this.context.COE.setLine(a)},onDeleteNodeCallback:function(a){this.context.COE.setLine(a)},setLine:function(a){if(a.length){var c=$.client.browserVersion.browser;
parseInt($.client.browserVersion.version);if("right"==this.context.BaseObject.data.orgType){var b=a.find("div.org_line_company:first");b&&b.hasClass("org_line_lm")&&b.removeClass("org_line_lm");var b=a.find(".org_table:first").find(".org_tr").children(".org_td"),d=b.length;d?(a.find("div.org_node_c:first").addClass("org_line_rm"),b.each(function(a,b){b=_jQuery(b).find("table.line_parent:first");c&&"Chrome"==c?(b.find("div.line_tra:first")&&(0==a||b.find("div.line_tra:first").hasClass("org_td_line_left")||
b.find("div.line_tra:first").addClass("org_td_line_left")),b.find("div.line_trb:first")&&(a==d-1||b.find("div.line_trb:first").hasClass("org_td_line_left")||b.find("div.line_trb:first").addClass("org_td_line_left"))):(b.find("td.line_tda:first")&&(0==a||b.find("td.line_tda:first").hasClass("org_td_line_left")||(c&&"Chrome"==c?b.find("td.line_tda:first").addClass("org_td_line_left"):b.find("td.line_tda:first").css({border:"1px solid #6C6C6C"}))),b.find("td.line_tdb:first")&&(a==d-1||b.find("td.line_tdb:first").hasClass("org_td_line_all")||
b.find("td.line_tdb:first").css({border:"1px solid #6C6C6C"})))})):a.find("div.org_node_c:first").removeClass("org_line_rm")}else if("mfchart"==this.context.BaseObject.data.orgType){(b=a.find("div.org_line_company:first"))&&b.hasClass(c&&"IE"==c?"org_line_tm_e":"org_line_tm")&&b.removeClass(c&&"IE"==c?"org_line_tm_e":"org_line_tm");var b=a.find(".org_table:first").find(".org_tr").children(".org_td"),d=b.length,e=0;d?(a.find("div.org_node_c:first").addClass("org_line_bm"),b.each(function(a,b){if((e=
_jQuery(b).attr("rank"))&&1<Number(e))b=_jQuery(b).find("table.line_parent:first"),1<d&&a!=d-1?b.find("td.line_tdall:first").hasClass("org_td_line_left")||b.find("td.line_tdall:first").addClass("org_td_line_left"):b.find("div.org_td_zt:first").hasClass("org_td_zh")||b.find("div.org_td_zt:first").addClass("org_td_zh");else if(b=_jQuery(b).find("table.line_table:first"),0==a)b.find("td.line_ltd:first").hasClass(c&&"IE"==c?"org_td_e":"org_td_n")||b.find("td.line_ltd:first").addClass(c&&"IE"==c?"org_td_e":
"org_td_n"),b.find("div.ltd_inner_div:first").hasClass("org_td_line")||b.find("div.ltd_inner_div:first").addClass("org_td_line"),b.find("td.line_rtd:first")&&b.find("td.line_rtd:first").hide();else if(a==d-1){if(b.find("td.line_in_ltd:first").hasClass("org_td_line")||b.find("td.line_in_ltd:first").addClass("org_td_line"),c&&"Chrome"==c){var k=b.find("div.org_line_subcompany:first");k.hasClass("org_line_tm")&&(k.removeClass("org_line_tm"),k.addClass("org_line_tm_tc"))}}else b.find("td.line_ltd:first").hasClass("org_td_line")||
b.find("td.line_ltd:first").addClass("org_td_line"),b.find("td.line_rtd:first").hasClass("org_td_line")||b.find("td.line_rtd:first").addClass("org_td_line")})):a.find("div.org_node_c:first").removeClass("org_line_bm")}else(b=a.find("div.org_line_company:first"))&&b.hasClass("org_line_tm")&&b.removeClass("org_line_tm"),b=a.find(".org_tr:first").children(".org_td"),(d=b.length)?(a.find("div.org_node_c:first").addClass("org_line_bm"),b.each(function(a,b){if(b=_jQuery(b).find("table.line_table:first").find("tr.line_tr:first"))0==
a||b.find("td.line_ltd").hasClass("org_td_line")||b.find("td.line_ltd").addClass("org_td_line"),a==d-1||b.find("td.line_rtd").hasClass("org_td_line")||b.find("td.line_rtd").addClass("org_td_line")})):a.find("div.org_node_c:first").removeClass("org_line_bm")}},createHtmlContent:function(a,c){var b,d=this.context.DataObject.adapter.id;b=this.context.DataObject.adapter.logo;var e=[];_jQuery.each(this.html.htmlContent,function(a,b){e.push(b)});e[0]=e[0].replace(/{id}/g,a[d]);e[2]=e[2].replace("{img}",
a[b]);b=_jQuery(e.join(""));b.find("span").html(a[d]);this.addEvent(b);return b},addEventToNode:function(a){a.find("img").bind("mousemove",function(a){a.preventDefault()}).bind("mouseup",function(a){a.preventDefault()}).bind("mousedown",function(a){a.preventDefault()})},isMoveOperation:function(){return this.context.conf.wrap.find("table.org_table[type!=tree]").length?!1:!0},getFinalStyle:function(a,c){if(a.style[c])return a.style[c];if(a.currentStyle)return a.currentStyle[c];if(document.defaultView&&
document.defaultView.getComputedStyle){c=c.replace(/([A-Z])/g,"-_jQuery1");c=c.toLowerCase();var b=document.defaultView.getComputedStyle(a,"");return b&&b.getPropertyValue(c)}return null}};