/*
 * JSP generated by Resin-3.1.8 (built Mon, 17 Nov 2008 12:15:21 PST)
 */

package _jsp._mobile._plugin;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import net.sf.json.*;
import java.util.*;
import weaver.conn.*;
import weaver.general.*;
import ln.LN;
import weaver.file.Prop;

public class _config__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("application/json");
    response.setCharacterEncoding("UTF-8");
    request.setCharacterEncoding("UTF-8");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
	Map<String, String> result = new HashMap<String, String>();
	int hideWfSignuture = Util.getIntValue(Prop.getPropValue("Mobile","hideWfSignuture"),0);
	result.put("workflowview", "1");
	
	//\u83b7\u53d6EMessage\u670d\u52a1\u5668\u5730\u5740
	RecordSet rs = new RecordSet();
	rs.executeSql("select 1 from ofProperty where name='weixin'");
	if(rs.next()){
		rs.executeSql("select propValue from ofProperty where name='xmpp.domain'");
		if(rs.next()){
			String ip = rs.getString("propValue");
			result.put("emessageServer", ip+"|true");
		}
	}
	
	result.put("newschedule", "1");
	//\u83b7\u53d6\u4eba\u529b\u8d44\u6e90\u6d4f\u89c8\u4f18\u5148\u663e\u793a\u9879\uff1a0--\u6240\u6709\u4eba\uff1b1--\u5e38\u7528\u7ec4\uff1b2--\u7ec4\u7ec7\u67b6\u6784
	rs.executeSql("select propValue from mobileProperty where name='hrmbtnshow'");
	if(rs.next()){
		result.put("hrmbtnshow", Util.getIntValue(rs.getString("propValue"), 1)+"");
	}

	rs.executeSql("select propValue from mobileProperty where name='androidsign'");
	if(rs.next()){
		result.put("androidsign", Util.getIntValue(rs.getString("propValue"), 1)+"");
	}
	rs.executeSql("select propValue from mobileProperty where name='iossign'");
	if(rs.next()){
		result.put("iossign", Util.getIntValue(rs.getString("propValue"), 1)+"");
	}
	rs.executeSql("select propValue from mobileProperty where name='ioskey'");
	if(rs.next()){
		result.put("ioskey", rs.getString("propValue"));
	}

	rs.executeSql("select propValue from mobileProperty where name='androidkey'");
	if(rs.next()){
		result.put("androidkey", rs.getString("propValue"));
	}
	rs.executeSql("select propValue from mobileProperty where name='iosWpskey'");
	if(rs.next()){
		result.put("iosWpskey", rs.getString("propValue"));
	}

	rs.executeSql("select propValue from mobileProperty where name='encryptpassword'");
	if(rs.next()){
		result.put("encryptpassword", rs.getString("propValue"));
	}

	LN ln=new LN();
	String cid=ln.getCid();
	
	result.put("cid",cid);

	result.put("newdoc", "1");
	result.put("workflowadsearch", "1");
	result.put("editavatar", "1");
	result.put("newdocreply","1");
	result.put("moreaccount","1");
	result.put("favourite","1");
	result.put("hideWfSignuture",""+hideWfSignuture);
    result.put("changePassword","1");
	result.put("opennetworkdisp","1");
	result.put("hasBroadCast", "1");
	result.put("webdoc", "1");
	result.put("groupchatvote", "1");
	result.put("isCanChangeUserInfo", "1");
	//\u83b7\u53d6\u5ba2\u6237\u7aef\u6d41\u7a0b\u6d88\u606f\u5217\u8868\u4f18\u5148\u663e\u793a\uff1a0--\u5168\u90e8\uff1b1--\u672a\u5904\u7406\uff1b
	rs.executeSql("select propValue from mobileProperty where name='UntreatedFirst'");
	if(rs.next()){
		result.put("UntreatedFirst", Util.getIntValue(rs.getString("propValue"), 0)+"");
	}
	//\u83b7\u53d6\u662f\u5426\u5f00\u542fCA\u8ba4\u8bc1\u5f00\u5173\u4ee5\u53caca\u670d\u52a1\u5730\u5740\u548c\u8ba4\u8bc1\u65b9\u5f0f
	result.put("isUsingCA", "0");//\u9ed8\u8ba4\u4e0d\u4f7f\u7528CA\u8ba4\u8bc1
	rs.executeSql("select name,propvalue from mobileProperty where name='isUsingCA' or name='caServerAddress' or name='caUsageMode'");
	while(rs.next()){
		String name = rs.getString("name");
		String propValue = rs.getString("propValue");
		if(name.equals("isUsingCA")){
			result.put("isUsingCA", Util.getIntValue(propValue, 0)+"");
		}else if(name.equals("caServerAddress")){
			result.put("caServerAddress", propValue);
		}else if(name.equals("caUsageMode")){
			result.put("caUsageMode", Util.getIntValue(propValue, 0)+"");
		}
	}

	if(result!=null) {
		JSONObject jo = JSONObject.fromObject(result);
		//System.out.println(jo);
		out.println(jo.toString());
	}

      out.write(_jsp_string1, 0, _jsp_string1.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 1886798272571451039L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("mobile/plugin/config.jsp"), -825595183940394941L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string1;
  private final static char []_jsp_string0;
  static {
    _jsp_string1 = "\r\n".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
  }
}
