var str="";
str+="<div style=\"width:100%;height:100%\">";
str+="<object width=\"100%\" height=\"100%\" classid=\"CLSID:15261F9B-22CC-4692-9089-0C40ACBDFDD8\" CODEBASE='/weaverplugin/chinaexcelweb.cab#version=4,2,0,0'  name=\"CellWeb1\" id=\"CellWeb1\" style=\"DISPLAY: none;LEFT: 130px; TOP: 194px; POSITION: ABSOLUTE;\">";
str+="<param name=\"_Version\" value=\"65536\">";
str+="<param name=\"_ExtentX\" value=\"20505\">";
str+="<param name=\"_ExtentY\" value=\"14155\">";
str+="<param name=\"_StockProps\" value=\"0\">";
str+="</OBJECT>";
str+="</div>";
str+="<input type=hidden id=CellVersion name=CellVersion value='4.2.0.0'>";
document.write(str);