/*
 * JSP generated by Resin-3.1.8 (built Mon, 17 Nov 2008 12:15:21 PST)
 */

package _jsp._meeting._data;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.Calendar;
import net.sf.json.JSONObject;
import weaver.hrm.User;
import weaver.hrm.HrmUserVarify;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import weaver.general.Util;
import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import java.text.SimpleDateFormat;
import java.util.Date;
import net.sf.json.JsonConfig;
import weaver.systeminfo.SystemEnv;
import java.util.StringTokenizer;
import weaver.WorkPlan.MutilUserUtil;
import weaver.meeting.MeetingShareUtil;

public class _calendardata__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("application/x-json;charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      weaver.conn.RecordSet recordSet;
      recordSet = (weaver.conn.RecordSet) pageContext.getAttribute("recordSet");
      if (recordSet == null) {
        recordSet = new weaver.conn.RecordSet();
        pageContext.setAttribute("recordSet", recordSet);
      }
      
	response.setHeader("cache-control", "no-cache");
	response.setHeader("pragma", "no-cache");
	response.setHeader("expires", "Mon 1 Jan 1990 00:00:00 GMT");

	User user = HrmUserVarify.getUser(request, response);
	//if(user == null)  return ;
	Log logger = LogFactory.getLog(this.getClass());

	//onmousemove="coordinateReport()"
	/*
	 * \u9875\u9762\u53c2\u6570\u63a5\u6536
	 * \u6570\u636e\u5e93\u6570\u636e\u8bfb\u53d6
	 */
	Calendar thisCalendar = Calendar.getInstance(); //\u5f53\u524d\u65e5\u671f
	Calendar selectCalendar = Calendar.getInstance(); //\u7528\u4e8e\u663e\u793a\u7684\u65e5\u671f
	Calendar currntCalendar = Calendar.getInstance();

	int countDays = 0; //\u9700\u8981\u663e\u793a\u7684\u5929\u6570
	int offsetDays = 0; //\u76f8\u5bf9\u663e\u793a\u663e\u793a\u7b2c\u4e00\u5929\u7684\u504f\u79fb\u5929\u6570
	String thisDate = ""; //\u5f53\u524d\u65e5\u671f
	String selectDate = ""; //\u7528\u4e8e\u663e\u793a\u65e5\u671f

	String beginDate = "";
	String endDate = "";

	String beginYear = "";
	String beginMonth = "";
	String beginDay = "";

	String endYear = "";
	String endMonth = "";
	String endDay = "";

	//\u53c2\u6570\u4f20\u9012
	String userId = String.valueOf(user.getUID()); //\u5f53\u524d\u7528\u6237Id
	String userType = user.getLogintype(); //\u5f53\u524d\u7528\u6237\u7c7b\u578b
	String selectUser = Util.null2String(request
			.getParameter("selectUser")); //\u88ab\u9009\u62e9\u7528\u6237Id	
	String selectedType = Util.null2String(request
			.getParameter("selectedType")); //\u88ab\u9009\u62e9\u7c7b\u578b
	String selectedDept = Util.null2String(request
			.getParameter("selectedDept")); //\u88ab\u9009\u62e9\u90e8\u95e8
	String selectedSub = Util.null2String(request
			.getParameter("selectedSub")); //\u88ab\u9009\u62e9\u5206\u90e8			
	String hasrightview = Util.null2String(request
			.getParameter("hasrightview")); //\u662f\u5426\u6709\u6743\u9650\u67e5\u770b	
	String viewType = request.getParameter("viewtype"); //1:\u65e5\u8ba1\u5212\u663e\u793a 2:\u5468\u8ba1\u5212\u663e\u793a 3:\u6708\u8ba1\u5212\u663e\u793a
	String selectDateString = Util.null2String(request
			.getParameter("selectdate")); //\u88ab\u9009\u62e9\u65e5\u671f
	String isShare = Util.null2String(request.getParameter("isShare")); //\u662f\u5426\u662f\u5171\u4eab    1\uff1a\u5171\u4eab\u65e5\u7a0b
	String selectUserNames = Util.null2String(request
			.getParameter("selectUserNames")); //\u67e5\u770b\u5176\u4ed6\u4eba\u59d3\u540d
	String meetingType =  Util.null2String(request
			.getParameter("meetingType")); //\u4f1a\u8bae\u7684\u8fdb\u884c\u72b6\u6001
	
    SimpleDateFormat SDF = new SimpleDateFormat("yyyy-MM-dd HH:mm") ;
    Calendar calendar = Calendar.getInstance() ;
    String currenttime = SDF.format(calendar.getTime()) ;
	
	boolean appendselectUser = false;

	viewType = "day".equals(viewType) ? "1"
			: ("week".equals(viewType) ? "2" : "3");

	if ("".equals(selectUser) || userId.equals(selectUser)) {
		appendselectUser = true;
		selectUser = userId;
	}
	selectUser = selectUser.replaceAll(",", "");
	
	String allUser=MeetingShareUtil.getAllUser(user);
	
	String thisYear = Util.add0((thisCalendar.get(Calendar.YEAR)), 4); //\u5f53\u524d\u5e74
	String thisMonth = Util.add0(
			(thisCalendar.get(Calendar.MONTH)) + 1, 2); //\u5f53\u524d\u6708
	String thisDayOfMonth = Util.add0((thisCalendar
			.get(Calendar.DAY_OF_MONTH)), 2); //\u5f53\u524d\u65e5
	thisDate = thisYear + "-" + thisMonth + "-" + thisDayOfMonth;

	if (!"".equals(selectDateString))
	//\u5f53\u9009\u62e9\u65e5\u671f
	{
		int selectYear = Util.getIntValue(selectDateString.substring(0,
				4)); //\u88ab\u9009\u62e9\u5e74
		int selectMonth = Util.getIntValue(selectDateString.substring(
				5, 7)) - 1; //\u88ab\u9009\u62e9\u6708
		int selectDay = Util.getIntValue(selectDateString.substring(8,
				10)); //\u88ab\u9009\u62e9\u65e5
		selectCalendar.set(selectYear, selectMonth, selectDay);
	}

	String selectYear = Util.add0((selectCalendar.get(Calendar.YEAR)),
			4); //\u5e74 
	String selectMonth = Util.add0(
			(selectCalendar.get(Calendar.MONTH)) + 1, 2); // \u6708
	String selectDayOfMonth = Util.add0((selectCalendar
			.get(Calendar.DAY_OF_MONTH)), 2); //\u65e5    
	String selectWeekOfYear = String.valueOf(selectCalendar
			.get(Calendar.WEEK_OF_YEAR)); //\u7b2c\u51e0\u5468
	String selectDayOfWeek = String.valueOf(selectCalendar
			.get(Calendar.DAY_OF_WEEK)); //\u4e00\u5468\u7b2c\u51e0\u5929
	selectDate = selectYear + "-" + selectMonth + "-"
			+ selectDayOfMonth;

	switch (Integer.parseInt(viewType))
	//\u8bbe\u7f6e\u4e3a\u663e\u793a\u7684\u7b2c\u4e00\u5929
	{
	case 1:
		//\u65e5\u663e\u793a
		offsetDays = 0;
		break;
	case 2:
		//\u5468\u663e\u793a
		offsetDays = Integer.parseInt(selectDayOfWeek) - 1;
		selectCalendar.add(Calendar.DAY_OF_WEEK, -1
				* Integer.parseInt(selectDayOfWeek) + 1);
		break;
	case 3:
		//\u6708\u663e\u793a
		selectCalendar.set(Calendar.DATE, 1); //\u8bbe\u7f6e\u4e3a\u6708\u7b2c\u4e00\u5929
		int offsetDayOfWeek = selectCalendar.get(Calendar.DAY_OF_WEEK) - 1;
		offsetDays = Integer.parseInt(selectDayOfMonth) - 1
				+ offsetDayOfWeek;
		selectCalendar.add(Calendar.DAY_OF_WEEK, -1 * offsetDayOfWeek); //\u8bbe\u7f6e\u4e3a\u6708\u9996\u65e5\u90a3\u5468\u7684\u7b2c\u4e00\u5929
		break;
	}
	beginYear = Util.add0(selectCalendar.get(Calendar.YEAR), 4); //\u5e74 
	beginMonth = Util.add0(selectCalendar.get(Calendar.MONTH) + 1, 2); // \u6708
	beginDay = Util.add0(selectCalendar.get(Calendar.DAY_OF_MONTH), 2); //\u65e5 
	beginDate = beginYear + "-" + beginMonth + "-" + beginDay;
	//System.out.println("viewType:" + viewType);
	switch (Integer.parseInt(viewType))
	//\u8bbe\u7f6e\u4e3a\u663e\u793a\u7684\u6700\u540e\u4e00\u5929
	{
	case 1:
		//\u65e5\u8ba1\u5212\u663e\u793a
		countDays = 1;
		break;
	case 2:
		//\u5468\u8ba1\u5212\u663e\u793a
		selectCalendar.add(Calendar.WEEK_OF_YEAR, 1);
		selectCalendar.add(Calendar.DATE, -1);
		countDays = 7;
		break;
	case 3:
		//\u6708\u8ba1\u5212\u663e\u793a
		selectCalendar.add(Calendar.DATE, offsetDays);
		//System.out.println("######" + selectCalendar.get(Calendar.DATE));
		selectCalendar.set(Calendar.DATE, 1); //\u8bbe\u7f6e\u4e3a\u6708\u7b2c\u4e00\u5929
		selectCalendar.add(Calendar.MONTH, 1);
		selectCalendar.add(Calendar.DATE, -1);
		countDays = selectCalendar.get(Calendar.DAY_OF_MONTH); //\u5f53\u6708\u5929\u6570
		int offsetDayOfWeekEnd = 7 - selectCalendar
				.get(Calendar.DAY_OF_WEEK);
		selectCalendar.add(Calendar.DAY_OF_WEEK, offsetDayOfWeekEnd); //\u8bbe\u7f6e\u4e3a\u6708\u672b\u65e5\u90a3\u5468\u7684\u6700\u540e\u4e00\u5929
		break;
	}
	endYear = Util.add0(selectCalendar.get(Calendar.YEAR), 4); //\u5e74 
	endMonth = Util.add0(selectCalendar.get(Calendar.MONTH) + 1, 2); // \u6708
	endDay = Util.add0(selectCalendar.get(Calendar.DAY_OF_MONTH), 2); //\u65e5
	endDate = endYear + "-" + endMonth + "-" + endDay;
	

	//String temptable = WorkPlanShareBase.getTempTable(userId);
	StringBuffer sqlStringBuffer = new StringBuffer();

	sqlStringBuffer
			.append("SELECT DISTINCT t1.id,t1.name,t1.address,t1.customizeAddress,t1.caller,t1.contacter,t1.begindate,t1.begintime,t1.enddate,t1.endtime,t1.meetingstatus,t1.isdecision, t3.status as status,t.id as tid, t.name as typename ")
			.append(" FROM Meeting_ShareDetail t2,   Meeting t1 left join Meeting_View_Status t3 on t3.meetingId = t1.id and t3.userId = " + userId + ", Meeting_Type  t   ");
	sqlStringBuffer.append(" WHERE t1.meetingtype = t.id");
	
	sqlStringBuffer.append(" and (t1.id = t2.meetingId) and t1.repeatType = 0  AND");
	sqlStringBuffer.append(" ((t1.meetingStatus in (1, 3) and t2.userId in ( " + allUser + ") AND t2.shareLevel in (1,4))" );
	sqlStringBuffer.append(" OR (t1.meetingStatus = 0  AND t1.creater in ( " + allUser + ")  AND (t2.userId in ( " + allUser + ")) )");
	sqlStringBuffer.append(" OR (t1.meetingStatus IN (2, 4) AND (t2.userId in ( " + allUser + ")))) ");
	if(!userId.equals(selectUser)){
		if("2".equals(selectedType)){
			//\u90e8\u95e8
			sqlStringBuffer.append(" and ( exists (select 1 from HrmResource where t1.caller = HrmResource.id and HrmResource.departmentid = "+ selectedDept +") ) ");
		} else if("3".equals(selectedType)){
			//\u5206\u90e8
			sqlStringBuffer.append(" and ( exists (select 1 from HrmResource where t1.caller = HrmResource.id and HrmResource.subcompanyid1 = "+ selectedSub +") ) ");
		} else {
			//\u4eba\u5458
			sqlStringBuffer.append(" and ( exists ( select 1 from Meeting_Member2 where t1.id = Meeting_Member2.meetingid and Meeting_Member2.membertype = 1 and Meeting_Member2.memberid = "+ selectUser +") or t1.caller = "+ selectUser +" or t1.contacter = "+ selectUser +") ");
		}
	}
	 
	//\u53d6\u6d88\u7684\u4f1a\u8bae\u4e0d\u5728\u65e5\u5386\u4e2d\u663e\u793a
    sqlStringBuffer.append(" and (t1.cancel <> 1 or t1.cancel is null) ");
	sqlStringBuffer.append(" AND ( (t1.beginDate >= '");
	sqlStringBuffer.append(beginDate);
	sqlStringBuffer.append("' AND t1.beginDate <= '");
	sqlStringBuffer.append(endDate);
	sqlStringBuffer.append("') OR ");
	sqlStringBuffer.append(" (t1.endDate >= '");
	sqlStringBuffer.append(beginDate);
	sqlStringBuffer.append("' AND t1.endDate <= '");
	sqlStringBuffer.append(endDate);
	sqlStringBuffer.append("') OR ");
	sqlStringBuffer.append(" (t1.endDate >= '");
	sqlStringBuffer.append(endDate);
	sqlStringBuffer.append("' AND t1.beginDate <= '");
	sqlStringBuffer.append(beginDate);
	sqlStringBuffer.append("') OR ");
	sqlStringBuffer
			.append(" ((t1.endDate IS null OR t1.endDate = '') AND t1.beginDate <= '");
	sqlStringBuffer.append(beginDate);
	sqlStringBuffer.append("') )");
	
	String btimeStr = "t1.beginDate+' '+t1.begintime ";
	String etimeStr = "t1.endDate+' '+t1.endtime ";
	if ((recordSet.getDBType()).equals("oracle")) {
	 	btimeStr = "t1.beginDate||' '||t1.begintime ";
	 	etimeStr = "t1.endDate||' '||t1.endtime ";
	}
	if("1".equals(meetingType)){
		sqlStringBuffer.append(" AND ("+etimeStr+" < '"+ currenttime + "' ");
		sqlStringBuffer.append(" or t1.isdecision = 2 ) ");
	} else if("2".equals(meetingType)){
		sqlStringBuffer.append(" AND ("+btimeStr+" <= '"+ currenttime + "' ");
		sqlStringBuffer.append("   AND "+etimeStr+" >= '"+ currenttime + "' and t1.isdecision <> 2) ");
	
	} else if("3".equals(meetingType)){
		sqlStringBuffer.append(" AND (("+btimeStr+" > '"+ currenttime + "' and t1.isdecision <> 2) )");
	}
	
	sqlStringBuffer.append(" order by t1.beginDate ,t1.begintime, t1.id ");

	//System.out.println("######" + beginDate); 
	//System.out.println("######" + endDate);
	recordSet.executeSql(sqlStringBuffer.toString());
	//recordSet.writeLog(sqlStringBuffer.toString());
	//System.out.println(sqlStringBuffer.toString());
	Map result = new HashMap();
	List eventslist = new ArrayList();
	SimpleDateFormat format = new SimpleDateFormat("MM/dd/yyyy HH:mm");
	SimpleDateFormat format2 = new SimpleDateFormat("yyyy-MM-dd HH:mm");
	SimpleDateFormat format3 = new SimpleDateFormat("HH:mm");
	int meetingstatus = 0;
	while (recordSet.next()) {
		try {
			boolean isAllDay = false;
			List event = new ArrayList();
			meetingstatus = Util.getIntValue(recordSet.getString("meetingstatus"), 0);
			String isdecision=recordSet.getString("isdecision");
			event.add(recordSet.getString("id"));
			if(meetingstatus == 0)
			{
				event.add("("+SystemEnv.getHtmlLabelName(220, user.getLanguage())+")"+recordSet.getString("name"));
			}else if(meetingstatus==1){
				event.add("("+SystemEnv.getHtmlLabelName(2242, user.getLanguage())+")"+recordSet.getString("name"));
			}else if(meetingstatus==3){
				event.add("("+SystemEnv.getHtmlLabelName(236, user.getLanguage())+")"+recordSet.getString("name"));
			}else {
				event.add(recordSet.getString("name"));
			}
			Date startDate = format2.parse(recordSet.getString(
					"begindate").trim()
					+ " " + recordSet.getString("begintime").trim());
			event.add(format.format(startDate));
			if (format2.parse(beginDate + " 00:00").getTime()
					- startDate.getTime() > 0) {
				beginDate = recordSet.getString("begindate");
			}
			Date endDate2 = null;
			if (!"".equals(recordSet.getString("enddate"))) {
				String endTime = recordSet.getString("endtime");
				if ("".equals(endTime.trim())) {
					endTime = "23:59";
				}
				endDate2 = format2.parse(recordSet
						.getString("enddate")
						+ " " + endTime);
				//if (endDate2.getTime() - startDate.getTime() > 0
						//|| endDate2.getHours() - startDate.getHours() >= 24||endDate2.getYear()-startDate.getYear()>0) {
				if(recordSet.getString("enddate").compareTo(recordSet.getString("begindate")) > 0){
					isAllDay = true;
				} else {

				}

				event.add(format.format(endDate2));
			} else {
				endDate = "01/01/10000";
				event.add("01/01/10000 00:00");
				isAllDay = true;
			}

			event.add("0");
			if (isAllDay) {
				event.add("1");//\u662f\u4e0d\u662f\u5168\u5929
			} else {
				event.add("0");
			}

			event.add("0");//,0,1,0,-1,1,
			
			if("2".equals(isdecision)){
				event.add("0");
			} else {
				if(startDate.getTime() >  currntCalendar.getTime().getTime()){
					event.add("2");
				} else if(endDate2 != null && currntCalendar.getTime().getTime() <= endDate2.getTime()){
					event.add("1");
				} else {
					event.add("0");
				}
			}
			
			event.add("");
			event.add("0");
			event.add("");
			event.add("");
			eventslist.add(event);
		} catch (Exception e) {
			
		}
	}

	result.put("events", eventslist);
	result.put("issort", ""+true);
	result.put("start", beginDate + " 00:00");
	result.put("end", endDate + " 23:59");
	result.put("error", null);

	JSONObject obj = JSONObject.fromObject(result);
	out.clearBuffer();
	out.print(obj.toString());

    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 1886798272571451039L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("meeting/data/CalendarData.jsp"), -1564644842316337651L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string0;
  static {
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
  }
}
