/*
 * JSP generated by Resin-3.1.8 (built Mon, 17 Nov 2008 12:15:21 PST)
 */

package _jsp._meeting._data;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import weaver.general.*;
import java.util.*;

public class _chkmeetingroom__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=GBK");
    request.setCharacterEncoding("GBK");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      weaver.conn.RecordSet RecordSet;
      RecordSet = (weaver.conn.RecordSet) pageContext.getAttribute("RecordSet");
      if (RecordSet == null) {
        RecordSet = new weaver.conn.RecordSet();
        pageContext.setAttribute("RecordSet", RecordSet);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      weaver.meeting.Maint.MeetingSetInfo meetingSetInfo;
      meetingSetInfo = (weaver.meeting.Maint.MeetingSetInfo) pageContext.getAttribute("meetingSetInfo");
      if (meetingSetInfo == null) {
        meetingSetInfo = new weaver.meeting.Maint.MeetingSetInfo();
        pageContext.setAttribute("meetingSetInfo", meetingSetInfo);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      weaver.meeting.Maint.MeetingRoomComInfo MeetingRoomComInfo;
      MeetingRoomComInfo = (weaver.meeting.Maint.MeetingRoomComInfo) pageContext.getAttribute("MeetingRoomComInfo");
      if (MeetingRoomComInfo == null) {
        MeetingRoomComInfo = new weaver.meeting.Maint.MeetingRoomComInfo();
        pageContext.setAttribute("MeetingRoomComInfo", MeetingRoomComInfo);
      }
      out.write(_jsp_string2, 0, _jsp_string2.length);
      
    String meetingaddress = Util.null2String(request.getParameter("address"));
	String begindate = Util.null2String(request.getParameter("begindate"));
	String begintime = Util.null2String(request.getParameter("begintime"));
	String enddate = Util.null2String(request.getParameter("enddate"));
	String endtime = Util.null2String(request.getParameter("endtime"));
	String requestid = Util.null2String(request.getParameter("requestid"));
	String meetingids=Util.null2String(request.getParameter("meetingid"));
	List<String> arr=new ArrayList();
	String returnstr = "0";
	if(meetingSetInfo.getRoomConflictChk() == 1 ){
		if(!"".equals(requestid)&&!"-1".equals(requestid)) {
		   RecordSet.executeQuery("select approveid from Bill_Meeting where requestid=?",requestid);
		   if(RecordSet.next()) {
			  meetingids = Util.null2String(RecordSet.getString("approveid"));
		   }
		}
		RecordSet.executeQuery("select address,begindate,enddate,begintime,endtime,id from meeting where meetingstatus in (1,2) and repeatType = 0 and isdecision<2 and (cancel is null or cancel<>'1') and (begindate <= ? and enddate >=?)",enddate,begindate);
		while(RecordSet.next()) {
			String begindatetmp = Util.null2String(RecordSet.getString("begindate"));
			String begintimetmp = Util.null2String(RecordSet.getString("begintime"));
			String enddatetmp = Util.null2String(RecordSet.getString("enddate"));
			String endtimetmp = Util.null2String(RecordSet.getString("endtime"));
			String addresstmp = Util.null2String(RecordSet.getString("address"));
			String mid = Util.null2String(RecordSet.getString("id"));

			String str1 = begindate+" "+begintime;
			String str2 = enddatetmp+" "+endtimetmp;
			String str3 = enddate+" "+endtime;
			String str4 = begindatetmp+" "+begintimetmp;

			String[] address=addresstmp.split(",");
			for(int i=0;i<address.length;i++){
				if(!"".equals(meetingaddress) && (","+meetingaddress+",").indexOf(","+address[i]+",")>-1 && !mid.equals(meetingids)) {
					if((str1.compareTo(str2) < 0 && str3.compareTo(str4) > 0)) {
						if(!arr.contains(address[i])){
							arr.add(address[i]);
						}
					}
				}
			}
		}
	}
	for(int i=0;i<arr.size();i++){
		String name=MeetingRoomComInfo.getMeetingRoomInfoname(arr.get(i));
		if("0".equals(returnstr)){
			returnstr="["+name+"]";
		}else{
			returnstr+="\n["+name+"]";
		}
	}
    response.setContentType("text/html;charset=utf-8");
    response.setHeader("Cache-Control", "no-cache");  
    out.write(returnstr);


      out.write(_jsp_string1, 0, _jsp_string1.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 1886798272571451039L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("meeting/data/ChkMeetingRoom.jsp"), 2240751078858223481L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string0;
  private final static char []_jsp_string1;
  private final static char []_jsp_string2;
  static {
    _jsp_string0 = "\r\n\r\n\r\n".toCharArray();
    _jsp_string1 = "\r\n".toCharArray();
    _jsp_string2 = "\r\n\r\n".toCharArray();
  }
}
