/*
 * JSP generated by Resin-3.1.8 (built Mon, 17 Nov 2008 12:15:21 PST)
 */

package _jsp._matrixmanage._pages;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import weaver.general.*;
import weaver.hrm.*;
import weaver.conn.*;
import org.json.*;
import java.math.*;
import java.text.*;
import weaver.matrix.*;
import java.sql.Timestamp;
import weaver.general.Util;
import weaver.docs.docs.CustomFieldManager;
import weaver.docs.docs.FieldParam;
import java.util.*;

public class _saveitems__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("application/json;charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      weaver.conn.RecordSetTrans RecordSetTrans;
      RecordSetTrans = (weaver.conn.RecordSetTrans) pageContext.getAttribute("RecordSetTrans");
      if (RecordSetTrans == null) {
        RecordSetTrans = new weaver.conn.RecordSetTrans();
        pageContext.setAttribute("RecordSetTrans", RecordSetTrans);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      weaver.conn.RecordSet RecordSet;
      RecordSet = (weaver.conn.RecordSet) pageContext.getAttribute("RecordSet");
      if (RecordSet == null) {
        RecordSet = new weaver.conn.RecordSet();
        pageContext.setAttribute("RecordSet", RecordSet);
      }
      out.write(_jsp_string2, 0, _jsp_string2.length);
      
out.clearBuffer();
User user = HrmUserVarify.getUser (request , response) ;
char flag=Util.getSeparator();
int userid=user.getUID();
request.setCharacterEncoding("UTF-8");
//RecordSet\u5bf9\u5e94\u7684sql
String rssql="";
//RecordSetTrans\u5bf9\u5e94\u7684sql
String sql="";
//\u6570\u636e\u5e93\u7c7b\u578b
String dbtype=RecordSet.getDBType();
List<String>  sqls=new ArrayList<String>();
StringBuffer sb=new StringBuffer("");
StringBuffer createsb=new StringBuffer("");
//\u4e3b\u8981\u5206\u66f4\u65b0\uff0c\u65b0\u589e\u90e8\u5206
List<Map<String,String>>  updateitems=new ArrayList<Map<String,String>>();
List<Map<String,String>>  additems=new ArrayList<Map<String,String>>();
List<String> updateids=new ArrayList<String>();
int  count=Integer.valueOf(request.getParameter("count"));
String[]  itemids=new String[count];
String[]  fieldlables=new String[count]; 
String[]  fieldorders=new String[count]; 
String[]  htmltypes=new String[count]; 
String[]  iscusttypes=new String[count]; 
String[]  namelabels=new String[count]; 
String[]  types=new String[count]; 
String[]  typeids=new String[count]; 
String[]  widths=new String[count];
String matrixid=request.getParameter("matrixid");


//\u77e9\u9635\u5bf9\u5e94\u7684\u8868\u540d
String matrixtablename=MatrixUtil.MATRIXPREFIX+matrixid;
String itemid;
String fieldlable;
String filedorder;
String htmltype;
String iscusttype;
String namelabel;
String typeid;
String type;
String width;

String fieldname;
String fieldlabel;
boolean needadd=true;

Map<String,String>  item;
//\u83b7\u53d6\u8868\u5355\u6570\u636e
for(int i=0;i<count;i++){
	
	itemids[i]=request.getParameter("itemid_"+i);
	fieldlables[i]=request.getParameter("fieldlable_"+i);
	fieldorders[i]=request.getParameter("filedorder_"+i);
	htmltypes[i]=request.getParameter("htmltype_"+i);
	iscusttypes[i]=request.getParameter("iscusttype_"+i);
	namelabels[i]=request.getParameter("namelabel_"+i);
	types[i]=request.getParameter("type_"+i);
	typeids[i]=request.getParameter("typeid_"+i);
	widths[i]=request.getParameter("width_"+i);
}
//\u83b7\u53d6\u65b0\u589e,\u66f4\u65b0\u6761\u76ee
for(int i=0;i<itemids.length;i++){
	 itemid=itemids[i];
	 item=new HashMap<String,String>();
	 item.put("itemid",itemid);
	 item.put("fieldlabel",fieldlables[i]);
	 item.put("fieldorder",fieldorders[i]);
	 item.put("htmltype",htmltypes[i]);
	 item.put("iscusttype",iscusttypes[i]);
	 item.put("namelabel",namelabels[i]);
	 item.put("typeid",typeids[i]);
	 item.put("type",types[i]);
	 //item.put("width",widths[i]);
	 String thiswidth = widths[i];
	 if(thiswidth.indexOf(".")>0){
		 thiswidth = thiswidth.substring(0,thiswidth.indexOf("."));
	 }
	 item.put("width",thiswidth);
	 //\u65b0\u589e\u6761\u76ee
	 if("".equals(itemid)){
	    additems.add(item);
	 //\u66f4\u65b0\u6761\u76ee	 
	 }else{
	    updateitems.add(item); 
	    updateids.add(itemid); 
	 }
	 
}

//\u662f\u5426\u662f\u7b2c\u4e00\u6b21\u521b\u5efa\u8868 1\u8868\u793a\u7b2c\u4e00\u6b21\u521b\u5efa 0 \u975e\u7b2c\u4e00\u6b21\u521b\u5efa
String firstcreatetable = "0";

//\u5224\u65ad\u8868\u540d\u662f\u5426\u521b\u5efa
rssql="select *  from MatrixFieldInfo where matrixid='"+matrixid+"'";
RecordSet.execute(rssql);
//\u4e0d\u5b58\u5728\u8868\u8bb0\u5f55,\u5219\u9ed8\u8ba4\u65b0\u5efa\u8868
if(!RecordSet.next()){
    	
    createsb.append("create table "+matrixtablename).append(" ( uuid  varchar(100), dataorder  float, ");
	for(int i=0,len=additems.size();i<len;i++){
		createsb.append(additems.get(i).get("fieldlabel")).append(" varchar(1000) ").append(",");	
	}
	rssql = createsb.substring(0,createsb.length()-1)+" ) ";
	//\u751f\u6210\u8868\u7ed3\u6784
    new RecordSet().execute(rssql);
	
	//\u5224\u65ad\u66f4\u65b0\u8fd8\u662f\u65b0\u5efa  true:update false:new
    needadd=false;
	//\u4e00\u6b21\u521b\u5efa
    firstcreatetable= "1";
}

//\u6784\u5efasql 1.\u5220\u9664\u6761\u76ee,\u66f4\u65b0\u6761\u76ee,\u6dfb\u52a0\u6761\u76ee
if(updateids.size()>0){
	String tempstr="";
	for(int i=0,len=updateids.size();i<len;i++){
		sb.append("'"+updateids.get(i)+"'").append(",");
	}
	if(sb.length()>0){
		tempstr=sb.substring(0,sb.length()-1);
	}
	if(needadd){
		rssql="select fieldname from MatrixFieldInfo where id not in ("+tempstr+")  and matrixid='"+matrixid+"'";
		RecordSet.execute(rssql);
		//\u5220\u9664\u6570\u636e\u5217
		while(RecordSet.next()){
		    sql="alter table "+matrixtablename+" drop column "+RecordSet.getString("fieldname");	
			sqls.add(sql);
		}
	}
	sql="delete from MatrixFieldInfo where id not in ("+tempstr+")  and matrixid='"+matrixid+"'";
	sqls.add(sql);
}
//\u66f4\u65b0\u6761\u76ee
if(updateitems.size()>0){
	 
	for(Map<String,String>  itemdata:updateitems){
	      
		rssql="select fieldname  from MatrixFieldInfo where id='"+itemdata.get("itemid")+"'";
		RecordSet.execute(rssql);
		if(RecordSet.next()){
			fieldname=RecordSet.getString("fieldname");
			fieldlabel=itemdata.get("fieldlabel");
		    //\u66f4\u6539\u5217\u540d\u64cd\u4f5c
			if(!fieldname.equals(fieldlabel)){
		 		if("oracle".equals(dbtype) || "db2".equals(dbtype)){
		    	   sql="alter table "+matrixtablename+" rename column "+fieldname+" to "+fieldlabel+"";	
		    	}else if("sqlserver".equals(dbtype)){
		    	   sql="EXEC sp_rename '"+matrixtablename+"."+fieldname+"', '"+fieldlabel+"', 'COLUMN'";
		    	}
				sqls.add(sql);
		    }
		 }
		 sql="update MatrixFieldInfo set browsertypeid='"+itemdata.get("htmltype")+"',browservalue='"+itemdata.get("typeid")+"',custombrowser='"+itemdata.get("iscusttype")+"',displayname='"+itemdata.get("namelabel")+"',fieldname='"+itemdata.get("fieldlabel")+"',fieldtype='"+itemdata.get("type")+"',priority='"+itemdata.get("fieldorder")+"',colwidth='"+itemdata.get("width")+"'  where id='"+itemdata.get("itemid")+"'";
	     sqls.add(sql);
	}
	
}
//\u65b0\u589e\u6761\u76ee
if(additems.size()>0){
	//\u83b7\u53d6 \u6700\u5927\u7684id
	int mfmaxid = 0;
	RecordSet.executeSql("select max(id) as id from MatrixFieldInfo");
	while(RecordSet.next()){
		mfmaxid = Util.getIntValue(RecordSet.getString("id"),1);
	}

	for(Map<String,String>  itemdata:additems){
		 
		 if(needadd){
			 //\u6dfb\u52a0\u5217
			 sql="alter table "+matrixtablename+" add "+itemdata.get("fieldlabel")+" varchar(1000)";
			 sqls.add(sql);
		 }
		 
		//\u63d2\u5165\u5217\u8be6\u7ec6\u4fe1\u606f
		  mfmaxid ++;
		 if("oracle".equals(dbtype)){
			 sql="insert into MatrixFieldInfo(id,matrixid,browsertypeid,browservalue,custombrowser,displayname,fieldname,fieldtype,priority,colwidth) values("+mfmaxid+",'"+matrixid+"','"+itemdata.get("htmltype")+"','"+itemdata.get("typeid")+"','"+itemdata.get("iscusttype")+"','"+itemdata.get("namelabel")+"','"+itemdata.get("fieldlabel")+"','"+itemdata.get("type")+"','"+itemdata.get("fieldorder")+"','"+itemdata.get("width")+"')";
	      }else if("sqlserver".equals(dbtype)){
	    	  sql="insert into MatrixFieldInfo(matrixid,browsertypeid,browservalue,custombrowser,displayname,fieldname,fieldtype,priority,colwidth) values('"+matrixid+"','"+itemdata.get("htmltype")+"','"+itemdata.get("typeid")+"','"+itemdata.get("iscusttype")+"','"+itemdata.get("namelabel")+"','"+itemdata.get("fieldlabel")+"','"+itemdata.get("type")+"','"+itemdata.get("fieldorder")+"','"+itemdata.get("width")+"')";
	     }
		 
		 
	     sqls.add(sql);
	}
}
try{
	RecordSetTrans.setAutoCommit(false);
	for(String sqlitem:sqls){
		//System.out.println(sqlitem );
		RecordSetTrans.execute(sqlitem);
	}	
	//\u63d0\u4ea4\u4e8b\u52a1
	RecordSetTrans.commit();
    String fieldinfojson=MatrixUtil.getMatrixJsonByIdForDesignList(matrixid);
	out.println("{\"success\":\"1\",\"fieldarray\":"+fieldinfojson+",\"firstcreatetable\":\""+firstcreatetable+"\"}");
	//out.println("{\"success\":\"1\"}");
}catch(Exception e){
	//e.printStackTrace();
	out.println("{\"success\":\"0\"}");
}




    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 1886798272571451039L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("matrixmanage/pages/saveitems.jsp"), -827369255809532546L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string0;
  private final static char []_jsp_string1;
  private final static char []_jsp_string2;
  static {
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string1 = "\r\n".toCharArray();
    _jsp_string2 = "\r\n\r\n".toCharArray();
  }
}
