var wmsg = {
	wfdesign : {
		newFlow : 'New',
		editFlow : 'Edit',
		openFlow : 'Open',
		saveFlow : 'Save',
		undo : 'Undo',
		redo : 'Redo',
		del : 'Delete',
		create : 'Create',
		realize : 'Realize',
		approve : 'Approve',
		fork : 'Fork',
		join : 'Join',
		child : 'Child',
		process : 'Process',
		step : 'Step',
		alignLeft : 'Align Left',
		alignRight : 'Align Right',
		alignCenter : 'Align Center',
		lignTop : 'Lign Top',
		lignBottom : 'Lign Bottom',
		lignMiddle : 'Lign Midddle',
		grid : 'Grid',
		validate : 'Validate',
		title : 'Workflow Design',
		property : 'Property',
		name : 'Name',
		value : 'Value',
		nodeName : 'ProcName',
		formSignature : 'IsFormSignature',
		rightMenu : 'RightMenu',
		preAddInOperate : 'PreAdditionalOperation',
		addInOperate : 'FollowedAdditionalOperation',
		logBrownser : 'RangeOfWorkflowLogTracing',
		nodeFormField : 'NodeFormField',
		createDoc : 'Create Document through WorkFlow',
		oerator : 'Opeator',
		childFlowOut : 'Data Exit',
		onlyOneCreate : 'Only One Create',
		noOutput : 'No Output',
		onlyOneProcess : 'Only One Process',
		noInput : 'NO Input',
		approveTwoMoreOutput : 'Approve Should Be Two More Output',
		forkTwoMoreOutput : 'Fork Should Be Two More Output',
		joinTwoMoreInput : 'Join Should Be Two More Input',
		stepName : 'StepName',
		createNumber : 'BulidCode',
		stepRemindMsg : 'TipsExportInformation',
		condition : 'Condition',
		stepAddInOperate : 'TheAdditionalRule',
		validateSuccess : 'Validate Success',
		deleteConfrim : 'Sure to Delelte?',
		yes : 'Yes',
		no : 'No',
		confrim : 'Confrim',
		cancel : 'Cancel',
		purposeNode : 'PurposeNode',
		type : 'Type',
		close : 'Close',
		fullScreen : 'Full Screen',
		isReject : 'WheatherWithdraw',
		info : 'Information',
		error : 'Error',
		procTitleInfo:'ProcProperty',
		flow:'FlowName',
		form:'Form',
		checkinError:'Log on overtime or network connection failure，check in failure!',
		checkoutMsg:'Flow has be check out，you can view it，but can not edit!',
		flowType:'Type of Flow',
		passnum:'PassNumber',
		showText:'Show Title',
		noInSameBranch:'Step Not In the Same Branch',
		stepExist:'Step Existed!',
		notSelf:'Direct to Self！',
		stepRule:'Step Can not  Start from Process',
		maxPoints :'At most 5 Points',
		noUndo:'No Undo Record',
		noRedo:'No Redo Record',
		noFocus:'No Selection！Please Click on It to Select',
		autoCreateStep:'Auto Create Step',
		selectProcNumber:'Select Proc Number',
		input:'Custom Input...',
		inputProcNumber:'Please Input the Number of Proc to Create(suggestion:No more than 50):',
		inputInt:'Please Input Valid Number',
		propertyWin:'Property Window',
		saveFailure:'Save Failure',
		saveSuccess:'Save Success',
		loadFailure:'Load Failure',
		procAddFailure:'Add Proc Failure',
		stepAddFailure:'Add Step Failure',
		select:'Select',
		clickToAddProc :'Please click on where you want to add the procs',
		processing:'Data processing,please wait',
		saveConfirm:'Continue Save?',
		validateFailure:'Validate Failure',
		passType :'JoinType',
		passByMum :'ThroughSeveralBranches',
		mustPass:'ThroughDesignatedBranches ',
		percentPass:'The combined percentage',
		Passpercent:'Pass percentage(%)',
		notNull:"The essential information is not intact!",
		adjustLine:"Auto Adjust Step",
		info:"Explanation",
		hasRole:"Step has the additional rule",
		hasCondition:"Step has the condition",
		hasRoleAndCondition:"Step has the condition and the additional rule",
		addSelfConfrim:"Add step that goes to itself,Sure?",
		saveBefore:"Should save before to do this, save now?",
		titleShowConfig:"Title display config",
		signIdeaConfig:"Sign opinion config",
		turnForwardConfig:"Turn forward config",
		freeFlowConfig:"Free flow config",
		subWorkFlowConfig:"Sub-workflow config",
		exceptionHandleConfig:"Flow exception handle"
	}
}

