

var wmsg = {
	wfdesign : {
		newFlow : '新建',
		editFlow : '編輯',
		openFlow : '打開',
		saveFlow : '保存',
		undo : '撤消',
		redo : '恢復',
		del : '刪除',
		create : '創建',
		realize : '處理',
		approve : '審批',
		fork : '分叉',
		join : '合并',
		child : '子流程',
		process : '歸檔',
		step : '出口',
		alignLeft : '左對齊',
		alignRight : '右對齊',
		alignCenter : '左右等間對齊',
		lignTop : '上對齊',
		lignBottom : '下對齊',
		lignMiddle : '上下等間對齊',
		grid : '網格',
		validate : '驗證',
		title : '工作流設計',
		property : '屬性',
		name : '名稱',
		value : '值',
		nodeName : '節點名稱',
		formSignature : '是否表單簽章',
		rightMenu : '操作菜單',
		preAddInOperate : '節點前附加操作',
		addInOperate : '節點后附加操作',
		logBrownser : '日志查看范圍',
		nodeFormField : '節點表單字段',
		createDoc : '流程創建文檔',
		oerator : '操作者',
		childFlowOut : '數據出口',
		onlyOneCreate : '只能有一個創建節點',
		noOutput : '沒有出口',
		onlyOneProcess : '只能有一個歸檔節點',
		noInput : '沒有入口',
		approveTwoMoreOutput : '審批節點至少應該有兩條或兩條以上的出口',
		forkTwoMoreOutput : '分叉節點至少應該有兩條或兩條以上的出口',
		joinTwoMoreInput : '合并節點至少應該有兩條或兩條以上的入口',
		stepName : '出口名稱',
		createNumber : '生成編號',
		stepRemindMsg : '出口提示信息',
		condition : '條件',
		stepAddInOperate : '附加規則',
		validateSuccess : '合法流程',
		deleteConfrim : '確定要刪除嗎？',
		yes : '是',
		no : '否',
		confrim : '確定',
		cancel : '取消',
		purposeNode : '目標節點',
		type : '類型',
		close : '關閉',
		fullScreen : '全屏',
		isReject : '是否退回',
		info : '提示',
		error : '錯誤',
		procTitleInfo:'節點屬性',
		flow:'流程名稱',
		form:'表單',
		checkinError:'登陸超時或網絡連接中斷，簽入失敗',
		checkoutMsg:'流程已被簽出，您只能查看該流程，但無法編輯!',
		flowType:'流程類型',
		passnum:'通過分支數',
		showText:'顯示文字',
		noInSameBranch:'出口不在同一分支中',
		stepExist:'出口已存在，請更改！',
		notSelf:'指向本身！',
		stepRule:'起點不能是歸檔節點！',
		maxPoints :'最多只能有5個頂點',
		noUndo:'沒有操作記錄可以撤銷',
		noRedo:'沒有操作記錄可以恢復',
		noFocus:'當前沒有選中對象！用鼠標單擊流程圖上的對象選中它',
		autoCreateStep:'自動連接節點',
		selectProcNumber:'選擇節點數',
		input:'自定義...',
		inputProcNumber:'請輸入要創建的節點數(建議最多50個):',
		inputInt:'請輸入有效數字',
		propertyWin:'屬性窗口',
		saveFailure:'流程保存失敗',
		saveSuccess:'流程保存成功',
		loadFailure:'流程載入失敗',
		procAddFailure:'節點添加失敗',
		stepAddFailure:'出口添加失敗',
		select:'請選擇',
		clickToAddProc :'請在需要的地方單擊滑鼠來添加節點',
		processing:'數據處理中，請稍候',
		saveConfirm:'繼續保存嗎?',
		validateFailure:'流程不合法',
		passType :'合并類型',
		passByMum :'通過分支數',
		mustPass:'指定通過分支',
		percentPass:'比例合併',
		Passpercent:'通过比例(%)',
		notNull:"必要信息不完整!",
		adjustLine:"自動調整出口",
		info:"說明",
		hasRole:"出口已設置附加規則",
		hasCondition:"出口已設置條件",
		hasRoleAndCondition:"出口已設置條件和附加規則",
		addSelfConfrim:"確定要添加指向本身的出口？",
		saveBefore:"請先保存後再進行此操作，現在保存嗎？",
		titleShowConfig:"标題顯示設置",
		signIdeaConfig:"簽字意見設置",
		turnForwardConfig:"轉發設置",
		freeFlowConfig:"自由流轉設置",
		subWorkFlowConfig:"子流程設置",
		exceptionHandleConfig:"流轉異常處理"
	}
}

