var wmsg = {
	wfdesign : {
		newFlow : '新建',
		editFlow : '编辑',
		openFlow : '打开',
		saveFlow : '保存',
		undo : '撤消',
		redo : '恢复',
		del : '删除',
		create : '创建',
		realize : '处理',
		approve : '审批',
		fork : '分叉',
		join : '合并',
		child : '子流程',
		process : '归档',
		step : '出口',
		alignLeft : '左对齐',
		alignRight : '右对齐',
		alignCenter : '左右等间对齐',
		lignTop : '上对齐',
		lignBottom : '下对齐',
		lignMiddle : '上下等间对齐',
		grid : '网格',
		validate : '验证',
		title : '工作流设计',
		property : '属性',
		name : '名称',
		value : '值',
		nodeName : '节点名称',
		formSignature : '是否表单签章',
		rightMenu : '操作菜单',
		preAddInOperate : '节点前附加操作',
		addInOperate : '节点后附加操作',
		logBrownser : '表单日志查看范围',
		nodeFormField : '表单内容',
		createDoc : '流程创建文档',
		oerator : '操作者',
		childFlowOut : '数据出口',
		onlyOneCreate : '只能有一个创建节点',
		noOutput : '没有出口',
		onlyOneProcess : '只能有一个归档节点',
		noInput : '没有入口',
		approveTwoMoreOutput : '审批节点至少应该有两条或两条以上的出口',
		forkTwoMoreOutput : '分叉节点至少应该有两条或两条以上的出口',
		joinTwoMoreInput : '合并节点至少应该有两条或两条以上的入口',
		stepName : '出口名称',
		createNumber : '生成编号',
		stepRemindMsg : '出口提示信息',
		condition : '条件',
		stepAddInOperate : '附加规则',
		validateSuccess : '合法流程',
		deleteConfrim : '确定要删除吗？',
		yes : '是',
		no : '否',
		confrim : '确定',
		cancel : '取消',
		purposeNode : '目标节点',
		type : '类型',
		close : '关闭',
		fullScreen : '全屏',
		isReject : '是否退回',
		info : '提示',
		error : '错误',
		procTitleInfo:'节点属性',
		flow:'流程名称',
		form:'表单',
		checkinError:'登录超时或网络连接中断,签入失败!',
		checkoutMsg:'流程已被签出,您只能查看该流程,但无法编辑!',
		flowType:'流程类型',
		passnum:'通过分支数',
		showText:'显示文字',
		noInSameBranch:'出口不在同一分支中',
		stepExist:'出口已存在，请更改！',
		notSelf:'指向本身！',
		stepRule:'起点不能是归档节点！',
		maxPoints :'最多只能有5个顶点',
		noUndo:'没有操作记录可以撤消',
		noRedo:'没有操作记录可以恢复',
		noFocus:'当前没有选中对象！用鼠标单击流程图上的对象可以选中它',
		autoCreateStep:'自动连接节点',
		selectProcNumber:'选择节点数',
		input:'自定义...',
		inputProcNumber:'请输入要创建的节点个数(建议最多50个):',
		inputInt:'请输入有效数字',
		propertyWin:'',
		saveFailure:'流程保存失败',
		saveSuccess:'流程保存成功',
		loadFailure:'流程载入失败',
		procAddFailure:'节点添加失败',
		stepAddFailure:'出口添加失败',
		select:'请选择',
		clickToAddProc :'请在需要的地方单击鼠标来添加节点',
		processing:'数据处理中，请稍候',
		saveConfirm:'继续保存吗?',
		validateFailure:'流程不合法',
		passType :'合并类型',
		passByMum :'通过分支数',
		mustPass:'指定通过分支',
		percentPass:'比例合并',
		Passpercent:'通过比例(%)',
		notNull:"必要信息不完整！",
		adjustLine:"自动调整出口",
		info:"说明",
		hasRole:"出口已设置附加规则",
		hasCondition:"出口已设置条件",
		hasRoleAndCondition:"出口已设置条件和附加规则",
		addSelfConfrim:"确定要添加指向本身的出口？",
		saveBefore:"请先保存后再进行此操作，现在保存吗？",
		titleShowConfig:"标题显示设置",
		signIdeaConfig:"签字意见设置",
		turnForwardConfig:"转发设置",
		freeFlowConfig:"自由流转设置",
		subWorkFlowConfig:"子流程设置",
		exceptionHandleConfig:"流转异常处理"
	}
}
