/*
 * JSP generated by Resin-3.1.8 (built Mon, 17 Nov 2008 12:15:21 PST)
 */

package _jsp._blog;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import weaver.blog.BlogManager;
import weaver.blog.BlogReportManager;
import weaver.conn.RecordSet;
import weaver.blog.BlogDao;
import java.text.SimpleDateFormat;
import weaver.systeminfo.menuconfig.MenuUtil;
import weaver.mobile.webservices.MobileServiceImpl;
import weaver.blog.BlogDiscessVo;
import weaver.general.GCONST;
import weaver.blog.AppDao;
import java.net.URLDecoder;
import weaver.task.TaskUtil;
import weaver.blog.bean.BlogZanBean;
import java.util.*;
import weaver.hrm.*;
import weaver.systeminfo.*;
import weaver.general.StaticObj;
import weaver.general.Util;
import weaver.hrm.settings.RemindSettings;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import weaver.blog.BlogShareManager;
import weaver.file.FileUpload;
import weaver.blog.WorkDayDao;
import net.sf.json.JSONObject;

public class _blogoperation__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
	
	response.setHeader("cache-control", "no-cache");
	response.setHeader("pragma", "no-cache");
	response.setHeader("expires", "Mon 1 Jan 1990 00:00:00 GMT");
	

	User user = HrmUserVarify.getUser (request , response) ;
	if(user == null)  return ;
	Log logger= LogFactory.getLog(this.getClass());
	String isIE = (String)session.getAttribute("browser_isie");

      out.write(_jsp_string1, 0, _jsp_string1.length);
      weaver.blog.BlogDao blogDao;
      blogDao = (weaver.blog.BlogDao) pageContext.getAttribute("blogDao");
      if (blogDao == null) {
        blogDao = new weaver.blog.BlogDao();
        pageContext.setAttribute("blogDao", blogDao);
      }
      out.write(_jsp_string2, 0, _jsp_string2.length);
      
    String userid=""+user.getUID();
    request.setCharacterEncoding("UTF-8"); 
    FileUpload fu = new FileUpload(request);
    BlogManager blogManager=new BlogManager(user);
    
	String operation=Util.null2String(fu.getParameter("operation"));
	String attentionid=Util.null2String(fu.getParameter("attentionid"));   //\u5173\u6ce8\u8005id
	String islower=Util.null2String(fu.getParameter("islower"));           //\u662f\u5426\u4e3a\u5f53\u524d\u7528\u6237\u4e0b\u5c5e
	String tempid=Util.null2String(request.getParameter("tempid"));  //\u62a5\u8868\u6a21\u677fid
	String searchUserName=Util.null2String(request.getParameter("searchUserName")); // \u641c\u7d22\u9ed8\u8ba4\u7684\u5fae\u535a
	BlogReportManager reportManager=new BlogReportManager();
	/*\u5173\u6ce8\u5904\u7406*/
	if(operation.equals("addAttention")){                 //\u6dfb\u52a0\u5173\u6ce8
	    blogManager.addAttention(userid,attentionid,islower);
	    blogDao.addRemind(attentionid,userid,"5","","0");  //\u5173\u6ce8\u6211\u7684+1\u63d0\u9192
	}else if(operation.equals("cancelAttention")){       //\u53d6\u6d88\u5173\u6ce8
		blogManager.cancelAttention(userid,attentionid,islower);
	}else if(operation.equals("requestAttention")){     //\u7533\u8bf7\u5173\u6ce8
		blogManager.requestAttention(userid,attentionid,islower);
	}else if(operation.equals("dealRequest")){
		String requestid=Util.null2String(fu.getParameter("requestid"));
		String sender=Util.null2String(fu.getParameter("sender"));
		String status=Util.null2String(fu.getParameter("status"));
		blogManager.dealRequest(userid,sender,requestid,status);
		if(status.equals("1")){        //\u540c\u610f
		   blogDao.addRemind(sender,userid,"2","","0");  //\u7533\u8bf7\u6210\u529f\u63d0\u9192
		}else if(status.equals("-1"))  //\u62d2\u7edd
		   blogDao.addRemind(sender,userid,"3","","0");	//\u7533\u8bf7\u5931\u8d25\u63d0\u9192
	}else if(operation.equals("delMsg")){
		String msgid=Util.null2String(fu.getParameter("msgid"));
		String remindType=Util.null2String(fu.getParameter("remindType"));
		String sql="";
		if(remindType.equals("8"))
		  sql="update blog_remind set status=-1 where id="+msgid;
		else
		  sql="delete from blog_remind where id="+msgid;	
		RecordSet recordSet=new RecordSet();
		recordSet.execute(sql);
	}else if(operation.equals("unsubmitRemind")){     //\u672a\u63d0\u4ea4\u63d0\u9192
		String remindid=Util.null2String(fu.getParameter("remindid"));
		String relatedid=Util.null2String(fu.getParameter("discussant"));
		String remindValue=Util.null2String(fu.getParameter("workdate"));
		String sql="select id from blog_remind where remindid="+remindid+" and relatedid="+relatedid+" and remindType=7 and remindValue='"+remindValue+"'";
		RecordSet recordSet=new RecordSet();
		recordSet.execute(sql);
		if(!recordSet.next())
		   blogDao.addRemind(remindid,relatedid,"7",remindValue,"0");	//\u7533\u8bf7\u5931\u8d25\u63d0\u9192
	}else if(operation.equals("signCheck")){         //\u7b7e\u5230 \u7b7e\u9000\u68c0\u67e5\u5fae\u535a\u662f\u5426\u63d0\u4ea4
		SimpleDateFormat dateFormat=new SimpleDateFormat("yyyy-MM-dd");
		String status=blogDao.getBlogStatus();       //\u5fae\u535a\u542f\u7528\u72b6\u6001
		Date enabledate=dateFormat.parse(blogDao.getSysSetting("enableDate")); //\u5fae\u535a\u542f\u7528\u65f6\u95f4
		Date currentdate=dateFormat.parse(dateFormat.format(new Date()));      //\u5f53\u524d\u65e5\u671f
		String isSignRemind=blogDao.getSysSetting("isSingRemind");    //\u662f\u5426\u542f\u7528\u7b7e\u5230\u63d0\u9192
		String checkday=Util.null2String(fu.getParameter("checkday"));//\u68c0\u67e5\u4f55\u65f6\u7684\u5de5\u4f5c\u5fae\u535a
		
		boolean todayHasBlog=true;         //\u4eca\u5929\u662f\u5426\u63d0\u4ea4\u5de5\u4f5c\u5fae\u535a\u4e86
		boolean prevWorkDayHasBlog=true;   //\u4e0a\u4e00\u4e2a\u5de5\u4f5c\u65e5\u662f\u5426\u63d0\u4ea4\u5de5\u4f5c\u5fae\u535a
		
		if(status.equals("1")&&isSignRemind.equals("1")&&currentdate.getTime()>=enabledate.getTime()){
			SimpleDateFormat frm=new SimpleDateFormat("yyyy-MM-dd");
		    if(checkday.equals("today"))       //\u7b7e\u9000\u65f6\u68c0\u67e5\u4eca\u5929
			   todayHasBlog=blogDao.chkDiscussExits(userid,frm.format(new Date()));
		    if(checkday.equals("prevWorkDay")){//\u7b7e\u5230\u65f6\u68c0\u67e5\u4e0a\u4e00\u4e2a\u5de5\u4f5c\u65e5
				WorkDayDao workDayDao=new WorkDayDao(user);
				for(int j=1;j<7;j++){
					Date tmpDate=new Date();
					tmpDate.setDate(tmpDate.getDate()-j);
					if(workDayDao.getIsWorkday(frm.format(tmpDate))){
						prevWorkDayHasBlog=blogDao.chkDiscussExits(""+user.getUID(),frm.format(tmpDate));
						break;
					}
				}
		    }
		}
		Map map=new HashMap();
		map.put("isSignRemind",isSignRemind);
		map.put("todayHasBlog",new Boolean(todayHasBlog));
		map.put("prevWorkDayHasBlog",new Boolean(prevWorkDayHasBlog));
		out.print(JSONObject.fromObject(map));
	}else if(operation.equals("markCommentRead")){ //\u6807\u8bb0\u8bc4\u8bba\u4e3a\u5df2\u8bfb
		String sql="delete from blog_remind where remindType=9 and remindid="+userid; 
		RecordSet recordSet=new RecordSet();
		recordSet.execute(sql);
	}else if(operation.equals("delUpdateRemind")){ //\u5220\u9664\u66f4\u65b0\u63d0\u9192
		String sql="delete from blog_remind where remindType=6 and remindid="+userid;
		RecordSet recordSet=new RecordSet();
		recordSet.execute(sql);
	}else if(operation.equals("managerScore")){     //\u4e0a\u7ea7\u8bc4\u5206
		String discussid=Util.null2String(fu.getParameter("discussid"));
		String score=Util.null2String(fu.getParameter("score"));
		
		String sql="update blog_discuss set score='"+score+"' where id="+discussid;
		RecordSet recordSet=new RecordSet();
		recordSet.execute(sql);
	}else if(operation.equals("getHomepageTotal")){    //\u83b7\u53d6\u4e3b\u9875\u8bb0\u5f55\u603b\u6570
		List attentionList=blogManager.getMyAttention(userid,"all");
		String attentionids=userid;                                 //\u6240\u6709\u6211\u5173\u6ce8\u7684\u4eba\u96c6\u5408,\u5305\u542b\u81ea\u8eab
		for(int i=0;i<attentionList.size();i++){
			attentionids=attentionids+","+attentionList.get(i);
		}
		int total=blogDao.getBlogDiscussCount(attentionids);
		out.println(total);
	}else if(operation.equals("readDiscuss")){    //\u5220\u9664\u66f4\u65b0\u63d0\u9192 \u548c \u6dfb\u52a0\u8bbf\u95ee\u8bb0\u5f55  \u9605\u8bfb\u8bb0\u5f55
		String discussid=Util.null2String(fu.getParameter("discussid"));
		String blogid=Util.null2String(fu.getParameter("blogid"));
		String sql="delete from blog_remind where remindType=6 and remindid="+userid+" and remindValue='"+discussid+"'";
		RecordSet recordSet=new RecordSet();
		recordSet.execute(sql);
		blogDao.addReadRecord(userid,blogid);  //\u6dfb\u52a0\u5df2\u8bfb\u8bb0\u5f55
	    blogDao.addVisitRecord(userid,blogid); //\u6dfb\u52a0\u8bbf\u95ee\u8bb0\u5f55
	}else if(operation.equals("getDiscussContent")){
		String discussid=Util.null2String(fu.getParameter("discussid"));
		BlogDiscessVo discessVo=blogDao.getDiscussVo(discussid);
		if(discessVo.getUserid().equals(userid)) //\u6743\u9650\u5224\u65ad
			out.print(discessVo.getContent());
	}else if(operation.equals("zanOpr")){//\u70b9\u8d5e\uff0c\u53d6\u6d88\u8d5e
		String discussid=Util.null2String(fu.getParameter("discussid"));
		String zanflag=Util.null2String(fu.getParameter("zanflag"));
		BlogZanBean blogZanBean = new BlogZanBean();
		if("zan0".equals(zanflag)){
			blogZanBean.addZan(discussid,userid);
		}else{
			blogZanBean.cancelZan(discussid,userid);
		}
		//String zanCount = blogZanBean.getZanCount(discussid);
		//out.println(zanCount);
	}else if(operation.equals("getZan")){
		String discussid=Util.null2String(fu.getParameter("discussid"));
		BlogZanBean blogZanBean = new BlogZanBean(discussid);
		blogZanBean.setCurUserid(userid);
		blogZanBean.setIsZan(blogZanBean.isZan(discussid,userid));
		JSONObject json=JSONObject.fromObject(blogZanBean);
		out.println(json);
	}else if(operation.equals("getIndex")){
		Calendar calendar = Calendar.getInstance();
		int currentMonth = calendar.get(Calendar.MONTH) + 1;
		int currentYear = calendar.get(Calendar.YEAR);
		reportManager.setUser(user);
		
		Map index=new HashMap();
		String blogid=Util.null2String(fu.getParameter("blogid"));
		//\u5de5\u4f5c\u6307\u6570
		Map workMap=new HashMap();
		Map resultMap = reportManager.getBlogReportByUser(blogid,currentYear, currentMonth);
		int totalWorkday = ((Integer) resultMap.get("totalWorkday")).intValue(); //\u5f53\u6708\u5de5\u4f5c\u65e5\u603b\u6570
		int totalUnsubmit = ((Integer) resultMap.get("totalUnsubmit")).intValue(); //\u5fae\u535a\u672a\u63d0\u4ea4\u603b\u6570
		double workIndex = ((Double) resultMap.get("workIndex")).doubleValue(); //\u5de5\u4f5c\u6307\u6570

		workMap.put("workIndex",""+resultMap.get("workIndex"));
		workMap.put("workIndexTitle",SystemEnv.getHtmlLabelName(15178,user.getLanguage())+totalUnsubmit+SystemEnv.getHtmlLabelName(1925,user.getLanguage())+SystemEnv.getHtmlLabelName(26932,user.getLanguage())+totalWorkday+SystemEnv.getHtmlLabelName(1925,user.getLanguage()));
		workMap.put("workIndexStar",reportManager.getReportIndexStar(workIndex));
		index.put("work",workMap);
		
		//\u5fc3\u60c5\u6307\u6570
		AppDao appDao = new AppDao();
		if(appDao.getAppVoByType("mood").isActive()){ 
			Map moodMap=new HashMap();
			Map moodResultMap = reportManager.getMoodReportByUser(blogid,currentYear, currentMonth);
			int happyDays = ((Integer) moodResultMap.get("happyDays")).intValue();
			int unHappyDays = ((Integer) moodResultMap.get("unHappyDays")).intValue();
			double moodIndex = ((Double) moodResultMap.get("moodIndex")).doubleValue(); //\u5fc3\u60c5\u6307\u6570
			
			moodMap.put("moodIndex",""+moodResultMap.get("moodIndex"));
			moodMap.put("moodIndexTitle",SystemEnv.getHtmlLabelName(26918,user.getLanguage())+unHappyDays+SystemEnv.getHtmlLabelName(1925,user.getLanguage())+SystemEnv.getHtmlLabelName(26917,user.getLanguage())+happyDays+SystemEnv.getHtmlLabelName(1925,user.getLanguage()));
			moodMap.put("moodIndexStar",reportManager.getReportIndexStar(moodIndex));
			index.put("mood",moodMap);
		}
		//\u8003\u52e4\u6307\u6570
		String isSignInOrSignOut=Util.null2String(blogDao.getIsSignInOrSignOut(user));
		if(isSignInOrSignOut.equals("1")){
		   Map scheduleMap=new HashMap();	
		   Map schedulrResultMap=reportManager.getScheduleReportByUser(blogid,currentYear,currentMonth); 
		   double scheduleIndex=((Double)schedulrResultMap.get("scheduleIndex")).doubleValue();    //\u8003\u52e4\u6307\u6570
		   int totalAbsent=((Integer)schedulrResultMap.get("totalAbsent")).intValue();          //\u65f7\u5de5\u603b\u5929\u6570
		   int totalLate=((Integer)schedulrResultMap.get("totalLate")).intValue();              //\u8fdf\u5230\u603b\u5929\u6570
		   
		   scheduleMap.put("scheduleIndex",""+schedulrResultMap.get("scheduleIndex"));
		   scheduleMap.put("scheduleIndexTitle",SystemEnv.getHtmlLabelName(20085,user.getLanguage())+totalAbsent+SystemEnv.getHtmlLabelName(18083,user.getLanguage())+SystemEnv.getHtmlLabelName(20081,user.getLanguage())+totalLate+SystemEnv.getHtmlLabelName(18083,user.getLanguage())+SystemEnv.getHtmlLabelName(18609,user.getLanguage())+totalWorkday+SystemEnv.getHtmlLabelName(20079,user.getLanguage()));
		   scheduleMap.put("scheduleIndexStar",reportManager.getReportIndexStar(scheduleIndex));
		   
		   index.put("schedule",scheduleMap);
		} 
		JSONObject json=JSONObject.fromObject(index);
		out.println(json);
	}else if(operation.equals("getMyAttentionCount")){ //\u83b7\u53d6\u6211\u5173\u6ce8\u7684\u4eba\u603b\u6570
		String groupid=Util.null2String(request.getParameter("groupid"));
		//int total=blogDao.getMyAttentionCount(userid,groupid,searchUserName);
		int total=blogDao.getMyAttentionCount(userid,"all");
		out.println(total);
	}else if(operation.equals("saveNotepad")){ //\u4fdd\u5b58\u8bb0\u4e8b\u672c\u5185\u5bb9
	    String content=Util.null2String(request.getParameter("content")); //\u8bb0\u4e8b\u672c\u5185\u5bb9
		String saveType=Util.null2String(fu.getParameter("saveType"));//\u4fdd\u5b58\u7c7b\u578b
		blogDao.saveNotes(userid,content,saveType); //\u4fdd\u5b58\u5185\u5bb9
	}
	
	/*\u81ea\u5b9a\u4e49\u62a5\u8868*/
	if(operation.equals("addReport")){          
	   tempid=reportManager.addReportTemp(userid);
       out.println(tempid);
	}else if(operation.equals("editReport")){      
	  String tempName=Util.fromScreen(Util.null2String(request.getParameter("tempName")),user.getLanguage());	
	  reportManager.editReportTemp(tempid,tempName);
	}else if(operation.equals("delReport")){ 
	  reportManager.delReportTemp(tempid); 	
	}else if(operation.equals("addCondition")){
	  String type=Util.null2String(request.getParameter("type"));	
	  String content=Util.null2String(request.getParameter("value"));	
	  reportManager.addTempCondition(tempid,type,content); 	
	}else if(operation.equals("delCondition")){          //\u81ea\u5b9a\u4e49\u62a5\u8868\u4eba\u9009\u62e9\u68c0\u67e5\u67e5\u770b\u6743\u9650
	  String conditionid=Util.null2String(request.getParameter("conditionid"));	
	  reportManager.delTempCondition(conditionid);
	}else if(operation.equals("isCanView")){          //\u81ea\u5b9a\u4e49\u62a5\u8868\u4eba\u9009\u62e9\u68c0\u67e5\u67e5\u770b\u6743\u9650
		BlogShareManager shareManager=new BlogShareManager();
	    boolean isCanView=shareManager.isCanView(userid,attentionid);
	    out.println(isCanView);
	}else if(operation.equals("appRightFilter")){      //\u68c0\u67e5\u5e94\u7528\u94fe\u63a5\u6743\u9650
	    String linktype=Util.null2String(request.getParameter("linktype"));
	    String linkid=Util.null2String(request.getParameter("linkid"));
	    linkid=blogDao.appRightFilter(userid,linktype,linkid);
	    out.println("{linkid:'"+linkid+"'}");
	}else if(operation.equals("getCountdata")){      //\u83b7\u53d6\u7edf\u8ba1\u6570\u5b57
		
		int blogCount= blogDao.getMyBlogCount(userid);               //\u5fae\u535a\u603b\u6570
		int myAttentionCount= blogDao.getMyAttentionCount(userid,"all");   //\u6211\u5173\u6ce8\u7684\u4eba\u603b\u6570
		int attentionMeCount= blogDao.getAttentionMe(userid).size();        //\u5173\u6ce8\u6211\u7684\u4eba\u603b\u6570
		
		Map result=new HashMap();
		result.put("blogCount",blogCount);
		result.put("myAttentionCount",myAttentionCount);
		result.put("attentionMeCount",attentionMeCount);
		
		JSONObject object=JSONObject.fromObject(result);
		out.print(object.toString());
		
	}
	
	if(operation.equals("getSysLog")){
		String blogid=Util.null2String(request.getParameter("blogid"));
		String workdate=Util.null2String(request.getParameter("workdate"));
		String logstr="";
		TaskUtil taskUtil=new TaskUtil();
		int taskindex=1;
	    List logList=taskUtil.getTaskLog(blogid,workdate);
	    String[] logtypes={"crm","wf","cowork","task"};
	 
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((workdate));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((SystemEnv.getHtmlLabelName(21313,user.getLanguage())));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((workdate));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((SystemEnv.getHtmlLabelName(18015,user.getLanguage())));
      out.write(_jsp_string6, 0, _jsp_string6.length);
      out.print((workdate));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((SystemEnv.getHtmlLabelName(30047,user.getLanguage())));
      out.write(_jsp_string7, 0, _jsp_string7.length);
      for(int m=0;m<logtypes.length;m++){
			  String logtype=logtypes[m];
			  taskindex=1;
			  logstr="";
			
      out.write(_jsp_string8, 0, _jsp_string8.length);
      out.print((logtype));
      out.write('_');
      out.print((workdate));
      out.write(_jsp_string9, 0, _jsp_string9.length);
      out.print((logtype.equals("crm")?"":"none"));
      out.write(_jsp_string10, 0, _jsp_string10.length);
      
					
					for(int k=0;k<logList.size();k++){ 
				    	   Map map=(Map)logList.get(k);
				    	   String taskid=(String)map.get("taskid");
				           String tasktype=(String)map.get("tasktype");
				           if(logtype.equals("wf")&&!tasktype.equals("2")) continue;
				           if(logtype.equals("crm")&&!tasktype.equals("9")) continue;
				           if(logtype.equals("cowork")&&!tasktype.equals("5")) continue;
				           if(logtype.equals("task")&&!tasktype.equals("1")) continue;
				        	   
				           String taskcontent=(String)map.get("taskcontent");
				           String taskname=(String)map.get("taskname");
				           logstr+="<TR height=18>"
				        	   		+"<TD width=8><IMG name=esymbol src='/blog/images/syslogs/li_wev8.png'></TD>";
				           logstr+="<td>"
				        	   		+"<div>"+(taskindex++)+"\u3001<a href=\"javascript:openTask("+taskid+","+tasktype+")\" class=\"a1\">"+taskname+"</a></div>"
				               	   +"</td>"
				               	   +"</TR>";
				           
				           logstr+="<tr><td></td><td>"
				        	   		+"<div class=\"log_c\">"+taskcontent+"</div>"
				        	   	   +"</td></tr>";
				    }
					if(logstr.equals(""))
				    	  logstr="<tr><td colspan='2'><div style=\"color:#bcbcbc;\">"+SystemEnv.getHtmlLabelName(82393,user.getLanguage())+"</div></td></tr>";
				    out.println(logstr);
					
      out.write(_jsp_string11, 0, _jsp_string11.length);
      }
      out.write(_jsp_string12, 0, _jsp_string12.length);
         
	    
	}
	

    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 1886798272571451039L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("blog/blogOperation.jsp"), -5365313776772866499L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("page/maint/common/initNoCache.jsp"), 3270256153856711871L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string12;
  private final static char []_jsp_string6;
  private final static char []_jsp_string4;
  private final static char []_jsp_string10;
  private final static char []_jsp_string7;
  private final static char []_jsp_string5;
  private final static char []_jsp_string0;
  private final static char []_jsp_string8;
  private final static char []_jsp_string3;
  private final static char []_jsp_string9;
  private final static char []_jsp_string1;
  private final static char []_jsp_string2;
  private final static char []_jsp_string11;
  static {
    _jsp_string12 = "\r\n		</DIV>\r\n	</DIV>\r\n	 ".toCharArray();
    _jsp_string6 = "</TD>\r\n						<TD class=\"tab2item tab2unselected\" onclick=\"showLogContent(this)\" _target=\"#cowork_".toCharArray();
    _jsp_string4 = "\">".toCharArray();
    _jsp_string10 = "\">\r\n					".toCharArray();
    _jsp_string7 = "</TD>\r\n						<TD width=\"*\" style=\"border-bottom:1px solid #c4cfde;\"></TD>\r\n					</TR>\r\n				</TABLE>\r\n			</DIV>\r\n			".toCharArray();
    _jsp_string5 = "</TD>\r\n						<TD class=\"tab2item tab2unselected\" onclick=\"showLogContent(this)\" _target=\"#wf_".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string8 = "\r\n			<TABLE width=\"100%\" class=\"log_content\" id=\"".toCharArray();
    _jsp_string3 = "\r\n	 <DIV style=\"POSITION: relative;\" class=\"sys_logs\">\r\n		<DIV style=\"WIDTH: 100%\" class=content>\r\n			<DIV class=tab2>\r\n				<TABLE border=0 cellSpacing=0 cellPadding=0 height=22>\r\n					<TR>\r\n						<td class=\"tab2unselected\" style=\"width:10px;\"></td>\r\n						<TD class=\"tab2item tab2selected\" onclick=\"showLogContent(this)\" _target=\"#crm_".toCharArray();
    _jsp_string9 = "\" style=\"display: ".toCharArray();
    _jsp_string1 = "\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string2 = "\r\n".toCharArray();
    _jsp_string11 = "\r\n			</TABLE>\r\n			".toCharArray();
  }
}
