/*
 * JSP generated by Resin-3.1.8 (built Mon, 17 Nov 2008 12:15:21 PST)
 */

package _jsp._workflow._exceldesign;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import weaver.general.Util;
import java.util.*;
import weaver.systeminfo.SystemEnv;
import java.util.LinkedHashMap;
import net.sf.json.JSONObject;

public class _excelgetfieldoperat__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      weaver.conn.RecordSet RecordSet;
      RecordSet = (weaver.conn.RecordSet) pageContext.getAttribute("RecordSet");
      if (RecordSet == null) {
        RecordSet = new weaver.conn.RecordSet();
        pageContext.setAttribute("RecordSet", RecordSet);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      weaver.workflow.form.FormManager FormManager;
      synchronized (pageContext.getSession()) {
        FormManager = (weaver.workflow.form.FormManager) pageContext.getSession().getAttribute("FormManager");
        if (FormManager == null) {
          FormManager = new weaver.workflow.form.FormManager();
          pageContext.getSession().setAttribute("FormManager", FormManager);
        }
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      weaver.systeminfo.label.LabelComInfo LabelComInfo;
      LabelComInfo = (weaver.systeminfo.label.LabelComInfo) pageContext.getAttribute("LabelComInfo");
      if (LabelComInfo == null) {
        LabelComInfo = new weaver.systeminfo.label.LabelComInfo();
        pageContext.setAttribute("LabelComInfo", LabelComInfo);
      }
      out.write(_jsp_string2, 0, _jsp_string2.length);
      weaver.workflow.form.FormFieldMainManager FormFieldMainManager;
      FormFieldMainManager = (weaver.workflow.form.FormFieldMainManager) pageContext.getAttribute("FormFieldMainManager");
      if (FormFieldMainManager == null) {
        FormFieldMainManager = new weaver.workflow.form.FormFieldMainManager();
        pageContext.setAttribute("FormFieldMainManager", FormFieldMainManager);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      FormFieldMainManager.resetParameter();
      out.write(_jsp_string1, 0, _jsp_string1.length);
      weaver.workflow.form.FormFieldlabelMainManager FormFieldlabelMainManager;
      FormFieldlabelMainManager = (weaver.workflow.form.FormFieldlabelMainManager) pageContext.getAttribute("FormFieldlabelMainManager");
      if (FormFieldlabelMainManager == null) {
        FormFieldlabelMainManager = new weaver.workflow.form.FormFieldlabelMainManager();
        pageContext.setAttribute("FormFieldlabelMainManager", FormFieldlabelMainManager);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      FormFieldlabelMainManager.resetParameter();
      out.write(_jsp_string1, 0, _jsp_string1.length);
      
	int formid = Util.getIntValue(request.getParameter("formid"),0);
	int fieldid = Util.getIntValue(request.getParameter("fieldid"),0);
	int isbill = Util.getIntValue(request.getParameter("isbill"),0);
	//System.out.println("isbill"+isbill);
	String method = Util.null2String(request.getParameter("method"));
	boolean issqlserver = (RecordSet.getDBType()).equals("sqlserver") ;
	if(method.equals("getfield"))
	{
		if(fieldid>0)
		{
			if(isbill == 0)
			{
				ArrayList langids=new ArrayList();
				FormFieldlabelMainManager.setFormid(formid);
				FormFieldlabelMainManager.selectLanguage();
				while(FormFieldlabelMainManager.next()){
					int curid=FormFieldlabelMainManager.getLanguageid();
					langids.add(""+curid);
				}
				LinkedHashMap map = new LinkedHashMap();
				for (int tmpcount1=0;tmpcount1<langids.size();tmpcount1++)
				{
					String curidlanguage=(String)langids.get(tmpcount1);
					FormFieldlabelMainManager.resetParameter();
					FormFieldlabelMainManager.setFormid(formid);
					FormFieldlabelMainManager.setFieldid(fieldid);
					FormFieldlabelMainManager.setLanguageid(Util.getIntValue(curidlanguage,0));
					FormFieldlabelMainManager.selectSingleFormField();
					if(curidlanguage.equals("7"))
						map.put("_cn",FormFieldlabelMainManager.getFieldlabel());
					else if(curidlanguage.equals("8"))
						map.put("_en",FormFieldlabelMainManager.getFieldlabel());
					else if(curidlanguage.equals("9"))
						map.put("_tw",FormFieldlabelMainManager.getFieldlabel());
				}
				JSONObject reval = JSONObject.fromObject(map);
				//System.out.println(reval);
				response.getWriter().write(reval.toString());
			}else if(isbill == 1)
			{
				if(formid!=0)
					RecordSet.executeSql("select id,fieldname,fieldlabel,viewtype from workflow_billfield where billid="+formid+" and id="+fieldid+"");
				if(RecordSet.next()){//\u53d6\u5f97\u8868\u5355\u7684\u6240\u6709\u5b57\u6bb5\u53ca\u5b57\u6bb5\u663e\u793a\u540d

					int tempFieldLableId = RecordSet.getInt("fieldlabel");
					//System.out.println("select id,fieldname,fieldlabel,viewtype from workflow_billfield where billid="+formid+" and id="+fieldid+"");
					//System.out.println(fieldid);
					String _cn = SystemEnv.getHtmlLabelName(tempFieldLableId,7);
					String _en = SystemEnv.getHtmlLabelName(tempFieldLableId,8);
					String _tw = SystemEnv.getHtmlLabelName(tempFieldLableId,9);
					
					LinkedHashMap map = new LinkedHashMap();
					map.put("_cn",_cn);
					map.put("_en",_en);
					map.put("_tw",_tw);
					JSONObject reval = JSONObject.fromObject(map);
					//System.out.println(reval);
					response.getWriter().write(reval.toString());
				}else if(fieldid < 0)
				{
					
				}
			}
		}
	}else if(method.equals("savefield"))
	{
		if(fieldid > 0)
		{
			String fieldnameCN = Util.null2String(request.getParameter("_cn"));
			String fieldnameEn = Util.null2String(request.getParameter("_en"));
			String fieldnameTW = Util.null2String(request.getParameter("_tw"));
			fieldnameCN = Util.StringReplace(fieldnameCN, "\"", "");//TD10108 \u8868\u5355\u5b57\u6bb5\u663e\u793a\u540d\u4e0d\u53ef\u4ee5\u542b\u6709\u534a\u89d2\u53cc\u5f15\u53f7\u201c"\u201d

			fieldnameCN = Util.StringReplace(fieldnameCN, "'", "");//TD31514 \u8868\u5355\u5b57\u6bb5\u663e\u793a\u540d\u4e0d\u53ef\u4ee5\u542b\u6709\u534a\u89d2\u5355\u5f15\u53f7\u201c'\u201d

			fieldnameEn = Util.StringReplace(fieldnameEn, "\"", "");//TD10108 \u8868\u5355\u5b57\u6bb5\u663e\u793a\u540d\u4e0d\u53ef\u4ee5\u542b\u6709\u534a\u89d2\u53cc\u5f15\u53f7\u201c"\u201d

			fieldnameEn = Util.StringReplace(fieldnameEn, "'", "");//TD31514 \u8868\u5355\u5b57\u6bb5\u663e\u793a\u540d\u4e0d\u53ef\u4ee5\u542b\u6709\u534a\u89d2\u5355\u5f15\u53f7\u201c'\u201d

			fieldnameTW = Util.StringReplace(fieldnameTW, "\"", "");//TD10108 \u8868\u5355\u5b57\u6bb5\u663e\u793a\u540d\u4e0d\u53ef\u4ee5\u542b\u6709\u534a\u89d2\u53cc\u5f15\u53f7\u201c"\u201d

			fieldnameTW = Util.StringReplace(fieldnameTW, "'", "");//TD31514 \u8868\u5355\u5b57\u6bb5\u663e\u793a\u540d\u4e0d\u53ef\u4ee5\u542b\u6709\u534a\u89d2\u5355\u5f15\u53f7\u201c'\u201d

			if(isbill == 0)
			{
				FormFieldlabelMainManager.setFormid(formid);
				FormFieldlabelMainManager.selectLanguage();
				ArrayList langids=new ArrayList();
				while(FormFieldlabelMainManager.next()){
					int curid=FormFieldlabelMainManager.getLanguageid();
					langids.add(""+curid);
				}
				int defaultlang =Util.getIntValue(Util.null2String(request.getParameter("isdefault")));
				for (int tmpcount1=0;tmpcount1<langids.size();tmpcount1++)
				{
					int languageid = Util.getIntValue((String)langids.get(tmpcount1),0);
					String isdef = "0";
					if( languageid < 1)
						break;
					if(languageid == defaultlang)
						isdef = "1";
					FormFieldlabelMainManager.resetParameter();
					FormFieldlabelMainManager.setFormid(formid);
					FormFieldlabelMainManager.setFieldid(fieldid);
					FormFieldlabelMainManager.setLanguageid(languageid);
					String label = "";
					if(languageid == 7)
					{
						label = fieldnameCN;
					}
					else if(languageid == 8)
						label = fieldnameEn;
					else if(languageid == 9)
						label = fieldnameTW;
					FormFieldlabelMainManager.setFieldlabel(label);
					FormFieldlabelMainManager.updataFormfieldlabel();
				}
			}else if(isbill == 1)
			{
				int lableid = 0;
				if(issqlserver) RecordSet.executeSql("select indexid from HtmlLabelInfo where labelname='"+fieldnameCN+"' collate Chinese_PRC_CS_AI and languageid=7");
				else RecordSet.executeSql("select indexid from HtmlLabelInfo where labelname='"+fieldnameCN+"' and languageid=7");
				if(RecordSet.next()) lableid = RecordSet.getInt("indexid");//\u5982\u679c\u5b57\u6bb5\u540d\u79f0\u5728\u6807\u7b7e\u5e93\u4e2d\u5b58\u5728\uff0c\u53d6\u5f97\u6807\u7b7eid,\u4ee5\u4e2d\u6587\u4e3a\u51c6\u3002

				else{//\u4e0d\u5b58\u5728\u5219\u751f\u6210\u65b0\u7684\u6807\u7b7eid
					lableid = -1;
			    	try{
			        //statement = new ConnStatement();
			        //statement.setStatementSql("select min(id) as id from HtmlLabelIndex");	
			        //statement.executeQuery();
			        RecordSet.executeSql("select min(id) as id from HtmlLabelIndex");
			        if(RecordSet.next()){
			        	lableid = RecordSet.getInt("id")-1;
			        	if(lableid > -2) lableid = -2;//\u4ece-2\u5f00\u59cb\u751f\u6210\u65b0\u7684labelid
			        }
			    	}catch (Exception e){
			    		lableid = -1;
			    	}
				}
				//System.out.println("labelid"+lableid);
				if(lableid!=-1){//\u66f4\u65b0\u6807\u7b7e\u5e93

					RecordSet.executeSql("delete from HtmlLabelIndex where id="+lableid);
					RecordSet.executeSql("delete from HtmlLabelInfo where indexid="+lableid);
					RecordSet.executeSql("INSERT INTO HtmlLabelIndex values("+lableid+",'"+fieldnameCN+"')");
					RecordSet.executeSql("INSERT INTO HtmlLabelInfo values("+lableid+",'"+fieldnameCN+"',7)");//\u4e2d\u6587
					RecordSet.executeSql("INSERT INTO HtmlLabelInfo values("+lableid+",'"+fieldnameEn+"',8)");//\u82f1\u6587
					RecordSet.executeSql("INSERT INTO HtmlLabelInfo values("+lableid+",'"+fieldnameTW+"',9)");//\u7e41\u4f53
				}
				
				RecordSet.executeSql("update workflow_billfield set fieldlabel="+lableid+" where id="+fieldid);
				
				LabelComInfo.addLabeInfoCache(""+lableid);//\u66f4\u65b0\u7f13\u5b58
				
			}
			response.getWriter().write("true");
		}
	}

    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 1886798272571451039L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("workflow/exceldesign/excelGetFieldOperat.jsp"), 3533127714655721990L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string0;
  private final static char []_jsp_string2;
  private final static char []_jsp_string1;
  static {
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string2 = "	\r\n".toCharArray();
    _jsp_string1 = "\r\n".toCharArray();
  }
}
