/*
 * JSP generated by Resin-3.1.8 (built Mon, 17 Nov 2008 12:15:21 PST)
 */

package _jsp._formmode._setup;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import net.sf.json.JSONArray;
import java.net.URLDecoder;
import net.sf.json.JSONObject;
import weaver.formmode.dao.BaseDao;
import weaver.conn.RecordSetTrans;
import java.net.URLEncoder;
import weaver.formmode.service.CommonConstant;
import weaver.conn.RecordSet;
import weaver.systeminfo.label.LabelComInfo;
import weaver.systeminfo.SystemEnv;
import weaver.formmode.service.AppInfoService;
import weaver.docs.category.DocTreeDocFieldConstant;
import weaver.formmode.setup.ModeTreeFieldComInfo;
import weaver.formmode.service.LogService;
import weaver.formmode.Module;
import weaver.formmode.log.LogType;
import java.util.*;
import weaver.general.Util;
import weaver.hrm.HrmUserVarify;
import weaver.hrm.User;
import weaver.formmode.ThreadLocalUser;
import weaver.systeminfo.systemright.CheckSubCompanyRight;
import java.io.IOException;

public class _appsettingsaction__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;

  
  private Map getCheckRightSubCompanyParam(String userRightStr,User user,String fmdetachable,int subCompanyId,String subCompanyIdName,
  	HttpServletRequest request,HttpServletResponse response,HttpSession session){
  	int operatelevel=0;
  	Map map = new HashMap();
  	if(subCompanyIdName.equals("")){
  		subCompanyIdName = "subCompanyId";
  	}
  	
  	if(fmdetachable.equals("1")){  
  		if(subCompanyId==-1){
  		    if(request.getParameter(subCompanyIdName)==null){
  		        subCompanyId=Util.getIntValue(String.valueOf(session.getAttribute("managefield_subCompanyId")),-1);
  		    }else{
  		        subCompanyId=Util.getIntValue(request.getParameter(subCompanyIdName),-1);
  		    }
  		    if(subCompanyId == -1){
  		        subCompanyId = user.getUserSubCompany1();
  		    }
  		}
  	    CheckSubCompanyRight CheckSubCompanyRight = new CheckSubCompanyRight();
  	    operatelevel= CheckSubCompanyRight.ChkComRightByUserRightCompanyId(user.getUID(),userRightStr,subCompanyId);
  	    if(operatelevel>=0){
  		    session.setAttribute("managefield_subCompanyId",String.valueOf(subCompanyId));
  	    }
  	}else{
  	    if(HrmUserVarify.checkUserRight(userRightStr, user)){
  	        operatelevel=2;
  	    }
  	}
  	String currentSubCompanyId = ""+session.getAttribute("defaultSubCompanyId");
  	map.put("currentSubCompanyId",currentSubCompanyId);
  	map.put("subCompanyId",subCompanyId);
  	map.put("operatelevel",operatelevel);
  	return map;
  }

  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
int isIncludeToptitle = 0;
User user = HrmUserVarify.getUser (request , response) ;
if(user==null) {
    response.sendRedirect("/login/Login.jsp");
    return;
}
ThreadLocalUser.setUser(user);

      out.write(_jsp_string1, 0, _jsp_string1.length);
      weaver.hrm.moduledetach.ManageDetachComInfo ManageDetachComInfo;
      ManageDetachComInfo = (weaver.hrm.moduledetach.ManageDetachComInfo) pageContext.getAttribute("ManageDetachComInfo");
      if (ManageDetachComInfo == null) {
        ManageDetachComInfo = new weaver.hrm.moduledetach.ManageDetachComInfo();
        pageContext.setAttribute("ManageDetachComInfo", ManageDetachComInfo);
      }
      out.write(_jsp_string2, 0, _jsp_string2.length);
      weaver.systeminfo.systemright.CheckSubCompanyRight CheckSubCompanyRight;
      CheckSubCompanyRight = (weaver.systeminfo.systemright.CheckSubCompanyRight) pageContext.getAttribute("CheckSubCompanyRight");
      if (CheckSubCompanyRight == null) {
        CheckSubCompanyRight = new weaver.systeminfo.systemright.CheckSubCompanyRight();
        pageContext.setAttribute("CheckSubCompanyRight", CheckSubCompanyRight);
      }
      out.write(_jsp_string2, 0, _jsp_string2.length);
      weaver.hrm.company.SubCompanyComInfo SubCompanyComInfo;
      SubCompanyComInfo = (weaver.hrm.company.SubCompanyComInfo) pageContext.getAttribute("SubCompanyComInfo");
      if (SubCompanyComInfo == null) {
        SubCompanyComInfo = new weaver.hrm.company.SubCompanyComInfo();
        pageContext.setAttribute("SubCompanyComInfo", SubCompanyComInfo);
      }
      out.write(_jsp_string2, 0, _jsp_string2.length);
      
boolean isUseFmManageDetach=ManageDetachComInfo.isUseFmManageDetach();
String fmdetachable="0";
if(isUseFmManageDetach){
   fmdetachable="1";
   session.setAttribute("detachable","1");
   session.setAttribute("fmdetachable",fmdetachable);
   session.setAttribute("fmdftsubcomid",ManageDetachComInfo.getFmdftsubcomid());
}else{
   fmdetachable="0";
   session.setAttribute("detachable","0");
   session.setAttribute("fmdetachable",fmdetachable);
   session.setAttribute("fmdftsubcomid","0");
}

      out.write(_jsp_string3, 0, _jsp_string3.length);
      weaver.conn.RecordSetTrans RecordSetTrans;
      RecordSetTrans = (weaver.conn.RecordSetTrans) pageContext.getAttribute("RecordSetTrans");
      if (RecordSetTrans == null) {
        RecordSetTrans = new weaver.conn.RecordSetTrans();
        pageContext.setAttribute("RecordSetTrans", RecordSetTrans);
      }
      out.write(_jsp_string2, 0, _jsp_string2.length);
      
if (!HrmUserVarify.checkUserRight("FORMMODEAPP:ALL", user)) {
	response.sendRedirect("/notice/noright.jsp");
	return;
}
response.reset();
out.clear();
AppInfoService appInfoService = new AppInfoService();
String action = Util.null2String(request.getParameter("action"));
RecordSetTrans rsTrans = new RecordSetTrans();
RecordSet rs = new RecordSet();
LogService logService = new LogService();
int subCompanyId = Util.getIntValue(request.getParameter("subCompanyId"),-1);
rs.executeSql("select fmdetachable from SystemSet");
if(rs.next()){
	fmdetachable = rs.getString(1);
}
if(action.equalsIgnoreCase("editAppinfo")){
	int appId = Util.getIntValue(request.getParameter("appId"));
	String treeFieldName = Util.fromScreen(request.getParameter("treeFieldName"),user.getLanguage());
	String showOrder = Util.null2String(request.getParameter("showOrder"));
	String treeFieldDesc = Util.null2String(request.getParameter("treeFieldDesc"));
	
	String superFieldId = Util.null2String(request.getParameter("superFieldId"));
	String treelevel = Util.null2String(request.getParameter("treelevel"));
	
	Map<String,	Object> dataMap = new HashMap<String,	Object>();
	dataMap.put("id", appId);
	dataMap.put("treeFieldName", treeFieldName);
	dataMap.put("showOrder", showOrder);
	dataMap.put("treeFieldDesc", treeFieldDesc);
	
	dataMap.put("superFieldId", superFieldId);
	dataMap.put("treelevel", treelevel);
	dataMap.put("subCompanyId", subCompanyId);
	
	appInfoService.saveOrUpdateAppInfo(dataMap);
	
	logService.log(appId, Module.APP, LogType.EDIT);
	
	ModeTreeFieldComInfo modeTreeFieldComInfo = new ModeTreeFieldComInfo();
	modeTreeFieldComInfo.removeDocTreeDocFieldCache();
	
	String editFromRightMenu = Util.null2String(request.getParameter("editFromRightMenu"));
	if(editFromRightMenu.equals("1")){
		out.print("<script type=\"text/javascript\">top.closeTopDialog("+appId+");</script>");
	}else{
		out.print("<script type=\"text/javascript\">parent.parent.refreshApp("+appId+");</script>");
	}
}else if(action.equalsIgnoreCase("getAllAppInfoForTree")){
	if(fmdetachable.equals("1")){
		Map map = new HashMap();
		map.put("subCompanyId",subCompanyId);
		map.put("user",user);
		JSONArray appinfoArr = appInfoService.getAllAppInfoForTreeParam(map);
		response.setCharacterEncoding("UTF-8");
		out.print(appinfoArr.toString());
	}else{
		JSONArray appinfoArr = appInfoService.getAllAppInfoForTree();
		response.setCharacterEncoding("UTF-8");
		out.print(appinfoArr.toString());
	}
}else if(action.equalsIgnoreCase("getAllAppInfoForTreeSearch")){
	String searchText = Util.null2String(request.getParameter("searchtext"));
	Map map = new HashMap();
	map.put("searchText", searchText);
	if(fmdetachable.equals("1")){
		map.put("subCompanyId",subCompanyId);
		map.put("user",user);
		JSONArray appinfoArr = appInfoService.getAllAppInfoForTreeParam(map);
		response.setCharacterEncoding("UTF-8");
		out.print(appinfoArr.toString());
	}else{
		JSONArray appinfoArr = appInfoService.getAllAppInfoForTreeParam(map);
		response.setCharacterEncoding("UTF-8");
		out.print(appinfoArr.toString());
	}
}else if(action.equalsIgnoreCase("addAppinfo")){
	
	if(subCompanyId==-1||subCompanyId==0){//\u5206\u6743\u5206\u90e8\u7684\u53d6\u5f97\u3002\u5982\u679c\u9875\u9762\u6ca1\u6709\uff0c\u5219\u9996\u5148\u4ece\u5206\u6743\u8bbe\u7f6e\u7684\u9ed8\u8ba4\u673a\u6784\u53d6\u5f97\uff0c\u5982\u679c\u9ed8\u8ba4\u673a\u6784\u6ca1\u6709\u8bbe\u7f6e\u5219\u53d6\u6240\u6709\u5206\u90e8\u4e2did\u6700\u5c0f\u7684\u90a3\u4e2a\u5206\u90e8\u3002
  		RecordSetTrans.executeSql("select fmdftsubcomid,dftsubcomid from SystemSet");
  		if(fmdetachable.equals("1")){
			RecordSetTrans.executeSql("select fmdftsubcomid,dftsubcomid from SystemSet");
	  		if(RecordSetTrans.next()){
	  			subCompanyId = Util.getIntValue(RecordSetTrans.getString("fmdftsubcomid"),-1);
	  			if(subCompanyId==-1||subCompanyId==0){
		  			subCompanyId = Util.getIntValue(RecordSetTrans.getString("dftsubcomid"),-1);
	  			}
	  		}	  	
	  		if(subCompanyId==-1||subCompanyId==0){
	  			RecordSetTrans.executeSql("select min(id) as id from HrmSubCompany");
	  			if(RecordSetTrans.next()) subCompanyId = RecordSetTrans.getInt("id");
	  		}
		}
  	}
	
	int appId = Util.getIntValue(request.getParameter("appId"));
	String treeFieldName = Util.fromScreen(request.getParameter("treeFieldName"),user.getLanguage());
	String showOrder = Util.null2String(request.getParameter("showOrder"));
	String treeFieldDesc = Util.null2String(request.getParameter("treeFieldDesc"));
	
	String superFieldId = Util.null2String(request.getParameter("superFieldId"));
	
	String allSuperFieldId;
	String treelevel;
	
	if(superFieldId.equals("") || superFieldId.equals(DocTreeDocFieldConstant.TREE_DOC_FIELD_ROOT_ID)){
		superFieldId = DocTreeDocFieldConstant.TREE_DOC_FIELD_ROOT_ID;
		allSuperFieldId = superFieldId;
		treelevel = "1";
	}else{
		Map<String, Object> superAppInfo = appInfoService.getAppInfoById(Util.getIntValue(superFieldId));
		//allSuperFieldId = Util.null2String(superAppInfo.get("superfieldid")) + "," + superFieldId;
		allSuperFieldId = appInfoService.getAllSuperFieldIdBySuperId(Util.getIntValue(superFieldId),superFieldId);
		treelevel = String.valueOf(Util.getIntValue(Util.null2String(superAppInfo.get("treelevel"))) + 1);
	}
	
	Map<String,	Object> dataMap = new HashMap<String,	Object>();
	dataMap.put("id", appId);
	dataMap.put("treeFieldName", treeFieldName);
	dataMap.put("showOrder", showOrder);
	dataMap.put("treeFieldDesc", treeFieldDesc);
	
	dataMap.put("superFieldId", superFieldId);
	dataMap.put("treelevel", treelevel);
	dataMap.put("allSuperFieldId", allSuperFieldId);
	dataMap.put("subCompanyId", subCompanyId);
	
	int createdAppid = appInfoService.saveOrUpdateAppInfo(dataMap);
	
	logService.log(createdAppid, Module.APP, LogType.ADD);
	
	ModeTreeFieldComInfo modeTreeFieldComInfo = new ModeTreeFieldComInfo();
	modeTreeFieldComInfo.removeDocTreeDocFieldCache();
	
	out.print("<script type=\"text/javascript\">top.closeTopDialog("+createdAppid+");</script>");
}else if(action.equalsIgnoreCase("deleteApp")){
	try{
		int appId = Util.getIntValue(request.getParameter("appId"));
		appInfoService.deleteAppInfo(appId);
		
		logService.log(appId, Module.APP, LogType.DELETE);
		
		ModeTreeFieldComInfo modeTreeFieldComInfo = new ModeTreeFieldComInfo();
		modeTreeFieldComInfo.removeDocTreeDocFieldCache();
		out.print("1");
	}catch(Exception ex){
		ex.printStackTrace();
		out.print(ex.getMessage());
	}
}else if("wasteApp".equalsIgnoreCase(action)){
	try{
		int appId = Util.getIntValue(request.getParameter("appId"));
		appInfoService.wasteAppInfo(appId);
		logService.log(appId, Module.APP, LogType.DELETE);
		ModeTreeFieldComInfo modeTreeFieldComInfo = new ModeTreeFieldComInfo();
		modeTreeFieldComInfo.removeDocTreeDocFieldCache();
		out.print("1");
	}catch(Exception ex){
		ex.printStackTrace();
		out.print(ex.getMessage());
	}
}
out.flush();
out.close();

    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 1886798272571451039L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("formmode/setup/appSettingsAction.jsp"), 5569849622716797024L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("formmode/pub_init.jsp"), -4246916824298514572L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("formmode/pub_function.jsp"), 5446055981984630656L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string3;
  private final static char []_jsp_string1;
  private final static char []_jsp_string2;
  private final static char []_jsp_string0;
  static {
    _jsp_string3 = "\r\n\r\n\r\n".toCharArray();
    _jsp_string1 = "\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string2 = "\r\n".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
  }
}
