/*
 * JSP generated by Resin-3.1.8 (built Mon, 17 Nov 2008 12:15:21 PST)
 */

package _jsp._workflow._request;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import weaver.general.browserData.BrowserManager;
import weaver.hrm.User;
import weaver.hrm.HrmUserVarify;
import java.util.*;
import weaver.systeminfo.SystemEnv;
import weaver.formmode.tree.CustomTreeUtil;
import weaver.formmode.tree.CustomTreeData;
import weaver.workflow.field.FileElement;
import weaver.workflow.datainput.DynamicDataInput;
import weaver.interfaces.workflow.browser.Browser;
import weaver.interfaces.workflow.browser.BrowserBean;
import weaver.general.Util;
import weaver.conn.*;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import weaver.system.code.CodeBuild;
import weaver.system.code.CoderBean;
import weaver.workflow.request.WFFreeFlowManager;
import weaver.file.FileUpload;
import weaver.hrm.attendance.domain.*;
import weaver.workflow.request.RequestConstants;
import weaver.general.LocateUtil;

public class _workflowmanagerequestbodyaction_0script__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      weaver.conn.RecordSet RecordSet;
      RecordSet = (weaver.conn.RecordSet) pageContext.getAttribute("RecordSet");
      if (RecordSet == null) {
        RecordSet = new weaver.conn.RecordSet();
        pageContext.setAttribute("RecordSet", RecordSet);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      weaver.conn.RecordSet recordSet;
      recordSet = (weaver.conn.RecordSet) pageContext.getAttribute("recordSet");
      if (recordSet == null) {
        recordSet = new weaver.conn.RecordSet();
        pageContext.setAttribute("recordSet", recordSet);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      weaver.hrm.resource.ResourceComInfo ResourceComInfo;
      ResourceComInfo = (weaver.hrm.resource.ResourceComInfo) pageContext.getAttribute("ResourceComInfo");
      if (ResourceComInfo == null) {
        ResourceComInfo = new weaver.hrm.resource.ResourceComInfo();
        pageContext.setAttribute("ResourceComInfo", ResourceComInfo);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      weaver.conn.RecordSet RecordSet_nf2;
      RecordSet_nf2 = (weaver.conn.RecordSet) pageContext.getAttribute("RecordSet_nf2");
      if (RecordSet_nf2 == null) {
        RecordSet_nf2 = new weaver.conn.RecordSet();
        pageContext.setAttribute("RecordSet_nf2", RecordSet_nf2);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      weaver.docs.category.SecCategoryComInfo SecCategoryComInfo1;
      SecCategoryComInfo1 = (weaver.docs.category.SecCategoryComInfo) pageContext.getAttribute("SecCategoryComInfo1");
      if (SecCategoryComInfo1 == null) {
        SecCategoryComInfo1 = new weaver.docs.category.SecCategoryComInfo();
        pageContext.setAttribute("SecCategoryComInfo1", SecCategoryComInfo1);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      weaver.hrm.company.DepartmentComInfo DepartmentComInfo1;
      DepartmentComInfo1 = (weaver.hrm.company.DepartmentComInfo) pageContext.getAttribute("DepartmentComInfo1");
      if (DepartmentComInfo1 == null) {
        DepartmentComInfo1 = new weaver.hrm.company.DepartmentComInfo();
        pageContext.setAttribute("DepartmentComInfo1", DepartmentComInfo1);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      weaver.hrm.company.SubCompanyComInfo SubCompanyComInfo1;
      SubCompanyComInfo1 = (weaver.hrm.company.SubCompanyComInfo) pageContext.getAttribute("SubCompanyComInfo1");
      if (SubCompanyComInfo1 == null) {
        SubCompanyComInfo1 = new weaver.hrm.company.SubCompanyComInfo();
        pageContext.setAttribute("SubCompanyComInfo1", SubCompanyComInfo1);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      weaver.workflow.request.RequestManager RequestManager;
      RequestManager = (weaver.workflow.request.RequestManager) pageContext.getAttribute("RequestManager");
      if (RequestManager == null) {
        RequestManager = new weaver.workflow.request.RequestManager();
        pageContext.setAttribute("RequestManager", RequestManager);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      weaver.conn.RecordSet rs;
      rs = (weaver.conn.RecordSet) pageContext.getAttribute("rs");
      if (rs == null) {
        rs = new weaver.conn.RecordSet();
        pageContext.setAttribute("rs", rs);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      weaver.workflow.workflow.WfLinkageInfo WfLinkageInfo;
      WfLinkageInfo = (weaver.workflow.workflow.WfLinkageInfo) pageContext.getAttribute("WfLinkageInfo");
      if (WfLinkageInfo == null) {
        WfLinkageInfo = new weaver.workflow.workflow.WfLinkageInfo();
        pageContext.setAttribute("WfLinkageInfo", WfLinkageInfo);
      }
      out.write(_jsp_string2, 0, _jsp_string2.length);
      
	String f_weaver_belongto_userid=Util.null2String(request.getParameter("f_weaver_belongto_userid"));
	String f_weaver_belongto_usertype=Util.null2String(request.getParameter("f_weaver_belongto_usertype"));//\u9700\u8981\u589e\u52a0\u7684\u4ee3\u7801

	User user = HrmUserVarify.getUser(request, response, f_weaver_belongto_userid, f_weaver_belongto_usertype) ;//\u9700\u8981\u589e\u52a0\u7684\u4ee3\u7801
	String userid = ""+user.getUID();
	String selectInitJsStr = Util.null2String(request.getParameter("selectInitJsStr"));
	String newfromdate = Util.null2String(request.getParameter("newfromdate"));
	String newenddate = Util.null2String(request.getParameter("newenddate"));
	int requestid = Util.getIntValue(request.getParameter("requestid"), 0);
	String nodetype = Util.null2String(request.getParameter("nodetype"));
	int isremark = Util.getIntValue(request.getParameter("isremark"), 0); //\u5f53\u524d\u64cd\u4f5c\u72b6\u6001
	int workflowid = Util.getIntValue(request .getParameter("workflowid"));

	int nodeid = Util.getIntValue(request.getParameter("nodeid"), 0);
	String bodychangattrstr = Util.null2String(request.getParameter("bodychangattrstr"));;

	String requestname = Util.null2String((String) session
			.getAttribute(userid + "_" + requestid + "requestname"));//update by fanggsh 20060509 TD4294

	String isbill = Util.null2String(request.getParameter("isbill"));
	int formid = Util.getIntValue(request.getParameter("formid"), 0);
	String isrequest = Util.null2String(request.getParameter("isrequest"));

      out.write(_jsp_string3, 0, _jsp_string3.length);
      
	int creater = Util.getIntValue(request.getParameter("creater"), 0);
	int creatertype = Util.getIntValue(request.getParameter("creatertype"), 0);
	String currentdate = Util.null2String(request.getParameter("currentdate"));
	String currenttime = Util.null2String(request.getParameter("currenttime"));
	String fieldCode =  Util.null2String(request.getParameter("fieldCode"));
	
	//\u5224\u65ad\u662f\u5426\u662fE8\u65b0\u7248\u4fdd\u5b58
    boolean isE8Save = Util.null2String(request.getParameter("isE8Save")).equals("true");
	
	String fieldIdSelect = Util.null2String(request.getParameter("fieldIdSelect"));
	String departmentFieldId = Util.null2String(request.getParameter("departmentFieldId"));
	String subCompanyFieldId = Util.null2String(request.getParameter("subCompanyFieldId"));
	String supSubCompanyFieldId = Util.null2String(request.getParameter("supSubCompanyFieldId"));
	String yearFieldId = Util.null2String(request.getParameter("yearFieldId"));
	String yearFieldHtmlType = Util.null2String(request.getParameter("yearFieldHtmlType"));
	String monthFieldId = Util.null2String(request.getParameter("monthFieldId"));
	String dateFieldId = Util.null2String(request.getParameter("dateFieldId"));
	String docCategory =  Util.null2String(request.getParameter("docCategory"));
	int uploadType = Util.getIntValue(request.getParameter("uploadType"), 0);
	String selectedfieldid = Util.null2String(request.getParameter("selectedfieldid"));
	String keywordismand =  Util.null2String(request.getParameter("keywordismand"));
	String keywordisedit = Util.null2String(request.getParameter("keywordisedit"));
	int titleFieldId = Util.getIntValue(request.getParameter("titleFieldId"), 0);
	int keywordFieldId = Util.getIntValue(request.getParameter("keywordFieldId"), 0);
	ArrayList managefckfields_body = (ArrayList)Util.stringToList(Util.null2String(request.getParameter("managefckfields_body")));
	//\u83b7\u5f97\u89e6\u53d1\u5b57\u6bb5\u540d mackjoe 2005-07-22
  	DynamicDataInput ddi = new DynamicDataInput(workflowid + "");
  	String trrigerfield = ddi.GetEntryTriggerFieldName();
	boolean editbodyactionflag =  Util.null2String(request.getParameter("editbodyactionflag")).equals("true");
	//\u5b57\u6bb5\u961f\u5217
	ArrayList fieldids = (ArrayList)Util.stringToList(Util.null2String(request.getParameter("fieldids"))); 


      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((bodychangattrstr));
      out.write(_jsp_string1, 0, _jsp_string1.length);
      String isFormSignature = null;
			RecordSet
					.executeSql("select isFormSignature from workflow_flownode where workflowId="
							+ workflowid + " and nodeId=" + nodeid);
			if (RecordSet.next()) {
				isFormSignature = Util.null2String(RecordSet
						.getString("isFormSignature"));
			}
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((isremark));
      out.write(_jsp_string6, 0, _jsp_string6.length);
      out.print((isremark));
      out.write(_jsp_string7, 0, _jsp_string7.length);
      out.print((!editbodyactionflag));
      out.write(_jsp_string8, 0, _jsp_string8.length);
      out.print((requestid));
      out.write(_jsp_string9, 0, _jsp_string9.length);
      if ("1".equals(isFormSignature)) {
      out.write(_jsp_string10, 0, _jsp_string10.length);
      out.print((SystemEnv.getHtmlLabelName(17614, user
      										.getLanguage())));
      out.write(_jsp_string11, 0, _jsp_string11.length);
      out.print((SystemEnv.getHtmlLabelName(21423, user
      										.getLanguage())));
      out.write(_jsp_string12, 0, _jsp_string12.length);
      out.print((SystemEnv.getHtmlLabelName(21442, user
      										.getLanguage())));
      out.write(_jsp_string13, 0, _jsp_string13.length);
      } else {
      out.write(_jsp_string14, 0, _jsp_string14.length);
      }
      out.write(_jsp_string15, 0, _jsp_string15.length);
      out.print((userid));
      out.write(_jsp_string16, 0, _jsp_string16.length);
      out.print((f_weaver_belongto_usertype));
      out.write(_jsp_string17, 0, _jsp_string17.length);
      out.print((requestid));
      out.write(_jsp_string18, 0, _jsp_string18.length);
      out.print((userid));
      out.write(_jsp_string16, 0, _jsp_string16.length);
      out.print((f_weaver_belongto_usertype));
      out.write(_jsp_string17, 0, _jsp_string17.length);
      out.print((requestid));
      out.write(_jsp_string19, 0, _jsp_string19.length);
      out.print((userid));
      out.write(_jsp_string16, 0, _jsp_string16.length);
      out.print((f_weaver_belongto_usertype));
      out.write(_jsp_string17, 0, _jsp_string17.length);
      out.print((requestid));
      out.write(_jsp_string20, 0, _jsp_string20.length);
      out.print((newenddate));
      out.write(_jsp_string21, 0, _jsp_string21.length);
      out.print((newfromdate));
      out.write(_jsp_string22, 0, _jsp_string22.length);
      out.print((newenddate));
      out.write(_jsp_string23, 0, _jsp_string23.length);
      out.print((newfromdate));
      out.write(_jsp_string24, 0, _jsp_string24.length);
      out.print((newfromdate));
      out.write(_jsp_string25, 0, _jsp_string25.length);
      out.print((newfromdate));
      out.write(_jsp_string26, 0, _jsp_string26.length);
      out.print((newenddate));
      out.write(_jsp_string27, 0, _jsp_string27.length);
      out.print((newenddate));
      out.write(_jsp_string28, 0, _jsp_string28.length);
      out.print((newenddate));
      out.write(_jsp_string29, 0, _jsp_string29.length);
      out.print((SystemEnv.getHtmlLabelName(15273, user.getLanguage())));
      out.write(_jsp_string30, 0, _jsp_string30.length);
      out.print((workflowid));
      out.write(_jsp_string31, 0, _jsp_string31.length);
      out.print((formid));
      out.write(_jsp_string32, 0, _jsp_string32.length);
      out.print((isbill));
      out.write(_jsp_string33, 0, _jsp_string33.length);
      out.print((nodeid));
      out.write(_jsp_string34, 0, _jsp_string34.length);
      if (!trrigerfield.trim().equals("")) {
				ArrayList Linfieldname = ddi.GetInFieldName();
				ArrayList Lcondetionfieldname = ddi.GetConditionFieldName();
				for (int i = 0; i < Linfieldname.size(); i++) {
					String temp = (String) Linfieldname.get(i);
      out.write(_jsp_string35, 0, _jsp_string35.length);
      out.print((temp.substring(temp.indexOf("|") + 1)));
      out.write(_jsp_string36, 0, _jsp_string36.length);
      out.print((temp));
      out.write(_jsp_string37, 0, _jsp_string37.length);
      out.print((temp.substring(temp.indexOf("|") + 1)));
      out.write(_jsp_string38, 0, _jsp_string38.length);
      }
				for (int i = 0; i < Lcondetionfieldname.size(); i++) {
					String temp = (String) Lcondetionfieldname.get(i);
      out.write(_jsp_string35, 0, _jsp_string35.length);
      out.print((temp.substring(temp.indexOf("|") + 1)));
      out.write(_jsp_string36, 0, _jsp_string36.length);
      out.print((temp));
      out.write(_jsp_string37, 0, _jsp_string37.length);
      out.print((temp.substring(temp.indexOf("|") + 1)));
      out.write(_jsp_string38, 0, _jsp_string38.length);
      }
			}
      out.write(_jsp_string39, 0, _jsp_string39.length);
      if (titleFieldId > 0 && keywordFieldId > 0) {
      out.write(_jsp_string40, 0, _jsp_string40.length);
      out.print((titleFieldId));
      out.write(_jsp_string41, 0, _jsp_string41.length);
      out.print((keywordFieldId));
      out.write(_jsp_string42, 0, _jsp_string42.length);
      } else if (titleFieldId == -3 && keywordFieldId > 0) {
      out.write(_jsp_string43, 0, _jsp_string43.length);
      out.print((keywordFieldId));
      out.write(_jsp_string42, 0, _jsp_string42.length);
      }
      out.write(_jsp_string44, 0, _jsp_string44.length);
      if (keywordFieldId > 0) {
      out.write(_jsp_string45, 0, _jsp_string45.length);
      out.print((keywordFieldId));
      out.write(_jsp_string46, 0, _jsp_string46.length);
      out.print((keywordismand));
      out.write(_jsp_string47, 0, _jsp_string47.length);
      out.print((keywordisedit));
      out.write(_jsp_string48, 0, _jsp_string48.length);
      out.print((keywordFieldId));
      out.write(_jsp_string49, 0, _jsp_string49.length);
      out.print((keywordFieldId));
      out.write(_jsp_string50, 0, _jsp_string50.length);
      out.print((keywordFieldId));
      out.write(_jsp_string51, 0, _jsp_string51.length);
      }
      out.write(_jsp_string52, 0, _jsp_string52.length);
      
	if (keywordFieldId > 0) {
	char setSeparator = Util.getSeparator();
	char setSeparator_temp = Util.getSeparator_temp();

      out.write(_jsp_string45, 0, _jsp_string45.length);
      out.print((keywordFieldId));
      out.write(_jsp_string53, 0, _jsp_string53.length);
      out.print((setSeparator));
      out.write(_jsp_string54, 0, _jsp_string54.length);
      out.print((setSeparator_temp));
      out.write(_jsp_string55, 0, _jsp_string55.length);
      out.print((SystemEnv.getHtmlLabelNames("21517",user.getLanguage())));
      out.write(_jsp_string56, 0, _jsp_string56.length);
      out.print((keywordFieldId));
      out.write(_jsp_string49, 0, _jsp_string49.length);
      out.print((keywordFieldId));
      out.write(_jsp_string57, 0, _jsp_string57.length);
      
    }

      out.write(_jsp_string58, 0, _jsp_string58.length);
      for (int i = 0; i < managefckfields_body.size(); i++) {
      out.write(_jsp_string59, 0, _jsp_string59.length);
      out.print((managefckfields_body.get(i)));
      out.write(_jsp_string60, 0, _jsp_string60.length);
      }
      out.write(_jsp_string61, 0, _jsp_string61.length);
      if (fieldids.size() < 1) {
      out.write(_jsp_string62, 0, _jsp_string62.length);
      out.print((SystemEnv.getHtmlLabelName(22577, user
      								.getLanguage())));
      out.write(_jsp_string63, 0, _jsp_string63.length);
      }
      out.write(_jsp_string64, 0, _jsp_string64.length);
      out.print((isbill));
      out.write(_jsp_string65, 0, _jsp_string65.length);
      out.print((selectedfieldid));
      out.write(_jsp_string66, 0, _jsp_string66.length);
      out.print((uploadType));
      out.write(_jsp_string67, 0, _jsp_string67.length);
      out.print((isbill));
      out.write(_jsp_string65, 0, _jsp_string65.length);
      out.print((selectedfieldid));
      out.write(_jsp_string66, 0, _jsp_string66.length);
      out.print((uploadType));
      out.write(_jsp_string68, 0, _jsp_string68.length);
      out.print((selectInitJsStr));
      out.write(_jsp_string2, 0, _jsp_string2.length);
      ArrayList currentdateList = Util.TokenizerString(currentdate, "-");
			int departmentId = Util.getIntValue(ResourceComInfo
					.getDepartmentID("" + creater), -1);
			int subCompanyId = Util.getIntValue(DepartmentComInfo1
					.getSubcompanyid1("" + departmentId), -1);
			int supSubCompanyId = Util.getIntValue(SubCompanyComInfo1
					.getSupsubcomid("" + subCompanyId), -1);
			if (supSubCompanyId <= 0) {
				supSubCompanyId = subCompanyId;//\u82e5\u4e0a\u7ea7\u5206\u90e8\u4e3a\u7a7a\uff0c\u5219\u8ba4\u4e3a\u4e0a\u7ea7\u5206\u90e8\u4e3a\u5206\u90e8
			}
      out.write(_jsp_string69, 0, _jsp_string69.length);
      out.print((workflowid));
      out.write(_jsp_string70, 0, _jsp_string70.length);
      out.print((formid));
      out.write(_jsp_string71, 0, _jsp_string71.length);
      out.print((isbill));
      out.write(_jsp_string72, 0, _jsp_string72.length);
      out.print((fieldCode));
      out.write(_jsp_string73, 0, _jsp_string73.length);
      out.print((fieldCode));
      out.write(_jsp_string74, 0, _jsp_string74.length);
      out.print((fieldCode));
      out.write(_jsp_string75, 0, _jsp_string75.length);
      out.print((departmentId));
      out.write(_jsp_string76, 0, _jsp_string76.length);
      out.print((yearFieldHtmlType));
      out.write(_jsp_string77, 0, _jsp_string77.length);
      
		if(yearFieldId.indexOf("~~wfcode~~")>-1){
			String [] yearlist = yearFieldId.split("~~wfcode~~");
			if(yearlist.length>0){
				for(int yidx=0;yidx < yearlist.length;yidx++){
	
      out.write(_jsp_string78, 0, _jsp_string78.length);
      out.print((yearlist[yidx]));
      out.write(_jsp_string79, 0, _jsp_string79.length);
      out.print((yearlist[yidx]));
      out.write(_jsp_string80, 0, _jsp_string80.length);
      out.print((yearlist[yidx]));
      out.write(_jsp_string81, 0, _jsp_string81.length);
      if (currentdateList.size() >= 1) {
      out.write(_jsp_string82, 0, _jsp_string82.length);
      out.print(((String) currentdateList.get(0)));
      out.write(_jsp_string83, 0, _jsp_string83.length);
      out.print(((String) currentdateList.get(0)));
      out.write(_jsp_string84, 0, _jsp_string84.length);
      }
      out.write(_jsp_string85, 0, _jsp_string85.length);
      		
				}
			}
		}else{
	
      out.write(_jsp_string86, 0, _jsp_string86.length);
      out.print((yearFieldId));
      out.write(_jsp_string87, 0, _jsp_string87.length);
      out.print((yearFieldId));
      out.write(_jsp_string88, 0, _jsp_string88.length);
      out.print((yearFieldId));
      out.write(_jsp_string89, 0, _jsp_string89.length);
      }
      out.write(_jsp_string90, 0, _jsp_string90.length);
      
		if(monthFieldId.indexOf("~~wfcode~~")>-1){
			String [] monlist = monthFieldId.split("~~wfcode~~");
			if(monlist.length>0){
				for(int midx=0;midx < monlist.length;midx++){
		
      out.write(_jsp_string91, 0, _jsp_string91.length);
      out.print((monlist[midx]));
      out.write(_jsp_string92, 0, _jsp_string92.length);
      out.print((monlist[midx]));
      out.write(_jsp_string93, 0, _jsp_string93.length);
      if (currentdateList.size() >= 2) {
      out.write(_jsp_string94, 0, _jsp_string94.length);
      out.print(((String) currentdateList.get(1) ));
      out.write(_jsp_string95, 0, _jsp_string95.length);
      out.print(((String) currentdateList.get(1)));
      out.write(_jsp_string96, 0, _jsp_string96.length);
      }
      out.write(_jsp_string97, 0, _jsp_string97.length);
      		
				}
			}
		}else{
		
      out.write(_jsp_string86, 0, _jsp_string86.length);
      out.print((monthFieldId));
      out.write(_jsp_string98, 0, _jsp_string98.length);
      out.print((monthFieldId));
      out.write(_jsp_string99, 0, _jsp_string99.length);
      }
      out.write(_jsp_string90, 0, _jsp_string90.length);
      
		if(dateFieldId.indexOf("~~wfcode~~")>-1){
			String [] dlist = dateFieldId.split("~~wfcode~~");
			if(dlist.length>0){
				for(int didx=0;didx < dlist.length;didx++){
		
      out.write(_jsp_string91, 0, _jsp_string91.length);
      out.print((dlist[didx]));
      out.write(_jsp_string100, 0, _jsp_string100.length);
      out.print((dlist[didx]));
      out.write(_jsp_string101, 0, _jsp_string101.length);
      if (currentdateList.size() >= 3) {
      out.write(_jsp_string102, 0, _jsp_string102.length);
      out.print(((String) currentdateList.get(2)));
      out.write(_jsp_string103, 0, _jsp_string103.length);
      out.print(((String) currentdateList.get(2)));
      out.write(_jsp_string104, 0, _jsp_string104.length);
      }
      out.write(_jsp_string97, 0, _jsp_string97.length);
      		
				}
			}
		}else{
		
      out.write(_jsp_string86, 0, _jsp_string86.length);
      out.print((dateFieldId));
      out.write(_jsp_string105, 0, _jsp_string105.length);
      out.print((dateFieldId));
      out.write(_jsp_string106, 0, _jsp_string106.length);
      }
      out.write(_jsp_string2, 0, _jsp_string2.length);
      if (currentdateList.size() >= 1) {
      out.write(_jsp_string107, 0, _jsp_string107.length);
      out.print(((String) currentdateList.get(0)));
      out.write(_jsp_string108, 0, _jsp_string108.length);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      if (currentdateList.size() >= 2) {
      out.write(_jsp_string109, 0, _jsp_string109.length);
      out.print(((String) currentdateList.get(1)));
      out.write(_jsp_string108, 0, _jsp_string108.length);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      if (currentdateList.size() >= 3) {
      out.write(_jsp_string110, 0, _jsp_string110.length);
      out.print(((String) currentdateList.get(2)));
      out.write(_jsp_string108, 0, _jsp_string108.length);
      }
      out.write(_jsp_string111, 0, _jsp_string111.length);
      
	if(fieldIdSelect.indexOf("~~wfcode~~")>-1){
		String [] fieldlist = fieldIdSelect.split("~~wfcode~~");
		if(fieldlist.length>0){
			for(int fld=0;fld < fieldlist.length;fld++){
	
      out.write(_jsp_string112, 0, _jsp_string112.length);
      out.print((fieldlist[fld]));
      out.write(_jsp_string113, 0, _jsp_string113.length);
      out.print((fieldlist[fld]));
      out.write(_jsp_string114, 0, _jsp_string114.length);
      out.print((fieldlist[fld]));
      out.write(_jsp_string115, 0, _jsp_string115.length);
      if(fieldlist[fld].equals(""))
							fieldlist[fld] = "-1";
						
      out.write(_jsp_string116, 0, _jsp_string116.length);
      out.print((fieldlist[fld]));
      out.write(_jsp_string114, 0, _jsp_string114.length);
      out.print((fieldlist[fld]));
      out.write(_jsp_string117, 0, _jsp_string117.length);
      		
			}
		}
	}else{
	
      out.write(_jsp_string118, 0, _jsp_string118.length);
      out.print((fieldIdSelect));
      out.write(_jsp_string119, 0, _jsp_string119.length);
      if(fieldIdSelect.equals(""))
				fieldIdSelect = "-1";
			
      out.write(_jsp_string120, 0, _jsp_string120.length);
      out.print((fieldIdSelect));
      out.write(_jsp_string121, 0, _jsp_string121.length);
      out.print((fieldIdSelect));
      out.write(_jsp_string122, 0, _jsp_string122.length);
      }
      out.write(_jsp_string123, 0, _jsp_string123.length);
      
	if(supSubCompanyFieldId.indexOf("~~wfcode~~")>-1){
		String [] supsublist = supSubCompanyFieldId.split("~~wfcode~~");
		if(supsublist.length>0){
			for(int supsubld=0;supsubld < supsublist.length;supsubld++){
	
      out.write(_jsp_string112, 0, _jsp_string112.length);
      out.print((supsublist[supsubld]));
      out.write(_jsp_string124, 0, _jsp_string124.length);
      out.print((supsublist[supsubld]));
      out.write(_jsp_string125, 0, _jsp_string125.length);
      out.print((supsublist[supsubld]));
      out.write(_jsp_string126, 0, _jsp_string126.length);
      		
			}
		}
	}else{
	
      out.write(_jsp_string118, 0, _jsp_string118.length);
      out.print((supSubCompanyFieldId));
      out.write(_jsp_string127, 0, _jsp_string127.length);
      out.print((supSubCompanyFieldId));
      out.write(_jsp_string128, 0, _jsp_string128.length);
      }
      out.write(_jsp_string129, 0, _jsp_string129.length);
      
	if(subCompanyFieldId.indexOf("~~wfcode~~")>-1){
		String [] subcomlist = subCompanyFieldId.split("~~wfcode~~");
		if(subcomlist.length>0){
			for(int subcomld=0;subcomld < subcomlist.length;subcomld++){
	
      out.write(_jsp_string130, 0, _jsp_string130.length);
      out.print((subcomlist[subcomld]));
      out.write(_jsp_string131, 0, _jsp_string131.length);
      out.print((subcomlist[subcomld]));
      out.write(_jsp_string132, 0, _jsp_string132.length);
      out.print((subcomlist[subcomld]));
      out.write(_jsp_string133, 0, _jsp_string133.length);
      		
			}
		}
	}else{
	
      out.write(_jsp_string118, 0, _jsp_string118.length);
      out.print((subCompanyFieldId));
      out.write(_jsp_string134, 0, _jsp_string134.length);
      out.print((subCompanyFieldId));
      out.write(_jsp_string135, 0, _jsp_string135.length);
      }
      out.write(_jsp_string136, 0, _jsp_string136.length);
      
	if(departmentFieldId.indexOf("~~wfcode~~")>-1){
		String [] deptlist = departmentFieldId.split("~~wfcode~~");
		if(deptlist.length>0){
			for(int deptld=0;deptld < deptlist.length;deptld++){
	
      out.write(_jsp_string130, 0, _jsp_string130.length);
      out.print((deptlist[deptld]));
      out.write(_jsp_string137, 0, _jsp_string137.length);
      out.print((deptlist[deptld]));
      out.write(_jsp_string138, 0, _jsp_string138.length);
      out.print((deptlist[deptld]));
      out.write(_jsp_string139, 0, _jsp_string139.length);
      		
			}
		}
	}else{
	
      out.write(_jsp_string118, 0, _jsp_string118.length);
      out.print((departmentFieldId));
      out.write(_jsp_string140, 0, _jsp_string140.length);
      out.print((departmentFieldId));
      out.write(_jsp_string141, 0, _jsp_string141.length);
      }
      out.write(_jsp_string142, 0, _jsp_string142.length);
      out.print((fieldCode));
      out.write(_jsp_string73, 0, _jsp_string73.length);
      out.print((fieldCode));
      out.write(_jsp_string143, 0, _jsp_string143.length);
      out.print((fieldCode));
      out.write(_jsp_string144, 0, _jsp_string144.length);
      out.print((fieldCode));
      out.write(_jsp_string145, 0, _jsp_string145.length);
      out.print((requestid));
      out.write(_jsp_string146, 0, _jsp_string146.length);
      out.print((fieldCode));
      out.write(_jsp_string147, 0, _jsp_string147.length);
      out.print((fieldCode));
      out.write(_jsp_string73, 0, _jsp_string73.length);
      out.print((fieldCode));
      out.write(_jsp_string148, 0, _jsp_string148.length);
      out.print((requestid));
      out.write(_jsp_string149, 0, _jsp_string149.length);
      out.print((fieldCode));
      out.write(_jsp_string150, 0, _jsp_string150.length);
      out.print((fieldCode));
      out.write(_jsp_string151, 0, _jsp_string151.length);
      out.print((fieldCode));
      out.write(_jsp_string73, 0, _jsp_string73.length);
      out.print((fieldCode));
      out.write(_jsp_string152, 0, _jsp_string152.length);
      out.print((requestid));
      out.write(_jsp_string153, 0, _jsp_string153.length);
      out.print((requestid));
      out.write(_jsp_string154, 0, _jsp_string154.length);
      out.print((SystemEnv.getHtmlLabelName(16579,user.getLanguage())));
      out.write(_jsp_string155, 0, _jsp_string155.length);
      out.print((SystemEnv.getHtmlLabelName(16579,user.getLanguage())));
      out.write(_jsp_string156, 0, _jsp_string156.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 1886798272571451039L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    manager.addTaglibFunctions(_jsp_functionMap, "brow", "/browserTag");
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("workflow/request/WorkflowManageRequestBodyAction_script.jsp"), 1633171961891182924L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string145;
  private final static char []_jsp_string19;
  private final static char []_jsp_string117;
  private final static char []_jsp_string16;
  private final static char []_jsp_string37;
  private final static char []_jsp_string87;
  private final static char []_jsp_string6;
  private final static char []_jsp_string115;
  private final static char []_jsp_string95;
  private final static char []_jsp_string14;
  private final static char []_jsp_string121;
  private final static char []_jsp_string33;
  private final static char []_jsp_string147;
  private final static char []_jsp_string80;
  private final static char []_jsp_string53;
  private final static char []_jsp_string143;
  private final static char []_jsp_string84;
  private final static char []_jsp_string76;
  private final static char []_jsp_string133;
  private final static char []_jsp_string35;
  private final static char []_jsp_string17;
  private final static char []_jsp_string25;
  private final static char []_jsp_string154;
  private final static char []_jsp_string130;
  private final static char []_jsp_string74;
  private final static char []_jsp_string45;
  private final static char []_jsp_string138;
  private final static char []_jsp_string151;
  private final static char []_jsp_string140;
  private final static char []_jsp_string98;
  private final static char []_jsp_string78;
  private final static char []_jsp_string49;
  private final static char []_jsp_string31;
  private final static char []_jsp_string137;
  private final static char []_jsp_string123;
  private final static char []_jsp_string116;
  private final static char []_jsp_string21;
  private final static char []_jsp_string134;
  private final static char []_jsp_string118;
  private final static char []_jsp_string89;
  private final static char []_jsp_string51;
  private final static char []_jsp_string153;
  private final static char []_jsp_string100;
  private final static char []_jsp_string64;
  private final static char []_jsp_string81;
  private final static char []_jsp_string156;
  private final static char []_jsp_string5;
  private final static char []_jsp_string20;
  private final static char []_jsp_string88;
  private final static char []_jsp_string39;
  private final static char []_jsp_string48;
  private final static char []_jsp_string69;
  private final static char []_jsp_string101;
  private final static char []_jsp_string8;
  private final static char []_jsp_string99;
  private final static char []_jsp_string3;
  private final static char []_jsp_string11;
  private final static char []_jsp_string18;
  private final static char []_jsp_string57;
  private final static char []_jsp_string22;
  private final static char []_jsp_string46;
  private final static char []_jsp_string97;
  private final static char []_jsp_string72;
  private final static char []_jsp_string129;
  private final static char []_jsp_string32;
  private final static char []_jsp_string36;
  private final static char []_jsp_string135;
  private final static char []_jsp_string85;
  private final static char []_jsp_string40;
  private final static char []_jsp_string12;
  private final static char []_jsp_string108;
  private final static char []_jsp_string139;
  private final static char []_jsp_string124;
  private final static char []_jsp_string122;
  private final static char []_jsp_string68;
  private final static char []_jsp_string94;
  private final static char []_jsp_string54;
  private final static char []_jsp_string66;
  private final static char []_jsp_string4;
  private final static char []_jsp_string126;
  private final static char []_jsp_string24;
  private final static char []_jsp_string109;
  private final static char []_jsp_string102;
  private final static char []_jsp_string63;
  private final static char []_jsp_string83;
  private final static char []_jsp_string44;
  private final static char []_jsp_string26;
  private final static char []_jsp_string152;
  private final static char []_jsp_string30;
  private final static char []_jsp_string141;
  private final static char []_jsp_string65;
  private final static char []_jsp_string142;
  private final static char []_jsp_string70;
  private final static char []_jsp_string29;
  private final static char []_jsp_string106;
  private final static char []_jsp_string90;
  private final static char []_jsp_string34;
  private final static char []_jsp_string61;
  private final static char []_jsp_string114;
  private final static char []_jsp_string113;
  private final static char []_jsp_string79;
  private final static char []_jsp_string148;
  private final static char []_jsp_string15;
  private final static char []_jsp_string104;
  private final static char []_jsp_string144;
  private final static char []_jsp_string112;
  private final static char []_jsp_string82;
  private final static char []_jsp_string86;
  private final static char []_jsp_string96;
  private final static char []_jsp_string59;
  private final static char []_jsp_string52;
  private final static char []_jsp_string92;
  private final static char []_jsp_string42;
  private final static char []_jsp_string110;
  private final static char []_jsp_string27;
  private final static char []_jsp_string103;
  private final static char []_jsp_string56;
  private final static char []_jsp_string125;
  private final static char []_jsp_string93;
  private final static char []_jsp_string136;
  private final static char []_jsp_string91;
  private final static char []_jsp_string55;
  private final static char []_jsp_string23;
  private final static char []_jsp_string58;
  private final static char []_jsp_string43;
  private final static char []_jsp_string13;
  private final static char []_jsp_string77;
  private final static char []_jsp_string9;
  private final static char []_jsp_string105;
  private final static char []_jsp_string10;
  private final static char []_jsp_string62;
  private final static char []_jsp_string38;
  private final static char []_jsp_string1;
  private final static char []_jsp_string67;
  private final static char []_jsp_string150;
  private final static char []_jsp_string107;
  private final static char []_jsp_string132;
  private final static char []_jsp_string47;
  private final static char []_jsp_string0;
  private final static char []_jsp_string60;
  private final static char []_jsp_string149;
  private final static char []_jsp_string28;
  private final static char []_jsp_string50;
  private final static char []_jsp_string155;
  private final static char []_jsp_string111;
  private final static char []_jsp_string75;
  private final static char []_jsp_string146;
  private final static char []_jsp_string128;
  private final static char []_jsp_string73;
  private final static char []_jsp_string127;
  private final static char []_jsp_string119;
  private final static char []_jsp_string131;
  private final static char []_jsp_string7;
  private final static char []_jsp_string41;
  private final static char []_jsp_string120;
  private final static char []_jsp_string2;
  private final static char []_jsp_string71;
  static {
    _jsp_string145 = "\").value == initfieldvalue) {\r\n			return;\r\n		} else {\r\n        	$GetEle(\"workflowKeywordIframe\").src=\"/workflow/request/WorkflowCodeIframe.jsp?operation=ChangeCode&requestId=".toCharArray();
    _jsp_string19 = "&isAppendTypeField=1\");\r\n	}\r\n}\r\n\r\nfunction openAccessory(fileId){ \r\n	jQuery($GetEle(\"flowbody\")).attr(\"onbeforeunload\", \"\");\r\n	openFullWindowHaveBar(\"/weaver/weaver.file.FileDownload?fileid=\"+fileId+\"&f_weaver_belongto_userid=".toCharArray();
    _jsp_string117 = "\").value;\r\n						if(fval == \"\"){\r\n							fval = \"-1\";\r\n						}\r\n						fieldValue+=\",\"+fval;\r\n					}\r\n					\r\n				}else{\r\n					if(fieldId == \"\"){\r\n						fieldId = \"-1\";\r\n						fieldValue = \"-1\";\r\n					}else{\r\n						fieldId = \",\"+\"-1\";\r\n						fieldValue = \",\"+\"-1\";\r\n					}\r\n				}\r\n	".toCharArray();
    _jsp_string16 = "&f_weaver_belongto_usertype=".toCharArray();
    _jsp_string37 = "=\"+escape($GetEle(\"".toCharArray();
    _jsp_string87 = "\")!=null){\r\n				if(yearFieldHtmlType==5){//\u5e74\u4efd\u4e3a\u4e0b\u62c9\u6846\r\n				  try{\r\n					  objYear= $GetEle(\"field".toCharArray();
    _jsp_string6 = "\"==9||\"".toCharArray();
    _jsp_string115 = "\").value;\r\n						if(fval == \"\"){\r\n							fval = \"-1\";\r\n						}\r\n						fieldValue= fval;\r\n						if(fieldId == \"\"){\r\n							fieldId = \"-1\";\r\n						}\r\n					}else{\r\n						".toCharArray();
    _jsp_string95 = "\";\r\n					    	}else{\r\n					    		monthId+= \",".toCharArray();
    _jsp_string14 = "\r\n        //\u9644\u4ef6\u4e0a\u4f20\r\n        StartUploadAll();\r\n        checkuploadcompletBydoc();\r\n".toCharArray();
    _jsp_string121 = "\").value;\r\n			if(fval == \"\"){\r\n				fval = \"-1\";\r\n			}\r\n			fieldId=".toCharArray();
    _jsp_string33 = "&node=".toCharArray();
    _jsp_string147 = "\").value) +\"&oldCodeStr=\"+initfieldvalue;\r\n        }\r\n	}\r\n}\r\n\r\nfunction onCreateCodeAgain(ismand){\r\n	if( $GetEle(\"field".toCharArray();
    _jsp_string80 = "\");\r\n							  var yvalue = \"\";\r\n							  try{\r\n							  	yvalue = objYear.options[objYear.selectedIndex].text;\r\n							  }catch(e){\r\n								yvalue = \"-1\";\r\n							  }\r\n							  \r\n							  if(yearId==\"\"){\r\n							  	yearId = yvalue; \r\n							  }else{\r\n							  	yearId += \",\"+yvalue; \r\n							  }\r\n						  	\r\n							}catch(e){}\r\n						}else{\r\n							try{\r\n						    	yearFieldValue= $GetEle(\"field".toCharArray();
    _jsp_string53 = "\");\r\n	var getSeparator = \"".toCharArray();
    _jsp_string143 = "span\")!=null){\r\n		initDataForWorkflowCode();\r\n		if( $GetEle(\"field".toCharArray();
    _jsp_string84 = ";\r\n				    	}\r\n						".toCharArray();
    _jsp_string76 = ";\r\n\r\nfunction initDataForWorkflowCode(){\r\n	yearId=\"\";\r\n	monthId=\"\";\r\n	dateId=\"\";\r\n	fieldId=\"\";\r\n	fieldValue=\"\";\r\n	supSubCompanyId=\"\";\r\n	subCompanyId=\"\";\r\n	departmentId=\"\";\r\n	recordId=-1;\r\n\r\n	yearFieldValue=-1;\r\n	yearFieldHtmlType=\"".toCharArray();
    _jsp_string133 = "\").value;\r\n					}\r\n				}else{\r\n					if(subCompanyId == \"\"){\r\n						subCompanyId=\"-1\";\r\n					}else{\r\n						subCompanyId+=\",-1\";\r\n					}\r\n				}\r\n	".toCharArray();
    _jsp_string35 = "\r\n          if($GetEle(\"".toCharArray();
    _jsp_string17 = "&requestid=".toCharArray();
    _jsp_string25 = "\").value.substring(5,7);\r\n        DayFrom=$GetEle(\"".toCharArray();
    _jsp_string154 = "&workflowId=\"+workflowId+\"&formId=\"+formId+\"&isBill=\"+isBill+\"&codeSeqReservedIdAndCode=\"+encodeURI(idanname)+\"&ismand=\"+ismand+\"&createrdepartmentid=\"+createrdepartmentid;	\r\n			}	\r\n		} ;\r\n		dialognew.Title = \"".toCharArray();
    _jsp_string130 = "\r\n				if( $GetEle(\"field".toCharArray();
    _jsp_string74 = "span\")!=null){\r\n		if(!hasinitfieldvalue) {\r\n			initfieldvalue =  $GetEle(\"field".toCharArray();
    _jsp_string45 = "\r\n	var keywordObj= $GetEle(\"field".toCharArray();
    _jsp_string138 = "\").value;\r\n					}else{\r\n						departmentId+= \",\"+$GetEle(\"field".toCharArray();
    _jsp_string151 = "span\").innerHTML = \"\";\r\n			//\u53d1\u6587\u5b57\u53f7\u91cd\u65b0\u8d4b\u503c(TD18867)\r\n			initfieldvalue = newCode;\r\n\r\n			if(parent.document.getElementById(\"requestmarkSpan\")!=null){\r\n				parent.document.getElementById(\"requestmarkSpan\").innerText=newCode;\r\n			}\r\n\r\n			if( $GetEle(\"requestmarkSpan\")!=null){\r\n				 $GetEle(\"requestmarkSpan\").innerText=newCode;\r\n			}\r\n\r\n		}\r\n\r\n}\r\n\r\nfunction onChooseReservedCode(ismand){\r\n	if( $GetEle(\"field".toCharArray();
    _jsp_string140 = "\")!=null){\r\n			departmentId= $GetEle(\"field".toCharArray();
    _jsp_string98 = "\")!=null){\r\n				monthFieldValue= $GetEle(\"field".toCharArray();
    _jsp_string78 = "		\r\n					if( $GetEle(\"field".toCharArray();
    _jsp_string49 = "','field".toCharArray();
    _jsp_string31 = "&formid=".toCharArray();
    _jsp_string137 = "\")!=null){\r\n					if(departmentId == \"\"){\r\n						departmentId= $GetEle(\"field".toCharArray();
    _jsp_string123 = "\r\n\r\n	\r\n	".toCharArray();
    _jsp_string116 = "\r\n						fieldId+=\",\"+".toCharArray();
    _jsp_string21 = "\"!=\"b\" && \"".toCharArray();
    _jsp_string134 = "\")!=null){\r\n			subCompanyId= $GetEle(\"field".toCharArray();
    _jsp_string118 = "\r\n		if( $GetEle(\"field".toCharArray();
    _jsp_string89 = "\").value;\r\n				    if(yearFieldValue.indexOf(\"-\")>0){\r\n					    var yearFieldValueArray = yearFieldValue.split(\"-\") ;\r\n					    if(yearFieldValueArray.length>=1){\r\n						    yearId=yearFieldValueArray[0];\r\n					    }\r\n				    }else{\r\n					    yearId=yearFieldValue;\r\n				    }\r\n				}\r\n			}\r\n		".toCharArray();
    _jsp_string51 = "span.innerHTML=strKeyword;\r\n		}\r\n\r\n	}\r\n".toCharArray();
    _jsp_string153 = "&workflowId=\"+workflowId+\"&formId=\"+formId+\"&isBill=\"+isBill+\"&codeSeqReservedIdAndCode=\"+con+\"&ismand=\"+ismand;	\r\n		//}	\r\n		\r\n		var urls=\"/systeminfo/BrowserMain.jsp?url=\"+escape(\"/workflow/workflow/showChooseReservedCodeOperate.jsp?workflowId=\"+workflowId+\"&formId=\"+formId+\"&isBill=\"+isBill+\"&yearId=\"+yearId+\"&monthId=\"+monthId+\"&dateId=\"+dateId+\"&fieldId=\"+fieldId+\"&fieldValue=\"+fieldValue+\"&supSubCompanyId=\"+supSubCompanyId+\"&subCompanyId=\"+subCompanyId+\"&departmentId=\"+departmentId+\"&recordId=\"+recordId+\"&createrdepartmentid=\"+createrdepartmentid);	\r\n		var dialognew = new window.top.Dialog();\r\n		dialognew.currentWindow = window;\r\n		//dialog.callbackfunParam = {id:\"test\", name:\"testname\"};\r\n		dialognew.URL = urls;\r\n		dialognew.callbackfun = function (paramobj, con) {\r\n			//alert(con.id);\r\n			//alert(con.name);\r\n			if(typeof(con)!=\"undefined\"&&con!=\"\"){\r\n				var idanname = con.id+\"~~wfcodecon~~\"+con.name;\r\n				initDataForWorkflowCode();\r\n				$GetEle(\"workflowKeywordIframe\").src=\"/workflow/request/WorkflowCodeIframe.jsp?operation=chooseReservedCode&requestId=".toCharArray();
    _jsp_string100 = "\")!=null){\r\n						dateFieldValue= $GetEle(\"field".toCharArray();
    _jsp_string64 = "\r\n    }\r\n    \r\n    if (window.addEventListener)\r\n    window.addEventListener(\"load\", dyniframesize, false);\r\n    else if (window.attachEvent)\r\n    window.attachEvent(\"onload\", dyniframesize);\r\n    else\r\n    window.onload=dyniframesize;\r\n\r\n    function changeChildField(obj, fieldid, childfieldid){\r\n        var paraStr = \"fieldid=\"+fieldid+\"&childfieldid=\"+childfieldid+\"&isbill=".toCharArray();
    _jsp_string81 = "\").value;\r\n							}catch(e){\r\n								yearFieldValue = \"-1\";\r\n							}\r\n						    if(yearFieldValue.indexOf(\"-\")>0){\r\n							    var yearFieldValueArray = yearFieldValue.split(\"-\") ;\r\n							    if(yearFieldValueArray.length>=1){\r\n							    	if(yearId==\"\"){\r\n								    	yearId=yearFieldValueArray[0];\r\n							    	}else{\r\n							    		yearId+= \",\"+yearFieldValueArray[0];\r\n							    	}\r\n							    }\r\n						    }else{\r\n						    	if(yearId==\"\"){\r\n							    	yearId=yearFieldValue;\r\n						    	}else{\r\n						    		yearId+= \",\"+yearFieldValue;\r\n						    	}\r\n						    }\r\n						}\r\n					}else{\r\n						".toCharArray();
    _jsp_string156 = "\";\r\n	dialognew.Modal = true;\r\n	dialognew.Width = 550 ;\r\n	dialognew.Height = 500 ;\r\n	dialognew.isIframe=false;\r\n	dialognew.show();\r\n}\r\n\r\njQuery(\".wffbtn\").mouseover(function(){\r\n   jQuery(this).css(\"color\",\"red\");\r\n}).mouseout(function(){\r\n   jQuery(this).css(\"color\",\"#123885\");\r\n});\r\n\r\nfunction changecancleon(obj){\r\n	/*jQuery(obj).children().eq(1).css(\"cssText\",\"background-color:#f4fcff!important;padding-left:0px!important\");\r\n	jQuery(obj).children().eq(2).css(\"cssText\",\"background-color:#f4fcff!important;padding-left:0px!important\");\r\n	jQuery(obj).children().eq(3).css(\"cssText\",\"background-color:#f4fcff!important;padding-left:0px!important\");*/\r\n	jQuery(obj).find(\".fieldClassChange\").css(\"background-color\",\"#f4fcff\");\r\n	jQuery(obj).find(\"#fieldCancleChange\").find(\"span\").css(\"display\",\"block\");\r\n	//jQuery(obj).children().eq(3).find(\"span\").css(\"display\",\"block\");\r\n}\r\n\r\nfunction changecancleout(obj){\r\n	/*jQuery(obj).children().eq(1).css(\"cssText\",\"background-color:#ffffff!important;padding-left:0px!important\");\r\n	jQuery(obj).children().eq(2).css(\"cssText\",\"background-color:#ffffff!important;padding-left:0px!important\");\r\n	jQuery(obj).children().eq(3).css(\"cssText\",\"background-color:#ffffff!important;padding-left:0px!important\");*/\r\n	jQuery(obj).find(\".fieldClassChange\").css(\"background-color\",\"#ffffff\");\r\n	jQuery(obj).find(\"#fieldCancleChange\").find(\"span\").css(\"display\",\"none\");\r\n	//jQuery(obj).children().eq(3).find(\"span\").css(\"display\",\"none\");\r\n}\r\n\r\n</script>\r\n\r\n".toCharArray();
    _jsp_string5 = "\r\nfunction createDoc(fieldbodyid,docVlaue,isedit)\r\n{\r\n	\r\n	/*\r\n   for(i=0;i<=1;i++){\r\n  		parent.$GetEle(\"oTDtype_\"+i).background=\"/images/tab2_wev8.png\";\r\n  		parent.$GetEle(\"oTDtype_\"+i).className=\"cycleTD\";\r\n  	}\r\n  	parent.$GetEle(\"oTDtype_1\").background=\"/images/tab.active2_wev8.png\";\r\n  	parent.$GetEle(\"oTDtype_1\").className=\"cycleTDCurrent\";\r\n	*/\r\n  	if(\"".toCharArray();
    _jsp_string20 = "&fromrequest=1\");\r\n}\r\n\r\nfunction onNewDoc(fieldid) {\r\n	$GetEle(\"frmmain\").action = \"RequestOperation.jsp\" ;\r\n	$GetEle(\"frmmain\").method.value = \"docnew_\"+fieldid ;\r\n	$GetEle(\"frmmain\").isMultiDoc.value = fieldid ;\r\n	$GetEle(\"frmmain\").src.value='save';\r\n    //\u9644\u4ef6\u4e0a\u4f20\r\n        StartUploadAll();\r\n        jQuery($GetEle(\"flowbody\")).attr(\"onbeforeunload\", \"\");\r\n        checkuploadcomplet();\r\n}\r\n\r\nfunction DateCompare(YearFrom, MonthFrom, DayFrom,YearTo, MonthTo,DayTo)\r\n{\r\n    YearFrom  = parseInt(YearFrom,10);\r\n    MonthFrom = parseInt(MonthFrom,10);\r\n    DayFrom = parseInt(DayFrom,10);\r\n    YearTo    = parseInt(YearTo,10);\r\n    MonthTo   = parseInt(MonthTo,10);\r\n    DayTo = parseInt(DayTo,10);\r\n    if(YearTo<YearFrom)\r\n    return false;\r\n    else{\r\n        if(YearTo==YearFrom){\r\n            if(MonthTo<MonthFrom)\r\n            return false;\r\n            else{\r\n                if(MonthTo==MonthFrom){\r\n                    if(DayTo<DayFrom)\r\n                    return false;\r\n                    else\r\n                    return true;\r\n                }\r\n                else\r\n                return true;\r\n            }\r\n            }\r\n        else\r\n        return true;\r\n        }\r\n}\r\n\r\n\r\nfunction checktimeok(){         <!-- \u7ed3\u675f\u65e5\u671f\u4e0d\u80fd\u5c0f\u4e8e\u5f00\u59cb\u65e5\u671f -->\r\n    if (\"".toCharArray();
    _jsp_string88 = "\");\r\n					  yearId=objYear.options[objYear.selectedIndex].text; \r\n				  }catch(e){\r\n				  }\r\n				}else{\r\n				    yearFieldValue= $GetEle(\"field".toCharArray();
    _jsp_string39 = "\r\n      \r\n      var tempParfieldArr = parfield.split(\",\");\r\n	  for(var i=0;i<tempParfieldArr.length;i++){\r\n		  	var tempParfield = tempParfieldArr[i];\r\n		  	if (tempParfield != \"\") {\r\n		  		tempdata += $G(tempParfield).value+\",\" ;\r\n		  	}\r\n	  }\r\n	  StrData += \"&trgv=\"+tempdata+\"&rand=\"+temprand+\"&tempflag=\"+Math.random();\r\n	  StrData = StrData.replace(/\\+/g,\"%2B\");\r\n      //$GetEle(\"datainputform\").src=\"DataInputFrom.jsp?\"+StrData;\r\n      if($GetEle(\"datainput_\"+parfield)){\r\n		  	$GetEle(\"datainput_\"+parfield).src = \"DataInputFrom.jsp?\"+StrData;\r\n	  }else{\r\n	  		createIframe(\"datainput_\"+parfield);\r\n	  		$GetEle(\"datainput_\"+parfield).src = \"DataInputFrom.jsp?\"+StrData;\r\n	  }\r\n      //xmlhttp.open(\"POST\", \"DataInputFrom.jsp\", false);\r\n      //xmlhttp.setRequestHeader(\"Content-Type\",\"application/x-www-form-urlencoded\");\r\n      //xmlhttp.send(StrData);\r\n  }\r\nfunction getWFLinknum(wffiledname){\r\n    if($GetEle(wffiledname) != null){\r\n        return $GetEle(wffiledname).value;\r\n    }else{\r\n        return 0;\r\n    }\r\n}\r\n\r\nfunction changeKeyword(){\r\n".toCharArray();
    _jsp_string48 = ";\r\n\r\n	if(keywordObj!=null){\r\n		if(keywordisedit==1){\r\n			keywordObj.value=strKeyword;\r\n			if(keywordismand==1){\r\n				checkinput('field".toCharArray();
    _jsp_string69 = "\r\n\r\n    var workflowId=".toCharArray();
    _jsp_string101 = "\").value;\r\n						if(dateFieldValue.indexOf(\"-\")>0){\r\n							var dateFieldValueArray = dateFieldValue.split(\"-\") ;\r\n							if(dateFieldValueArray.length>=3){\r\n								//yearId=dateFieldValueArray[0];\r\n								//monthId=dateFieldValueArray[1];\r\n								//dateId=dateFieldValueArray[2];\r\n								if(dateId==\"\"){\r\n									dateId=dateFieldValueArray[2];\r\n						    	}else{\r\n						    		dateId+= \",\"+dateFieldValueArray[2];\r\n						    	}\r\n							}\r\n						}\r\n					}else{\r\n						".toCharArray();
    _jsp_string8 = "){\r\n  		$GetEle(\"frmmain\").action = \"RequestDocView.jsp?requestid=".toCharArray();
    _jsp_string99 = "\").value;\r\n				if(monthFieldValue.indexOf(\"-\")>0){\r\n					var monthFieldValueArray = monthFieldValue.split(\"-\") ;\r\n					if(monthFieldValueArray.length>=2){\r\n						//yearId=monthFieldValueArray[0];\r\n						monthId=monthFieldValueArray[1];\r\n					}\r\n				}\r\n			}\r\n		".toCharArray();
    _jsp_string3 = "\r\n\r\n\r\n<!--\u8bf7\u6c42\u7684\u6807\u9898\u7ed3\u675f -->\r\n".toCharArray();
    _jsp_string11 = "\"+\"\\\"\"+\"".toCharArray();
    _jsp_string18 = "\");\r\n	}else{\r\n		openFullWindowHaveBar(\"/docs/docs/DocDspExt.jsp?id=\"+showid+\"&imagefileId=\"+docImagefileid+\"&isFromAccessory=true&isrequest=1&f_weaver_belongto_userid=".toCharArray();
    _jsp_string57 = "span');\r\n				}\r\n			}\r\n		}\r\n		dialog.show();\r\n	}\r\n".toCharArray();
    _jsp_string22 = "\"!=\"a\" && $GetEle(\"".toCharArray();
    _jsp_string46 = "\");\r\n\r\n    var keywordismand=".toCharArray();
    _jsp_string97 = "\r\n					}\r\n		".toCharArray();
    _jsp_string72 = ";\r\n	var yearId=-1;\r\n	var monthId=-1;\r\n	var dateId=-1;\r\n	var fieldId=-1;\r\n	var fieldValue=-1;\r\n	var supSubCompanyId=-1;\r\n	var subCompanyId=-1;\r\n	var departmentId=-1;\r\n	var recordId=-1;\r\n	//\u53d1\u6587\u5b57\u53f7\u521d\u59cb\u503c\u53d6\u5f97(TD18867)\r\n	var hasinitfieldvalue=false\r\n	var initfieldValue = -1;\r\n	if( $GetEle(\"field".toCharArray();
    _jsp_string129 = "\r\n		\r\n	\r\n	\r\n	".toCharArray();
    _jsp_string32 = "&bill=".toCharArray();
    _jsp_string36 = "\")) StrData+=\"&".toCharArray();
    _jsp_string135 = "\").value;\r\n		}\r\n		if(subCompanyId==\"\"||(subCompanyId<=0&&subCompanyId>-1)){\r\n		    subCompanyId=\"-1\";\r\n		}\r\n	".toCharArray();
    _jsp_string85 = "\r\n					}\r\n	".toCharArray();
    _jsp_string40 = "\r\n	    var titleObj= $GetEle(\"field".toCharArray();
    _jsp_string12 = "\");\r\n										isDocEmpty=0;\r\n									}else{\r\n										alert(\"".toCharArray();
    _jsp_string108 = ";\r\n        }\r\n".toCharArray();
    _jsp_string139 = "\").value;\r\n					}\r\n				}else{\r\n					if(departmentId == \"\"){\r\n						departmentId=\"-1\";\r\n					}else{\r\n						departmentId+=\",-1\";\r\n					}\r\n				}\r\n	".toCharArray();
    _jsp_string124 = "\")!=null){\r\n					if(supSubCompanyId == \"\"){\r\n						supSubCompanyId= $GetEle(\"field".toCharArray();
    _jsp_string122 = ";\r\n			fieldValue= fval;\r\n		}else{\r\n			fieldId = \"-1\";\r\n			fieldValue = \"-1\";\r\n		}\r\n	".toCharArray();
    _jsp_string68 = "&isdetail=0&selectvalue=\"+pFieldValue+\"&childvalue=\"+finalvalue;\r\n    				$GetEle(\"iframe_\"+pFieldid+\"_\"+fieldid+\"_00\").src = \"SelectChange.jsp?\"+paraStr;\r\n    			}\r\n    		}\r\n    	}catch(e){}\r\n    }\r\n    ".toCharArray();
    _jsp_string94 = "\r\n							if(monthId==\"\"){\r\n								monthId=\"".toCharArray();
    _jsp_string54 = "\";\r\n	var getSeparator_temp = \"".toCharArray();
    _jsp_string66 = "&uploadType=".toCharArray();
    _jsp_string4 = "\r\n<script language=\"javascript\">\r\n\r\nfunction funcClsDateTime(){\r\n	//var onlstr = new clsDateTime();\r\n}                \r\n\r\nif (window.addEventListener){\r\n    window.addEventListener(\"load\", funcClsDateTime, false);\r\n}else if (window.attachEvent){\r\n    window.attachEvent(\"onload\", funcClsDateTime);\r\n}else{\r\n    window.onload=funcClsDateTime;\r\n}\r\n\r\n".toCharArray();
    _jsp_string126 = "\").value;\r\n					}\r\n				}else{\r\n					if(supSubCompanyId == \"\"){\r\n						supSubCompanyId=\"-1\";\r\n					}else{\r\n						supSubCompanyId+=\",-1\";\r\n					}\r\n				}\r\n	".toCharArray();
    _jsp_string24 = "\").value.substring(0,4);\r\n        MonthFrom=$GetEle(\"".toCharArray();
    _jsp_string109 = "\r\n	    if(monthId==\"\"||monthId<=0){\r\n	        monthId=".toCharArray();
    _jsp_string102 = "\r\n						if(dateId==\"\"){\r\n							dateId=\"".toCharArray();
    _jsp_string63 = "\");\r\n    ".toCharArray();
    _jsp_string83 = ";\r\n				    	}else{\r\n				    		yearId+= \",\"+".toCharArray();
    _jsp_string44 = "\r\n}\r\n\r\nfunction URLencode(sStr) \r\n{	\r\n	   return escape(sStr).replace(/\\+/g, '%2B').replace(/\\\"/g,'%22').replace(/\\'/g, '%27').replace(/\\//g,'%2F'); \r\n}\r\nfunction updateKeywordData(strKeyword){\r\n".toCharArray();
    _jsp_string26 = "\").value.substring(8,10);\r\n        YearTo=$GetEle(\"".toCharArray();
    _jsp_string152 = "span\")!=null){\r\n        //initDataForWorkflowCode();\r\n        //url=uescape(\"/workflow/workflow/showChooseReservedCodeOperate.jsp?workflowId=\"+workflowId+\"&formId=\"+formId+\"&isBill=\"+isBill+\"&yearId=\"+yearId+\"&monthId=\"+monthId+\"&dateId=\"+dateId+\"&fieldId=\"+fieldId+\"&fieldValue=\"+fieldValue+\"&supSubCompanyId=\"+supSubCompanyId+\"&subCompanyId=\"+subCompanyId+\"&departmentId=\"+departmentId+\"&recordId=\"+recordId);	\r\n	    //con = window.showModalDialog(\"/systeminfo/BrowserMain.jsp?url=\"+url, \"\" , \"dialogWidth=550px;dialogHeight=550px\");\r\n\r\n		//if(typeof(con)!=\"undefined\"&&con!=\"\"){\r\n		//	$GetEle(\"workflowKeywordIframe\").src=\"/workflow/request/WorkflowCodeIframe.jsp?operation=chooseReservedCode&requestId=".toCharArray();
    _jsp_string30 = "\");\r\n            return false;\r\n        }\r\n    }\r\n    return true;\r\n}\r\n\r\nfunction datainput(parfield){                <!--\u6570\u636e\u5bfc\u5165-->\r\n      //var xmlhttp=XmlHttp.create();\r\n	try{\r\n		if(event.propertyName && event.propertyName.toLowerCase() != \"value\"){\r\n			return;\r\n		}\r\n		var src = event.srcElement || event.target; \r\n		if(src.tagName.toLowerCase() == 'button'){\r\n			return ;\r\n		}\r\n	}catch(e){}  \r\n      var detailsum=\"0\";\r\n      try{\r\n          detailsum=$GetEle(\"detailsum\").value;\r\n      }catch(e){ detailsum=\"0\";}\r\n      var tempdata = \"\";\r\n      var temprand = $GetEle(\"rand\").value ;\r\n      var StrData=\"id=".toCharArray();
    _jsp_string141 = "\").value;\r\n		}\r\n		if(departmentId==\"\"||(departmentId<=0&&departmentId>-1)){\r\n		    departmentId=\"-1\";\r\n		}\r\n	".toCharArray();
    _jsp_string65 = "&selectedfieldid=".toCharArray();
    _jsp_string142 = "\r\n}\r\n\r\n//\u53d1\u6587\u5b57\u53f7\u53d8\u66f4(TD18867)\r\nfunction onChangeCode(ismand){\r\n	if( $GetEle(\"field".toCharArray();
    _jsp_string70 = ";\r\n    var formId=".toCharArray();
    _jsp_string29 = "\").value.substring(8,10);\r\n        if (!DateCompare(YearFrom, MonthFrom, DayFrom,YearTo, MonthTo,DayTo )){\r\n            window.alert(\"".toCharArray();
    _jsp_string106 = "\").value;\r\n				if(dateFieldValue.indexOf(\"-\")>0){\r\n					var dateFieldValueArray = dateFieldValue.split(\"-\") ;\r\n					if(dateFieldValueArray.length>=3){\r\n						//yearId=dateFieldValueArray[0];\r\n						//monthId=dateFieldValueArray[1];\r\n						dateId=dateFieldValueArray[2];\r\n					}\r\n				}\r\n			}\r\n		".toCharArray();
    _jsp_string90 = "\r\n\r\n		\r\n		".toCharArray();
    _jsp_string34 = "&detailsum=\"+detailsum+\"&trg=\"+parfield;\r\n      ".toCharArray();
    _jsp_string61 = "\r\n    ".toCharArray();
    _jsp_string114 = ";\r\n						var fval = $GetEle(\"field".toCharArray();
    _jsp_string113 = "\")!=null){\r\n					if(fieldId == \"\"){\r\n						fieldId=".toCharArray();
    _jsp_string79 = "\")!=null){\r\n						if(yearFieldHtmlType==5){//\u5e74\u4efd\u4e3a\u4e0b\u62c9\u6846\r\n						  try{\r\n							  var objYear= $GetEle(\"field".toCharArray();
    _jsp_string148 = "span\")!=null){\r\n        initDataForWorkflowCode();\r\n        $GetEle(\"workflowKeywordIframe\").src=\"/workflow/request/WorkflowCodeIframe.jsp?operation=CreateCodeAgain&requestId=".toCharArray();
    _jsp_string15 = "\r\n\r\n    }\r\n\r\n\r\n}\r\n\r\nfunction openDocExt(showid,versionid,docImagefileid,isedit){\r\n	jQuery($GetEle(\"flowbody\")).attr(\"onbeforeunload\", \"\");\r\n\r\n	// isAppendTypeField\u53c2\u6570\u6807\u8bc6  \u5f53\u524d\u5b57\u6bb5\u7c7b\u578b\u662f\u9644\u4ef6\u4e0a\u4f20\u7c7b\u578b\uff0c\u4e0d\u8bba\u8be5\u9644\u4ef6\u6240\u5728\u6587\u6863\u5185\u5bb9\u662f\u5426\u4e3a\u7a7a\u3001\u6216\u8005\u5b58\u5728\u6700\u65b0\u7248\u672c\uff0c\u5728\u8be5\u94fe\u63a5\u6253\u5f00\u9875\u9762\u6c38\u8fdc\u6253\u5f00\u8be5\u9644\u4ef6\u5185\u5bb9\u3001\u4e0d\u663e\u793a\u8be5\u9644\u4ef6\u6240\u5728\u6587\u6863\u5185\u5bb9\u3002\r\n\r\n\r\n\r\n\r\n\r\n	if(isedit==1){\r\n		openFullWindowHaveBar(\"/docs/docs/DocEditExt.jsp?id=\"+showid+\"&imagefileId=\"+docImagefileid+\"&isFromAccessory=true&isrequest=1&f_weaver_belongto_userid=".toCharArray();
    _jsp_string104 = "\";\r\n				    	}\r\n						".toCharArray();
    _jsp_string144 = "\").value == \"\" ||  $GetEle(\"field".toCharArray();
    _jsp_string112 = "	\r\n				if( $GetEle(\"field".toCharArray();
    _jsp_string82 = "\r\n						if(yearId==\"\"){\r\n					    	yearId=".toCharArray();
    _jsp_string86 = "\r\n			if( $GetEle(\"field".toCharArray();
    _jsp_string96 = "\";\r\n					    	}\r\n						".toCharArray();
    _jsp_string59 = "\r\n    if (document.getElementById)\r\n    {\r\n        //\u81ea\u52a8\u8c03\u6574iframe\u9ad8\u5ea6\r\n        dyniframe =  $GetEle(\"".toCharArray();
    _jsp_string52 = "\r\n}\r\n\r\n\r\nfunction onShowKeyword(isbodymand){\r\n".toCharArray();
    _jsp_string92 = "\")!=null){\r\n						monthFieldValue= $GetEle(\"field".toCharArray();
    _jsp_string42 = "\");\r\n\r\n        if(titleObj!=null&&keywordObj!=null){\r\n\r\n		     $GetEle(\"workflowKeywordIframe\").src=\"/docs/sendDoc/WorkflowKeywordIframe.jsp?operation=UpdateKeywordDataEscape&docTitle=\"+escape(URLencode(titleObj.value))+\"&docKeyword=\"+escape(URLencode(keywordObj.value));\r\n	    }\r\n".toCharArray();
    _jsp_string110 = "\r\n	    if(dateId==\"\"||dateId<=0){\r\n	        dateId=".toCharArray();
    _jsp_string27 = "\").value.substring(0,4);\r\n        MonthTo=$GetEle(\"".toCharArray();
    _jsp_string103 = "\";\r\n				    	}else{\r\n				    		dateId+= \",".toCharArray();
    _jsp_string56 = "\";\r\n		dialog.Height = 600;\r\n		dialog.Width = 500;\r\n		dialog.Drag = true;\r\n		dialog.URL = tempUrl;\r\n		dialog.callbackfun = function(params,data){\r\n			if(data){\r\n				keywordObj.value=data.name?data.name.replace(/,/g,\" \"):\"\";\r\n				jQuery(keywordObj).data(\"keywordid\",data.id);\r\n				if(isbodymand==1){\r\n					checkinput('field".toCharArray();
    _jsp_string125 = "\").value;\r\n					}else{\r\n						supSubCompanyId+=\",\"+$GetEle(\"field".toCharArray();
    _jsp_string93 = "\").value;\r\n						if(monthFieldValue.indexOf(\"-\")>0){\r\n							var monthFieldValueArray = monthFieldValue.split(\"-\") ;\r\n							if(monthFieldValueArray.length>=2){\r\n								//yearId=monthFieldValueArray[0];\r\n								if(monthId==\"\"){\r\n									monthId=monthFieldValueArray[1];\r\n						    	}else{\r\n						    		monthId+= \",\"+monthFieldValueArray[1];\r\n						    	}\r\n							}\r\n						}\r\n					}else{\r\n						".toCharArray();
    _jsp_string136 = "\r\n	\r\n	\r\n	".toCharArray();
    _jsp_string91 = "	\r\n					if( $GetEle(\"field".toCharArray();
    _jsp_string55 = "\";\r\n	if(keywordObj!=null){\r\n		strKeyword=keywordObj.value;\r\n		strKeyword=strKeyword.replace(/%/g,getSeparator);  //\u56e0\u4e3a%\u4f5c\u4e3a\u7279\u6b8a\u5b57\u7b26\uff0c%\u4e5f\u4f5c\u4e3a\u8f6c\u7801\u7684\u5b57\u7b26\uff0c\u5982\u679c\u901a\u8fc7url\u4f20\u53c2\u5c31\u51fa\u73b0\u4e0d\u53ef\u89e3\u6790\u51fa\u73b0\u4e71\u7801;\u6b64\u5904\u66ff\u6362\u540e\uff0c\u5f85\u663e\u793a\u518d\u66ff\u6362\u56de\u6765\u3002\r\n\r\n\r\n\r\n\r\n\r\n		strKeyword=strKeyword.replace(/\"/g,getSeparator_temp);\r\n        tempUrl=\"/docs/sendDoc/WorkflowKeywordBrowserMulti.jsp?strKeyword=\"+jQuery(keywordObj).data(\"keywordid\");\r\n		dialog = new window.top.Dialog();\r\n		dialog.currentWindow = window;\r\n		dialog.Title = \"".toCharArray();
    _jsp_string23 = "\").value != \"\")\r\n    {\r\n        YearFrom=$GetEle(\"".toCharArray();
    _jsp_string58 = "\r\n}\r\n\r\n\r\nfunction uescape(url){\r\n    return escape(url);\r\n}\r\n//** iframe\u81ea\u52a8\u9002\u5e94\u9875\u9762 **//\r\n\r\n    function dyniframesize()\r\n    {\r\n    var dyniframe;\r\n    ".toCharArray();
    _jsp_string43 = "\r\n	    var titleObj= $GetEle(\"requestname\");\r\n	    var keywordObj= $GetEle(\"field".toCharArray();
    _jsp_string13 = "\");\r\n									}\r\n									return ;\r\n								}\r\n					        }\r\n					    }catch(e){\r\n					        //\u9644\u4ef6\u4e0a\u4f20\r\n					        StartUploadAll();\r\n                            checkuploadcompletBydoc();\r\n					    }\r\n".toCharArray();
    _jsp_string77 = "\";\r\n	monthFieldValue=-1;\r\n	dateFieldValue=-1;	\r\n\r\n	".toCharArray();
    _jsp_string9 = "&docValue=\"+docVlaue;\r\n  	}else{\r\n  		$GetEle(\"frmmain\").action = \"RequestOperation.jsp?docView=\"+isedit+\"&docValue=\"+docVlaue+\"&isFromEditDocument=true\";\r\n  	}\r\n	$GetEle(\"frmmain\").method.value = \"crenew_\"+fieldbodyid ;\r\n	$GetEle(\"frmmain\").target=\"delzw\";\r\n    parent.delsave();\r\n	if(check_form($GetEle(\"frmmain\"),'requestname')){\r\n		if( $GetEle(\"needoutprint\"))  $GetEle(\"needoutprint\").value = \"1\";//\u6807\u8bc6\u70b9\u6b63\u6587\r\n\r\n\r\n\r\n\r\n\r\n		$GetEle(\"src\").value='save';\r\n		$GetEle(\"isremark\").value='0';\r\n\r\n//\u4fdd\u5b58\u7b7e\u7ae0\u6570\u636e\r\n".toCharArray();
    _jsp_string105 = "\")!=null){\r\n				dateFieldValue= $GetEle(\"field".toCharArray();
    _jsp_string10 = "\r\n	                    try{  \r\n					        if(typeof(eval(\"SaveSignature_save\"))==\"function\"){\r\n					              if(SaveSignature_save()){\r\n		                            //\u9644\u4ef6\u4e0a\u4f20\r\n		                            StartUploadAll();\r\n		                            checkuploadcompletBydoc();\r\n		                        }else{\r\n									if(isDocEmpty==1){\r\n										alert(\"\\\"\"+\"".toCharArray();
    _jsp_string62 = "\r\n    alert(\"".toCharArray();
    _jsp_string38 = "\").value);\r\n      ".toCharArray();
    _jsp_string1 = "\r\n".toCharArray();
    _jsp_string67 = "&isdetail=0&selectvalue=\"+obj.value;\r\n        $GetEle(\"selectChange\").src = \"SelectChange.jsp?\"+paraStr;\r\n        //alert($GetEle(\"selectChange\").src);\r\n    }\r\n    function doInitChildSelect(fieldid,pFieldid,finalvalue){\r\n    	try{\r\n    		var pField = $GetEle(\"field\"+pFieldid);\r\n    		if(pField != null){\r\n    			var pFieldValue = pField.value;\r\n    			if(pFieldValue==null || pFieldValue==\"\"){\r\n    				jQuery('#field'+fieldid +' option:gt(0)').remove();\r\n    				return;\r\n    			}\r\n    			if(pFieldValue!=null && pFieldValue!=\"\"){\r\n    				var field = $GetEle(\"field\"+fieldid);\r\n    			    var paraStr = \"fieldid=\"+pFieldid+\"&childfieldid=\"+fieldid+\"&isbill=".toCharArray();
    _jsp_string150 = "\").value=newCode;\r\n			 $GetEle(\"field".toCharArray();
    _jsp_string107 = "\r\n	    if(yearId==\"\"||yearId<=0){\r\n	        yearId=".toCharArray();
    _jsp_string132 = "\").value;\r\n					}else{\r\n						subCompanyId+=\",\"+$GetEle(\"field".toCharArray();
    _jsp_string47 = ";\r\n    var keywordisedit=".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string60 = "\");\r\n        if (dyniframe && !window.opera)\r\n        {\r\n            if (dyniframe.contentDocument && dyniframe.contentDocument.body.offsetHeight){ //\u5982\u679c\u7528\u6237\u7684\u6d4f\u89c8\u5668\u662fNetScape\r\n                dyniframe.height = dyniframe.contentDocument.body.offsetHeight+20;\r\n            }else if (dyniframe.Document && dyniframe.Document.body.scrollHeight){ //\u5982\u679c\u7528\u6237\u7684\u6d4f\u89c8\u5668\u662fIE\r\n                //alert(dyniframe.name+\"|\"+dyniframe.Document.body.scrollHeight);\r\n                dyniframe.Document.body.bgColor=\"transparent\";\r\n                dyniframe.height = dyniframe.Document.body.scrollHeight+20;\r\n            }\r\n        }\r\n    }\r\n    ".toCharArray();
    _jsp_string149 = "&workflowId=\"+workflowId+\"&formId=\"+formId+\"&isBill=\"+isBill+\"&yearId=\"+yearId+\"&monthId=\"+monthId+\"&dateId=\"+dateId+\"&fieldId=\"+fieldId+\"&fieldValue=\"+fieldValue+\"&supSubCompanyId=\"+supSubCompanyId+\"&subCompanyId=\"+subCompanyId+\"&departmentId=\"+departmentId+\"&recordId=\"+recordId+\"&ismand=\"+ismand+\"&createrdepartmentid=\"+createrdepartmentid;\r\n	}\r\n}\r\nfunction onCreateCodeAgainReturn(newCode,ismand){\r\n\r\n		if(typeof(newCode)!=\"undefined\"&&newCode!=\"\"){\r\n			 $GetEle(\"field".toCharArray();
    _jsp_string28 = "\").value.substring(5,7);\r\n        DayTo=$GetEle(\"".toCharArray();
    _jsp_string50 = "span');\r\n			}\r\n		}else{\r\n			keywordObj.value=strKeyword;\r\n			field".toCharArray();
    _jsp_string155 = "\";\r\n		dialognew.Modal = true;\r\n		dialognew.Width = 550 ;\r\n		dialognew.Height = 500 ;\r\n		dialognew.isIframe=false;\r\n		dialognew.show();\r\n		\r\n	}\r\n\r\n}\r\n\r\nfunction onNewReservedCode(ismand){\r\n    initDataForWorkflowCode();\r\n    //url=uescape(\"/workflow/workflow/showNewReservedCodeOperate.jsp?workflowId=\"+workflowId+\"&formId=\"+formId+\"&isBill=\"+isBill+\"&yearId=\"+yearId+\"&monthId=\"+monthId+\"&dateId=\"+dateId+\"&fieldId=\"+fieldId+\"&fieldValue=\"+fieldValue+\"&supSubCompanyId=\"+supSubCompanyId+\"&subCompanyId=\"+subCompanyId+\"&departmentId=\"+departmentId+\"&recordId=\"+recordId);	\r\n	//con = window.showModalDialog(\"/systeminfo/BrowserMain.jsp?url=\"+url, \"\", \"dialogWidth=550px;dialogHeight=550px\");\r\n\r\n	var urls=\"/systeminfo/BrowserMain.jsp?url=\"+escape(\"/workflow/workflow/showNewReservedCodeOperate.jsp?workflowId=\"+workflowId+\"&formId=\"+formId+\"&isBill=\"+isBill+\"&yearId=\"+yearId+\"&monthId=\"+monthId+\"&dateId=\"+dateId+\"&fieldId=\"+fieldId+\"&fieldValue=\"+fieldValue+\"&supSubCompanyId=\"+supSubCompanyId+\"&subCompanyId=\"+subCompanyId+\"&departmentId=\"+departmentId+\"&recordId=\"+recordId+\"&createrdepartmentid=\"+createrdepartmentid);	\r\n	var dialognew = new window.top.Dialog();\r\n	dialognew.currentWindow = window;\r\n	//dialog.callbackfunParam = {id:\"test\", name:\"testname\"};\r\n	dialognew.URL = urls;\r\n	dialognew.Title = \"".toCharArray();
    _jsp_string111 = "\r\n\r\n\r\n	".toCharArray();
    _jsp_string75 = "\").value;\r\n			hasinitfieldvalue = true;\r\n		}\r\n	}\r\n\r\n	var yearFieldValue=-1;\r\n    var yearFieldHtmlType=-1;\r\n	var monthFieldValue=-1;\r\n	var dateFieldValue=-1;	\r\n	var createrdepartmentid=".toCharArray();
    _jsp_string146 = "&workflowId=\"+workflowId+\"&formId=\"+formId+\"&isBill=\"+isBill+\"&yearId=\"+yearId+\"&monthId=\"+monthId+\"&dateId=\"+dateId+\"&fieldId=\"+fieldId+\"&fieldValue=\"+fieldValue+\"&supSubCompanyId=\"+supSubCompanyId+\"&subCompanyId=\"+subCompanyId+\"&departmentId=\"+departmentId+\"&recordId=\"+recordId+\"&ismand=\"+ismand+\"&returnCodeStr=\"+ escape($GetEle(\"field".toCharArray();
    _jsp_string128 = "\").value;\r\n		}\r\n		if(supSubCompanyId==\"\"||(supSubCompanyId<=0&&supSubCompanyId>-1)){\r\n		    supSubCompanyId=\"-1\";\r\n		}\r\n	".toCharArray();
    _jsp_string73 = "\")!=null&& $GetEle(\"field".toCharArray();
    _jsp_string127 = "\")!=null){\r\n			supSubCompanyId= $GetEle(\"field".toCharArray();
    _jsp_string119 = "\")!=null){\r\n			".toCharArray();
    _jsp_string131 = "\")!=null){\r\n					if(subCompanyId == \"\"){\r\n						subCompanyId= $GetEle(\"field".toCharArray();
    _jsp_string7 = "\"==5||".toCharArray();
    _jsp_string41 = "\");\r\n	    var keywordObj= $GetEle(\"field".toCharArray();
    _jsp_string120 = "\r\n			var fval = $GetEle(\"field".toCharArray();
    _jsp_string2 = "\r\n\r\n".toCharArray();
    _jsp_string71 = ";\r\n    var isBill=".toCharArray();
  }
}
