/*
 * JSP generated by Resin-3.1.8 (built Mon, 17 Nov 2008 12:15:21 PST)
 */

package _jsp._workflow._request;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.text.*;
import java.util.*;
import weaver.general.Util;
import weaver.general.TimeUtil;
import weaver.systeminfo.SystemEnv;
import weaver.general.SessionOper;
import weaver.hrm.performance.*;
import weaver.worktask.worktask.*;
import weaver.general.*;

public class _workflowviewwt__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      weaver.conn.RecordSet recordSet_requestbase;
      recordSet_requestbase = (weaver.conn.RecordSet) pageContext.getAttribute("recordSet_requestbase");
      if (recordSet_requestbase == null) {
        recordSet_requestbase = new weaver.conn.RecordSet();
        pageContext.setAttribute("recordSet_requestbase", recordSet_requestbase);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      weaver.conn.RecordSet rs;
      rs = (weaver.conn.RecordSet) pageContext.getAttribute("rs");
      if (rs == null) {
        rs = new weaver.conn.RecordSet();
        pageContext.setAttribute("rs", rs);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      weaver.hrm.resource.ResourceComInfo resourceComInfo;
      resourceComInfo = (weaver.hrm.resource.ResourceComInfo) pageContext.getAttribute("resourceComInfo");
      if (resourceComInfo == null) {
        resourceComInfo = new weaver.hrm.resource.ResourceComInfo();
        pageContext.setAttribute("resourceComInfo", resourceComInfo);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      
int requestid = Util.getIntValue(request.getParameter("requestid"), 0);
int userid = Util.getIntValue(request.getParameter("userid"), 0);
int usertype = Util.getIntValue(request.getParameter("usertype"), 0);
int languageid = Util.getIntValue(request.getParameter("languageid"), 7);
String sql = "";
sql = "select * from worktask_requestbase where deleted=0 and sourceworkflowid="+requestid;
recordSet_requestbase.execute(sql);
if(recordSet_requestbase.next()){
	Hashtable worktaskStatus_hs = new Hashtable();
	sql = "select * from SysPubRef where masterCode='WorkTaskStatus' and flag=1";
	rs.execute(sql);
	while(rs.next()){
		String detailCode_tmp = ""+Util.getIntValue(rs.getString("detailCode"), 0);
		String worktaskStatusName_tmp = Util.null2String(SystemEnv.getHtmlLabelName(Util.getIntValue(rs.getString("detailLabel")), languageid));
		worktaskStatus_hs.put("worktaskstatus_"+detailCode_tmp, worktaskStatusName_tmp);
	}
	recordSet_requestbase.beforFirst();
	session.setAttribute("sourceworkflowid", ""+requestid);

      out.write(_jsp_string2, 0, _jsp_string2.length);
      out.print((SystemEnv.getHtmlLabelName(22175, languageid)));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((SystemEnv.getHtmlLabelName(15486, languageid)));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((SystemEnv.getHtmlLabelName(16936, languageid)));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((SystemEnv.getHtmlLabelName(22134, languageid)));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((SystemEnv.getHtmlLabelName(22074, languageid)));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      
		int count = 0;
		String classStr = " class=\"datalight\" ";
		while(recordSet_requestbase.next()){
			String liableperson = Util.null2String(recordSet_requestbase.getString("liableperson"));
			if("".equals(liableperson)){
				continue;
			}
			count++;
			int wt_requestid = Util.getIntValue(recordSet_requestbase.getString("requestid"), 0);
			String taskcontent = Util.null2String(recordSet_requestbase.getString("taskcontent"));
			int status = Util.getIntValue(recordSet_requestbase.getString("status"), 1);
			String showName = "";
			String[] liablepersons = Util.TokenizerString2(liableperson, ",");
			for(int i=0; i<liablepersons.length; i++){
				int liableperson_tmp = Util.getIntValue(liablepersons[i]);
				String name = resourceComInfo.getLastname(""+liableperson_tmp);
				if(!"".equals(name)){
					showName += ("<a href=\"javaScript:openFullWindowHaveBar('/hrm/resource/HrmResource.jsp?id="+liableperson_tmp+"')\">"+name+"</a>&nbsp;");
				}
			}
			String status_name = Util.null2String((String)worktaskStatus_hs.get("worktaskstatus_"+status));
			out.println("<tr"+classStr+"><td align=\"center\">"+count+"</td>");
			out.println("<td>"+showName+"</td>");
			out.println("<td><a href=\"javaScript:openFullWindowHaveBar('/worktask/request/ViewWorktask.jsp?isfromworkflow=1&deswtrequestcount="+count+"&requestid="+wt_requestid+"')\">"+taskcontent+"</a></td>");
			out.println("<td align=\"center\">"+status_name+"</td></td>");
			out.println("<tr><td class=\"Line2\" colSpan=3></td></tr>");
			session.setAttribute("deswtrequestid"+count, ""+wt_requestid);
			if(count%2 == 0){
				classStr = " class=\"datalight\" ";
			}else{
				classStr = " class=\"datadark\" ";
			}
		}
	
      out.write(_jsp_string6, 0, _jsp_string6.length);
      }
      out.write(_jsp_string7, 0, _jsp_string7.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 1886798272571451039L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("workflow/request/WorkflowViewWT.jsp"), -1741733208811186298L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string2;
  private final static char []_jsp_string3;
  private final static char []_jsp_string7;
  private final static char []_jsp_string6;
  private final static char []_jsp_string5;
  private final static char []_jsp_string1;
  private final static char []_jsp_string4;
  private final static char []_jsp_string0;
  static {
    _jsp_string2 = "\r\n<br>\r\n<table class=\"ListStyle\">\r\n	<colgroup>\r\n	<col width=\"5%\">\r\n	<col width=\"30%\">\r\n	<col width=\"50%\">\r\n	<col width=\"15%\">\r\n	<tr class=\"HeaderForWF\">\r\n		<th colspan=\"4\">".toCharArray();
    _jsp_string3 = "</th>\r\n	</tr>\r\n	<tr class=\"HeaderForWF\">\r\n		<td align=\"center\">".toCharArray();
    _jsp_string7 = "\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string6 = "\r\n</table>\r\n<br>\r\n".toCharArray();
    _jsp_string5 = "</td>\r\n	</tr>\r\n	<tr><td class=\"Line2\" colSpan=\"4\"></td></tr>\r\n	".toCharArray();
    _jsp_string1 = "\r\n".toCharArray();
    _jsp_string4 = "</td>\r\n		<td align=\"center\">".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
  }
}
