var urmsg={
	name:"Name",
	size:"Size",
	lastModified:"LastModified",
	fileDir:"File Directory",
	submit:"Submit",
	cancel:"Cancel",
	clear:"Clear",
	createDir:"Create Directory",
	renameDir:"rename Directory",
	deleteDir:"delete Directory",
	deleteFile:"delete File",
	fileNotExist:"File not Exist or Be Moved!",
	noSpecialChar:"Name only can be letter or number!",
	noChineseChar:"No Chinese Char",
	dirName:"Directory Name",
	createDirFailure:"Create Directory Failure",
	noRight:"Can not modify the system directory!",
	deleteFailure:"Delete Failure",
	renameFailure:"Rename Failure",
	noNull:"Input name",
	noSelect:"No Selected File!",
	noSpace:"No Space!",
	upload:"Upload File"
}