var urmsg={
	name:"名称",
	size:"大小",
	lastModified:"修改日期",
	fileDir:"文件目录",
	submit:"确定",
	cancel:"取消",
	clear:"清除",
	createDir:"新建目录",
	renameDir:"重命名目录",
	deleteDir:"删除目录",
	deleteFile:"删除文件",
	fileNotExist:"您选择的文件不存在或者已被移动！",
	noSpecialChar:"名称只能包含字母或者数字！",
	noChineseChar:"不能包含中文",
	dirName:"目录名称",
	createDirFailure:"目录创建失败",
	noRight:"不能修改系统目录！",
	deleteFailure:"删除失败",
	renameFailure:"重命名失败",
	noNull:"请输入名称",
	noSelect:"未选择文件！",
	noSpace:"不能包含空格！",
	upload:"上传文件"
	
}