var i18n = $.extend({}, i18n || {}, {
    xgcalendar: {
        dateformat: {
            "fulldaykey": "yyyyMMdd",
            "fulldayshow": "yyyy年M月d日",
            "fulldayvalue": "yyyy-MM-dd",
            "Md": "M月/d日 (W)",
            "Md3": "M月d日",
            "yM": "yyyy年M月",
            "separator": "-",
            "year_index": 0,
            "month_index": 1,
            "day_index": 2,
            "day": "d日",
            "sun": "周日",
            "mon": "周一",
            "tue": "周二",
            "wed": "周三",
            "thu": "周四",
            "fri": "周五",
            "sat": "周六",
            "jan": "一月",
            "feb": "二月",
            "mar": "三月",
            "apr": "四月",
            "may": "五月",
            "jun": "六月",
            "jul": "七月",
            "aug": "八月",
            "sep": "九月",
            "oct": "十月",
            "nov": "十一月",
            "dec": "十二月"
        },
        "no_implemented": "没有实现",
        "to_date_view": "点击转到该日期的日视图",
        "i_undefined": "未设置",
        "allday_event": "全天日程",
        "repeat_event": "跨天日程",
        "time": "时间",
        "event": "事件",
        "location": "地点",
        "participant": "参与人",
        "get_data_exception": "获取数据发生异常",
        "new_event": "新日程",
        "confirm_delete_event": "确定删除该日程吗？",
        "confrim_delete_event_or_all": "删除此序列还是单个事件？\r\n点击[确定]删除事件,点击[取消]删除序列",
        "data_format_error": "数据格式错误！",
        "invalid_title": "日程标题不能为空",
        "view_no_ready": "视图未准备完毕",
        "example": "例如：有个办公会议",
        "content": "內 容",
        "create_event": "保存",
        "update_detail": "修改日程详细信息",
        "click_to_detail": "点击查看详细",
        "i_delete": "刪除",
        "day_plural": "天",
        "others": "另外",
        "item": "个",
        "edit_event":"编辑日程",
        "viewDetail":"查看详细",
        "confirm_delete_event":"您确实要删除此日程吗"
    }
}); 