/*
 * JSP generated by Resin-3.1.8 (built Mon, 17 Nov 2008 12:15:21 PST)
 */

package _jsp._page._element._compatible;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import weaver.general.*;
import weaver.homepage.style.HomepageStyleBean;
import java.util.*;
import weaver.hrm.*;
import weaver.systeminfo.*;
import weaver.general.StaticObj;
import weaver.general.Util;
import weaver.hrm.settings.RemindSettings;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

public class _newstabcontentdata__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      weaver.page.PageCominfo hpc;
      hpc = (weaver.page.PageCominfo) pageContext.getAttribute("hpc");
      if (hpc == null) {
        hpc = new weaver.page.PageCominfo();
        pageContext.setAttribute("hpc", hpc);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      weaver.page.PageUtil hpu;
      hpu = (weaver.page.PageUtil) pageContext.getAttribute("hpu");
      if (hpu == null) {
        hpu = new weaver.page.PageUtil();
        pageContext.setAttribute("hpu", hpu);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      weaver.homepage.cominfo.HomepageElementCominfo hpec;
      hpec = (weaver.homepage.cominfo.HomepageElementCominfo) pageContext.getAttribute("hpec");
      if (hpec == null) {
        hpec = new weaver.homepage.cominfo.HomepageElementCominfo();
        pageContext.setAttribute("hpec", hpec);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      weaver.homepage.cominfo.HomepageElementFieldCominfo hpefc;
      hpefc = (weaver.homepage.cominfo.HomepageElementFieldCominfo) pageContext.getAttribute("hpefc");
      if (hpefc == null) {
        hpefc = new weaver.homepage.cominfo.HomepageElementFieldCominfo();
        pageContext.setAttribute("hpefc", hpefc);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      weaver.homepage.HomepageExtShow hpes;
      hpes = (weaver.homepage.HomepageExtShow) pageContext.getAttribute("hpes");
      if (hpes == null) {
        hpes = new weaver.homepage.HomepageExtShow();
        pageContext.setAttribute("hpes", hpes);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      weaver.homepage.style.HomepageStyleUtil hpsu;
      hpsu = (weaver.homepage.style.HomepageStyleUtil) pageContext.getAttribute("hpsu");
      if (hpsu == null) {
        hpsu = new weaver.homepage.style.HomepageStyleUtil();
        pageContext.setAttribute("hpsu", hpsu);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      weaver.page.PageCominfo pc;
      pc = (weaver.page.PageCominfo) pageContext.getAttribute("pc");
      if (pc == null) {
        pc = new weaver.page.PageCominfo();
        pageContext.setAttribute("pc", pc);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      weaver.page.style.ElementStyleCominfo esc;
      esc = (weaver.page.style.ElementStyleCominfo) pageContext.getAttribute("esc");
      if (esc == null) {
        esc = new weaver.page.style.ElementStyleCominfo();
        pageContext.setAttribute("esc", esc);
      }
      out.write(_jsp_string2, 0, _jsp_string2.length);
      weaver.conn.RecordSet rsCommon;
      rsCommon = (weaver.conn.RecordSet) pageContext.getAttribute("rsCommon");
      if (rsCommon == null) {
        rsCommon = new weaver.conn.RecordSet();
        pageContext.setAttribute("rsCommon", rsCommon);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      weaver.page.element.ElementUtil ec;
      ec = (weaver.page.element.ElementUtil) pageContext.getAttribute("ec");
      if (ec == null) {
        ec = new weaver.page.element.ElementUtil();
        pageContext.setAttribute("ec", ec);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      weaver.page.PageUtil pu;
      pu = (weaver.page.PageUtil) pageContext.getAttribute("pu");
      if (pu == null) {
        pu = new weaver.page.PageUtil();
        pageContext.setAttribute("pu", pu);
      }
      out.write(_jsp_string3, 0, _jsp_string3.length);
      
	
	response.setHeader("cache-control", "no-cache");
	response.setHeader("pragma", "no-cache");
	response.setHeader("expires", "Mon 1 Jan 1990 00:00:00 GMT");
	

	User user = HrmUserVarify.getUser (request , response) ;
	if(user == null)  return ;
	Log logger= LogFactory.getLog(this.getClass());
	String isIE = (String)session.getAttribute("browser_isie");

      out.write(_jsp_string1, 0, _jsp_string1.length);
      
	 /*
	 \u57fa\u672c\u4fe1\u606f
	 --------------------------------------
	 hpid:\u8868\u9996\u9875ID
	 subCompanyId:\u9996\u9875\u6240\u5c5e\u5206\u90e8\u7684\u5206\u90e8ID
	 eid:\u5143\u7d20ID
	 ebaseid:\u57fa\u672c\u5143\u7d20ID
	 styleid:\u6837\u5f0fID
	 
	 \u6761\u4ef6\u4fe1\u606f
	 --------------------------------------
	 String strsqlwhere \u683c\u5f0f\u4e3a \u6761\u4ef61^,^\u6761\u4ef62...
	 int perpage  \u663e\u793a\u9875\u6570
	 String linkmode \u67e5\u770b\u65b9\u5f0f  1:\u5f53\u524d\u9875 2:\u5f39\u51fa\u9875

	 
	 \u5b57\u6bb5\u4fe1\u606f
	 --------------------------------------
	 fieldIdList
	 fieldColumnList
	 fieldIsDate
	 fieldTransMethodList
	 fieldWidthList
	 linkurlList
	 valuecolumnList
	 isLimitLengthList

	 \u6837\u5f0f\u4fe1\u606f
	 ----------------------------------------
	 String hpsb.getEsymbol() \u5217\u9996\u56fe\u6807
	 String hpsb.getEsparatorimg()   \u884c\u5206\u9694\u7ebf 
	 */

      out.write(_jsp_string1, 0, _jsp_string1.length);
      
	String hpid = Util.null2String(request.getParameter("hpid"));
	int subCompanyId = Util.getIntValue(request
			.getParameter("subCompanyId"), -1);
	String eid = Util.null2String(request.getParameter("eid"));
	String ebaseid = Util.null2String(request.getParameter("ebaseid"));
	String styleid = Util.null2String(request.getParameter("styleid"));
	int perpage = 0;
	int userid = pu.getHpUserId(hpid, "" + subCompanyId, user);
	int usertype = pu.getHpUserType(hpid, "" + subCompanyId, user);
	if(Util.getIntValue(hpid)<0) {//\u534f\u540c\u7684 userid  \u548c usertype \u4e3a 1  \u548c 0
		userid = 1;
		usertype = 0;
	}
	//\u5224\u65ad\u5f53\u524d\u7528\u6237\u662f\u5426\u6709\u6743\u9650\u67e5\u770b\u8be5\u5143\u7d20
	
	boolean hasRight =true;
	User loginuser = (User)request.getSession(true).getAttribute("weaver_user@bean") ;
	// \u5148\u53d6\u6d88\u6743\u9650\u5224\u65ad
	if(loginuser != null)  {
		hasRight =  ec.isHasRight(eid,loginuser.getUID()+"",0,1);
	}
	if(!hasRight){
		response.sendRedirect("/page/element/noright.jsp");
	}
	//HomepageStyleBean hpsb = hpsu.getHpsb(styleid);

	//\u5f97\u5230\u9700\u8981\u663e\u793a\u7684\u5b57\u6bb5
	ArrayList fieldIdList = new ArrayList();
	ArrayList fieldColumnList = new ArrayList();
	ArrayList fieldIsDate = new ArrayList();
	ArrayList fieldTransMethodList = new ArrayList();
	ArrayList fieldWidthList = new ArrayList();
	ArrayList linkurlList = new ArrayList();
	ArrayList valuecolumnList = new ArrayList();
	ArrayList isLimitLengthList = new ArrayList();

	
	rsCommon.executeSql("select 1 from hpinfo where id="+hpid+" and isLocked=1");
	if (rsCommon.next()) {
		rsCommon.executeSql("select creatorid,creatortype from hpinfo where id="+hpid);
		if(rsCommon.next())
		{
			userid =Util.getIntValue(rsCommon.getString("creatorid"));
			usertype = Util.getIntValue(rsCommon.getString("creatortype"));
		}
	}

	String fields = "";
	String linkmode = "";
	String currenttab="";
	String isremind = "";

	String strsqlwhere = hpec.getStrsqlwhere(eid);
	
	String strSql = "select perpage,linkmode,showfield,isremind from hpElementSettingDetail where eid="
			+ eid
			+ " and usertype="
			+ usertype;
	//\u6392\u9664\u975e\u534f\u540c
	//if(Util.getIntValue(hpid)>0)
		strSql+= " and userid="+ userid;
	rsCommon.executeSql(strSql);
	//System.out.println("Common.jsp strSql====>"+strSql);
	if (rsCommon.next()) {
		fields = Util.null2String(rsCommon.getString("showfield"));
		perpage = Util.getIntValue(rsCommon.getString("perpage"));
		linkmode = Util.null2String(rsCommon.getString("linkmode"));
		isremind= Util.null2String(rsCommon.getString("isremind"));
	} else {
		//\u7528\u4e8e\u5143\u7d20\u72ec\u7acb\u663e\u793a\u5224\u65ad\uff0c\u82e5\u4e2a\u4eba\u914d\u7f6e\u4e0d\u5b58\u5728\uff0c\u8bfb\u53d6\u7ba1\u7406\u5458\u6570\u636e\u3002
		if ("true".equals(Util.null2String(request.getParameter("indie"), "false"))) {
			strSql = "select perpage,linkmode,showfield,isremind from hpElementSettingDetail where eid="
				+ eid
				+ " and usertype=3";
		}
		rsCommon.executeSql(strSql);
		if (rsCommon.next()) {
			fields = Util.null2String(rsCommon.getString("showfield"));
			perpage = Util.getIntValue(rsCommon.getString("perpage"));
			linkmode = Util.null2String(rsCommon.getString("linkmode"));
			isremind= Util.null2String(rsCommon.getString("isremind"));
		}
	}
	boolean needRecordTab = true;
	strSql="select isremembertab  from PageUserDefault where userid="+user.getUID();
	rsCommon.executeSql(strSql);
	if(rsCommon.next()){
		needRecordTab = !"0".equals(rsCommon.getString("isremembertab"));
	}
	String strsql2 = null;
	if(needRecordTab){//\u53ea\u6709\u5f00\u542f\u4e86\u8bb0\u5f55\u6700\u540e\u9009\u4e2d\u53f6\u7b7e\uff0c\u624d\u9700\u8981\u67e5\u8be5\u6570\u636e
		strsql2 = "select currenttab from hpcurrenttab where eid="+eid
		+ " and usertype="
		+ user.getType();
		//\u6392\u9664\u975e\u534f\u540c
		//if(Util.getIntValue(hpid)>0)
			strsql2+= " and userid="+ user.getUID();
		rsCommon.execute(strsql2);
		
		if(rsCommon.next()){
			currenttab = Util.null2String(rsCommon.getString("currenttab"));
		}else{
			rsCommon.execute("insert into hpcurrenttab (currenttab,eid,userid,usertype) values ( null,"+eid+","+user.getUID()+","+user.getType()+")");
		}
	}
	
	
	if (!"".equals(fields)) {
		ArrayList tempFieldList = Util.TokenizerString(fields, ",");
		for (int i = 0; i < tempFieldList.size(); i++) {
			String tempId = (String) tempFieldList.get(i);
			fieldIdList.add(tempId);
			fieldColumnList.add(hpefc.getFieldcolumn(tempId));
			fieldIsDate.add(hpefc.getIsdate(tempId));
			fieldTransMethodList.add(hpefc.getTransmethod(tempId));
			fieldWidthList.add(hpefc.getFieldWidth(tempId));
			linkurlList.add(hpefc.getLinkurl(tempId));
			valuecolumnList.add(hpefc.getValuecolumn(tempId));
			isLimitLengthList.add(hpefc.getIsLimitLength(tempId));
		}
	}
	String isFixationRowHeight="0";
	String background="";
	strSql = "select isFixationRowHeight,background from hpelement where id="+ eid;
	rsCommon.executeSql(strSql);
	if (rsCommon.next()) {
		isFixationRowHeight = Util.null2String(rsCommon.getString("isFixationRowHeight"));
		background = Util.null2String(rsCommon.getString("background"));
	}
	
	String eStyleid=hpec.getStyleid(eid);
	
	String pagetype = Util.null2String(request.getParameter("pagetype"), "");
	String fieldids = Util.null2String(request.getParameter("fieldids"), "");
	String fieldvalues = Util.null2String(request.getParameter("fieldvalues"), "");

      out.write(_jsp_string1, 0, _jsp_string1.length);
      weaver.conn.RecordSet rs;
      rs = (weaver.conn.RecordSet) pageContext.getAttribute("rs");
      if (rs == null) {
        rs = new weaver.conn.RecordSet();
        pageContext.setAttribute("rs", rs);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      weaver.docs.news.DocNewsManager dnm;
      dnm = (weaver.docs.news.DocNewsManager) pageContext.getAttribute("dnm");
      if (dnm == null) {
        dnm = new weaver.docs.news.DocNewsManager();
        pageContext.setAttribute("dnm", dnm);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      weaver.docs.docs.DocManager dm;
      dm = (weaver.docs.docs.DocManager) pageContext.getAttribute("dm");
      if (dm == null) {
        dm = new weaver.docs.docs.DocManager();
        pageContext.setAttribute("dm", dm);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      weaver.docs.docs.DocComInfo dc;
      dc = (weaver.docs.docs.DocComInfo) pageContext.getAttribute("dc");
      if (dc == null) {
        dc = new weaver.docs.docs.DocComInfo();
        pageContext.setAttribute("dc", dc);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      weaver.synergy.SynergyOperatDoc sod;
      sod = (weaver.synergy.SynergyOperatDoc) pageContext.getAttribute("sod");
      if (sod == null) {
        sod = new weaver.synergy.SynergyOperatDoc();
        pageContext.setAttribute("sod", sod);
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      
		/*
		\u57fa\u672c\u4fe1\u606f
		--------------------------------------
		hpid:\u8868\u9996\u9875ID
		subCompanyId:\u9996\u9875\u6240\u5c5e\u5206\u90e8\u7684\u5206\u90e8ID
		eid:\u5143\u7d20ID
		ebaseid:\u57fa\u672c\u5143\u7d20ID
		styleid:\u6837\u5f0fID
		
		\u6761\u4ef6\u4fe1\u606f
		--------------------------------------
		String strsqlwhere \u683c\u5f0f\u4e3a \u6761\u4ef61^,^\u6761\u4ef62...
		int perpage  \u663e\u793a\u9875\u6570
		String linkmode \u67e5\u770b\u65b9\u5f0f  1:\u5f53\u524d\u9875 2:\u5f39\u51fa\u9875

		
		\u5b57\u6bb5\u4fe1\u606f
		--------------------------------------
		fieldIdList
		fieldColumnList
		fieldIsDate
		fieldTransMethodList
		fieldWidthList
		linkurlList
		valuecolumnList
		isLimitLengthList

		\u6837\u5f0f\u4fe1\u606f
		----------------------------------------
		String esc.getIconEsymbol(pc.getStyleid(eid)) \u5217\u9996\u56fe\u6807
		class='sparator' \u884c\u5206\u9694\u7ebf 
	*/

      out.write(_jsp_string2, 0, _jsp_string2.length);
      
String returnStr = "";

//\u66f4\u65b0\u5f53\u524dtab\u4fe1\u606f
String tabid = Util.null2String(request.getParameter("tabId"));
String updateSql = "update  hpcurrenttab set currenttab ='"+tabid+"' where eid="
	+ eid
	+ " and userid="
	+ user.getUID()
	+ " and usertype="
	+ user.getType();
rs.execute(updateSql);

//\u56fe\u7247\u5927\u5c0f
int imgWidth=120;
int imgHeight = 108;
String topDocIds="";//\u7f6e\u9876\u6587\u6863ID
int topDocCount = 0;//\u7f6e\u9876\u6587\u6863\u6570\u76ee
String tabSql="select tabId,tabTitle,sqlWhere from hpNewsTabInfo where eid="+eid+" and tabId="+tabid;
rs.execute(tabSql);
if(rs.next()){
	strsqlwhere = rs.getString("sqlWhere");
}

if(strsqlwhere.indexOf("^topdoc^")!=-1){
	strsqlwhere = Util.StringReplace(strsqlwhere, "^topdoc^","#");
	String[] temp = Util.TokenizerString2(strsqlwhere, "#");
	strsqlwhere = Util.null2String(temp[0]);
	if(temp.length>1){
		topDocIds = Util.null2String(temp[1]);
	}
}
boolean isNewReply = weaver.docs.docs.reply.DocReplyUtil.isUseNewReply();	//\u662f\u5426\u542f\u7528\u65b0\u7684\u6587\u6863\u56de\u590d
// \u5f97\u5230\u65b0\u95fb\u9875ID\u4ee5\u53ca\u76f8\u5173\u7684\u5c55\u73b0\u65b9\u5f0f
if(strsqlwhere.length()<3) return;
if("^,^".equals(strsqlwhere.substring(0,3)))  return ;
try {
	strsqlwhere = Util.StringReplace(strsqlwhere, "^,^","&");
} catch (Exception e) {			
	e.printStackTrace();
}
String srcOpenFirstAccess="0" ;
String[] strsqlwheres = Util.TokenizerString2(strsqlwhere, "&");
String newsId = Util.null2String(strsqlwheres[0]);
int showModeId = Util.getIntValue(strsqlwheres[1]);
if (strsqlwheres.length>3) srcOpenFirstAccess=strsqlwheres[3];
//System.out.println("strsqlwhere:"+strsqlwhere);
//System.out.println("newsId:"+newsId);
String srcType="0";
String srcContent="0";
String srcReply="0";

String newstemplateid="";
String newstemplatetype="";
String imgType="";
String imgSrc="";

rs.execute("select newstemplate,imgtype,imgsrc from hpFieldLength where eid="+eid+" and usertype=3 order by id desc");
if(rs.next()){
	//newstemplateid = Util.null2String(rs.getString("newstemplate"));
	imgType = rs.getString("imgtype");
	imgSrc = rs.getString("imgsrc");
}
rs.execute("select newstemplate from hpElement where id="+eid);
if(rs.next()){
	newstemplateid = Util.null2String(rs.getString("newstemplate"));
}

if(!"".equals(newstemplateid)){
	rs.execute("select templatetype from pagenewstemplate where id="+newstemplateid);
	if(rs.next()){
		newstemplatetype = rs.getString("templatetype"); 
	}else{
		rs.execute("update hpElement set newstemplate = '' where id="+eid);
		newstemplateid = "";
		newstemplatetype = "";
	}
}

ArrayList docSrcList=Util.TokenizerString(""+newsId, "|");
if (docSrcList.size()>0) srcType=(String)docSrcList.get(0);
if (docSrcList.size()>1) srcContent=(String)docSrcList.get(1);
if (docSrcList.size()>2) srcReply=(String)docSrcList.get(2);


if("0".equals(srcContent)) return ;
String strAccess="";
if("1".equals(srcOpenFirstAccess)) strAccess="&isOpenFirstAss=1";
else strAccess="&isOpenFirstAss=0";
		
String rollDirection="";
if(strsqlwheres.length<=2)  rollDirection="None";
else  rollDirection=strsqlwheres[2];

      out.write(_jsp_string4, 0, _jsp_string4.length);
      
String  userid1=""+user.getUID();
String ownerid=userid1;
String strImg="";
ArrayList docIdList=new ArrayList();
ArrayList docsubjectList=new ArrayList();
ArrayList doclastmoddateList=new ArrayList();
ArrayList doclastmodtimeList=new ArrayList();
ArrayList docContentList=new ArrayList();
ArrayList doccreateridList = new ArrayList();
ArrayList readCountList = new ArrayList();
String andSql="";
//String invalidStr = " or docstatus = 7 and  (sharelevel>1" + ((userid1!=null&&!"".equals(userid1))?" or (doccreaterid=" + userid1 + ((ownerid!=null&&!"".equals(ownerid))?" or ownerid=" + ownerid:"") + ")":"") + ") ";
//String strStatus=" and (docstatus='1' or docstatus='2' or docstatus='5' "+invalidStr+")";
String invalidStr = " or (docstatus = 7 and  (sharelevel>1" + ((userid1!=null&&!"".equals(userid1))?" or (doccreaterid=" + userid1 + ((ownerid!=null&&!"".equals(ownerid))?" or ownerid=" + ownerid:"") + ")":"") + ")) ";
String strStatus=" and (((docstatus='1' or docstatus='2' or docstatus='5') and sharelevel>0) "+invalidStr+")";
//\u5728\u534f\u540c\u4e2d\uff0c\u83b7\u53d6\u53c2\u6570\u5e76\u62fc\u63a5\u6761\u4ef6
String newsfrom = "";
if(Util.getIntValue(hpid) < 0)
{
	int docid = Util.getIntValue(request.getParameter("requestid"),-1);
	String syparaSql = sod.getDocAndSql(eid,docid,Util.getIntValue(hpid),user);
	newsfrom = sod.getDocFromSql(eid);
	strStatus += syparaSql;
}
String topDocWhere="";
/**\u6587\u6863\u7f6e\u9876*/
if(!topDocIds.equals("")){
	ArrayList docids=Util.TokenizerString(topDocIds,",");
	String newDocids="";
	 for(int i=0;i<docids.size();i++)	newDocids+=","+(String)docids.get(i);
	if(newDocids.length()>0) newDocids=newDocids.substring(1);
	
	andSql=" and t1.id in("+newDocids+") "+strStatus;
	topDocWhere = " and t1.id  not in("+newDocids+") ";
	//\u5728\u534f\u540c\u4e2d\uff0c\u83b7\u53d6\u53c2\u6570\u5e76\u62fc\u63a5\u6761\u4ef6
	if(Util.getIntValue(hpid) < 0)
	{
		dm.selectNewsDocInfo4Synergy(newsfrom,andSql, user,perpage, 1);
	}else
		dm.selectNewsDocInfo(andSql, user,perpage, 1);
	while (dm.next()) {
		docIdList.add(""+dm.getDocid());
		docsubjectList.add(""+dm.getDocsubject()) ;
		doclastmoddateList.add(""+dm.getDoclastmoddate()) ;
		doclastmodtimeList.add(""+dm.getDoclastmodtime()) ;
		docContentList.add(dm.getDoccontent());
		doccreateridList.add(""+dm.getDoccreaterid());
		readCountList.add(""+dm.getReadCount());
	}
	//topDocCount = docids.size();
	//perpage = perpage-docids.size();
	topDocCount = dm.getCount();
	//perpage = perpage-topDocCount;
	if(perpage<0){
		perpage = 0;
	}
}
strStatus = strStatus+topDocWhere;

if("1".equals(srcType)){//\u65b0\u95fb\u4e2d\u5fc3
	
	String newsclause = "";

	dnm.resetParameter();
	dnm.setId(Util.getIntValue(srcContent));
	dnm.getDocNewsInfoById();
	newsclause = dnm.getNewsclause();
	dnm.closeStatement();

	String newslistclause = newsclause.trim();
	if (!newslistclause.equals("")) 	newslistclause = " and (" + newslistclause+") ";
	andSql = newslistclause	+ "  and (ishistory is null or ishistory = 0)  and docpublishtype in('2','3') "+strStatus;
	//\u5728\u534f\u540c\u4e2d\uff0c\u83b7\u53d6\u53c2\u6570\u5e76\u62fc\u63a5\u6761\u4ef6
	if(Util.getIntValue(hpid) < 0)
	{
		dm.selectNewsDocInfo4Synergy(newsfrom,andSql, user,perpage, 1);
	}else
		dm.selectNewsDocInfo(andSql, user,perpage, 1);
} else if("2".equals(srcType)){  //\u6587\u6863\u76ee\u5f55
	if(",".equals(srcContent.substring(0,1))) srcContent=srcContent.substring(1);
	andSql="  and (ishistory is null or ishistory = 0)  and exists (select id from docseccategory where id = seccategory and id in ("+srcContent+")) "+strStatus;
    if (isNewReply || !"1".equals(srcReply))	andSql+=" and (isreply!=1 or  isreply is null) ";
  //\u5728\u534f\u540c\u4e2d\uff0c\u83b7\u53d6\u53c2\u6570\u5e76\u62fc\u63a5\u6761\u4ef6
	if(Util.getIntValue(hpid) < 0)
	{
		dm.selectNewsDocInfo4Synergy(newsfrom,andSql, user,perpage, 1);
	}else
		dm.selectNewsDocInfo(andSql, user,perpage, 1);
		
} else if("3".equals(srcType)){  //\u865a\u62df\u76ee\u5f55	
	andSql=" and (ishistory is null or ishistory = 0)  "+strStatus;
	if (isNewReply || !"1".equals(srcReply) )	andSql+=" and (isreply!=1 or  isreply is null)";
	//dm.selectNewsDocInfo(andSql, user,perpage, 1,srcContent);
	//\u5728\u534f\u540c\u4e2d\uff0c\u83b7\u53d6\u53c2\u6570\u5e76\u62fc\u63a5\u6761\u4ef6
	if(Util.getIntValue(hpid) < 0)
	{
		dm.selectNewsDocInfoForHpSynergy(newsfrom,andSql, user,perpage, 1,srcContent);
	}else
		dm.selectNewsDocInfoForHp(andSql, user,perpage, 1,srcContent);

} else if("4".equals(srcType)){ //\u6307\u5b9a\u6587\u6863
	ArrayList docids=Util.TokenizerString(srcContent,",");
	String newDocids="";
    for(int i=0;i<docids.size();i++)	newDocids+=","+dm.getNewDocid((String)docids.get(i));
	if(newDocids.length()>0) newDocids=newDocids.substring(1);
	
	andSql=" and id in("+newDocids+") "+strStatus;
	//\u5728\u534f\u540c\u4e2d\uff0c\u83b7\u53d6\u53c2\u6570\u5e76\u62fc\u63a5\u6761\u4ef6
	if(Util.getIntValue(hpid) < 0)
	{
		dm.selectNewsDocInfo4Synergy(newsfrom,andSql, user,perpage, 1);
	}else
		dm.selectNewsDocInfo(andSql, user,perpage, 1);

}else if("5".equals(srcType)){ //\u641c\u7d22\u6a21\u677f

}else if("6".equals(srcType)){ //\u641c\u7d22\u6761\u4ef6
//\u9884\u7559
}

//\u5f97\u5230\u53bb\u6389top\u7684\u51e0\u6761\u6570\u636e\uff0c\u4f59\u4e0b\u7684\u663e\u793a\u7684\u6761\u6570
int temp_perpage=perpage-topDocCount;
int temp_js=0;
while (dm.next()) {
	//System.out.println(topDocIds+"\u6587\u6863\u7684id"+dm.getDocid());
	//\u6392\u9664\u91cd\u590d\u7684\u6587\u6863\u7684id
	if((","+topDocIds+",").indexOf(","+dm.getDocid()+",")==-1&&temp_js<temp_perpage){
		temp_js++;
		docIdList.add(""+dm.getDocid());
		docsubjectList.add(""+dm.getDocsubject()) ;
		doclastmoddateList.add(""+dm.getDoclastmoddate()) ;
		doclastmodtimeList.add(""+dm.getDoclastmodtime()) ;
		docContentList.add(dm.getDoccontent());
		doccreateridList.add(""+dm.getDoccreaterid());
		readCountList.add(""+dm.getReadCount());
	}
}

int index = fieldColumnList.indexOf("img");

if(index!=-1){
	String imgfieldId = (String)fieldIdList.get(index);
	String sql = "";
	
	if(hpc.getIsLocked(hpid).equals("1")) {
		sql="select imgsize from hpFieldLength where eid="+ eid + " and efieldid=" + imgfieldId+"" +" and userid="+hpc.getCreatorid(hpid)+" and usertype="+hpc.getCreatortype(hpid);
	}else{
    	sql="select imgsize from hpFieldLength where eid="+ eid + " and efieldid=" + imgfieldId+"" +" and userid="+hpu.getHpUserId(hpid,""+subCompanyId,user)+" and usertype="+hpu.getHpUserType(hpid,""+subCompanyId,user);
	}

    rs.execute(sql);
    if (rs.next()){
	String imgSize = Util.null2String(rs.getString("imgsize"));
	
	if(!"".equals(imgSize)){
		ArrayList imgSizeAry = Util.TokenizerString(imgSize,"*");
		imgWidth = Util.getIntValue((String)imgSizeAry.get(0),imgWidth);
		imgHeight = Util.getIntValue((String)imgSizeAry.get(1),imgHeight);
	}
    }
    
}

if(showModeId == 4){
	strImg="";
	if(imgType.equals("0")||imgType.equals("")){
		if (fieldColumnList.contains("img")) {
	strImg = hpes.getImgPlay(request,docIdList,docContentList,imgWidth,imgHeight,hpec.getStyleid(eid),eid);
		}
	}else{
		strImg = "<img src="+imgSrc+" height = "+imgHeight+" width="+imgWidth+" />";
	}
	returnStr +="<table width=\"100%\"  cellPadding='0' cellSpacing='0'><tr><td valign=\"top\"><table style='margin-top:6px' cellPadding='0' cellSpacing='0'><tr><TD  height=\"112\" valign=\"top\">"+strImg+"</TD></tr></table></td>\n";
	returnStr +="<td width=1px>&nbsp;</td><td width=\"100%\" valign=\"top\">" ;
}
returnStr += "<TABLE class='elementdatatable'  width=\"100%\"";
//System.out.println("showModeId:"+showModeId);
if (showModeId == 3 || showModeId == 2 ){ //\u5de6\u56fe\u5f0f or \u4e0a\u56fe\u5f0f or \u591a\u56fe\u5f0f
	returnStr += " cellPadding='0' cellSpacing='0' >\n";
} else {
	returnStr += " >\n";
}
int rowcount=0;
String imgSymbol="";
if (!"".equals(esc.getIconEsymbol(hpec.getStyleid(eid)))) imgSymbol="<img name='esymbol' src='"+esc.getIconEsymbol(hpec.getStyleid(eid))+"'>";

String docshowlink = "";//\u6587\u6863\u6253\u5f00\u65b9\u5f0f
if("".equals(newstemplateid)){//\u9ed8\u8ba4\u6587\u6863\u663e\u793a\u9875\u9762
	docshowlink= "/docs/docs/DocDsp.jsp?id=";
}else{//\u6587\u6863\u663e\u793a\u6a21\u7248
	docshowlink = "/page/maint/template/news/newstemplate.jsp?templatetype="+newstemplatetype+"&templateid="+newstemplateid+"&docid=";
}


      out.write(_jsp_string5, 0, _jsp_string5.length);
      
int height = docIdList.size()*23;
	int tabsize = Util.getIntValue(request.getParameter("tabsize"),1);
	int eHeight=Util.getIntValue(hpec.getHeight(eid),0);

	if(eHeight>0&&height<eHeight){
		if(tabsize>1){
			height = eHeight-36;
		}else{
			height = eHeight-4;
		}
	}
if("Up".equals(rollDirection)||"Down".equals(rollDirection)) {
	if((showModeId==2||showModeId==3||showModeId==4)&&height<156) height = 156;
	out.println("<MARQUEE DIRECTION="+rollDirection.toLowerCase()+"  id=\"webjx_"+eid+"\" onmouseover=\"webjx_"+eid+".stop()\" onmouseout=\"webjx_"+eid+".start()\"  SCROLLDELAY=200 height="+height+">");
}else if("Left".equals(rollDirection)||"Right".equals(rollDirection)) {
	out.println("<MARQUEE DIRECTION="+rollDirection.toLowerCase()+"  id=\"webjx_"+eid+"\" onmouseover=\"webjx_"+eid+".stop()\" onmouseout=\"webjx_"+eid+".start()\"  SCROLLDELAY=200>");
}

      out.write(_jsp_string6, 0, _jsp_string6.length);
      out.print((eid));
      out.write(_jsp_string7, 0, _jsp_string7.length);
      
		 
for (int i=0;i<docIdList.size();i++) {
	int docid = Util.getIntValue((String)docIdList.get(i));
	String docId=(String)docIdList.get(i);
	String docsubject = (String)docsubjectList.get(i);
	String doccontent = (String)docContentList.get(i);
	String doclastmoddate =  (String)doclastmoddateList.get(i);
	String doclastmodtime =  (String)doclastmodtimeList.get(i);
	String doccreaterid = (String)doccreateridList.get(i);
	int readCount = Util.getIntValue((String)readCountList.get(i),0);

	//
	
	
	if(showModeId==5){
		if(i%2==0){
	returnStr+="<tr>";
	
		}
		returnStr += "	<TD width=\"8\">"+imgSymbol+"</TD>\n";
		//returnStr+=""
	}else{
		returnStr += "<TR>\n";
	}

	if(showModeId == 1||showModeId == 4){
		
		returnStr += "	<TD width=\"8\">"+imgSymbol+"</TD>\n";
	}
	int size = fieldIdList.size();
	if (fieldColumnList.contains("img")) {
		size--;
	}
	 boolean isOnlyImg = false;
	for (int j = 0; j <  fieldIdList.size(); j++) {
		String fieldId = (String) fieldIdList.get(j);
		String columnName = (String) fieldColumnList.get(j);
		String strIsDate = (String) fieldIsDate.get(j);
		String fieldwidth = (String) fieldWidthList.get(j);
		String isLimitLength = (String) isLimitLengthList.get(j);

		String cloumnValue = docsubject;
		String titleValue = cloumnValue;
		
		if (showModeId == 1 || showModeId == 4||showModeId==5) {// \u5217\u8868\u5f0f
	
			//todo
	 if ("docdocsubject".equals(columnName)) {
		int wordLength = 8;
		//if ("1".equals(isLimitLength))
			//cloumnValue = hpu.getLimitStr(eid, fieldId,cloumnValue,user,hpid,subCompanyId);

			String imgNew="<IMG id='doclist_"+docId+"img' src='/images/ecology8/statusicon/BDNew_wev8.png' title='"+SystemEnv.getHtmlLabelName(18441,user.getLanguage())+"' class='wfremindimg' border=0 align='absbottom'>";
			if(i<topDocCount){
		imgNew="<IMG src='/images/BDTop_wev8.gif' border=0 align='absbottom'>";
			}else if(!dc.getIsNewDoc(docId, user.getLogintype(), ""+user.getUID(),doccreaterid,readCount)){ 
		imgNew="";
			}

		String showValue = "";
		
		if ("1".equals(linkmode)) {
			showValue = "<a class='ellipsis'  href='"+docshowlink
			+ docid+strAccess
			+ "' target='_self'>"
			+ "<font class='font docnamedetail'>"+cloumnValue+"</font>" + "</a>\n";
		} else {
			showValue = "<a class='ellipsis'  href=\"javascript:openFullWindowForDoc('"+docshowlink
			+ docid+strAccess
			+ "','"+docid+"')\">"
			+ "<font class='font docnamedetail' >"+cloumnValue+"</font>"
			+ "</a>\n";
		}
		
		returnStr += "<td class='docdetail' width='" + fieldwidth
		+ "' title='" + titleValue + "'>"
		+ showValue +imgNew+ "</td>\n";
	}else if("summary".equals(columnName)){
		String newTitle = cloumnValue;
			//hpu.getLimitStr(eid, fieldId,
			//	cloumnValue,user,hpid,subCompanyId);
		String strmemo = "";
		int tmppos = doccontent.indexOf("!@#$%^&*");
		if (tmppos != -1) strmemo = doccontent.substring(0, tmppos);
		
		if (!fieldColumnList.contains("docdocsubject")){
			newTitle = "";
		} else {
			int tempPos=fieldColumnList.indexOf("docdocsubject");
			String tempFiledId=(String)fieldIdList.get(tempPos);
			//newTitle = hpu.getLimitStr(eid, tempFiledId,newTitle,user,hpid,subCompanyId);

			String imgNew="<IMG id='doclist_"+docId+"img' src='/images/ecology8/statusicon/BDNew_wev8.png' title='"+SystemEnv.getHtmlLabelName(18441,user.getLanguage())+"' class='wfremindimg' border=0 align='absbottom'>";
			if(i<topDocCount){
				imgNew="<IMG src='/images/BDTop_wev8.gif' border=0 align='absbottom'>";
			}else if(!dc.getIsNewDoc(docId, user.getLogintype(), ""+user.getUID(),doccreaterid,readCount)){ 
				imgNew="";
			}
			
			if ("1".equals(linkmode)) {
				newTitle = "<a class='ellipsis'  href='"+docshowlink+ docid+strAccess+ "' target='_self'>"+"<font class=font>"+newTitle+"</font>" +imgNew+ "</a>\n";
			} else {
				newTitle = "<a  class='ellipsis'  href=\"javascript:openFullWindowForDoc('"+docshowlink+ docid+strAccess+ "','"+docid+"')\">"+ "<font class=font>"+newTitle+"</font>" +imgNew+ "</a>\n";
			}
		}
		if (!fieldColumnList.contains("doclastmoddate"))
			doclastmoddate = "";
		if (!fieldColumnList.contains("doclastmodtime"))
			doclastmodtime = "";
		if (!fieldColumnList.contains("summary")){
			strmemo = "";
		} else {			
			int tempPos=fieldColumnList.indexOf("summary");
			String tempFiledId=(String)fieldIdList.get(tempPos);			
			
			//strmemo = hpu.getLimitStr(eid, tempFiledId,strmemo,user,hpid,subCompanyId);
			if ("1".equals(linkmode)) {
				strmemo = "<a class='ellipsis'  href='"+docshowlink+ docid+ strAccess+"' target='_self'><font class=font>"+ strmemo + "</font></a>\n";
			} else {
				strmemo = "<a class='ellipsis'  href=\"javascript:openFullWindowForXtable('"+docshowlink+docid+strAccess+ "')\"><font class=font> "+ strmemo+ "</font></a>\n";
			}
		}
		returnStr += "<td  width='" + fieldwidth + "'>"
		+ "<font class=font>"+strmemo+"</font>" + "</td>\n";
		
	} else if ("doclastmoddate".equals(columnName)) {
		returnStr += "<td  width='" + fieldwidth + "'>"
		+ "<font class=font>"+doclastmoddate+"</font>" + "</td>\n";
	} else if ("doclastmodtime".equals(columnName)) {
		returnStr += "<td  width='" + fieldwidth + "'>"
		+ "<font class=font>"+doclastmodtime+"</font>" + "</td>\n";
	}
		 	
		} else {

	String newTitle =cloumnValue;
	//hpu.getLimitStr(eid, fieldId,
	//		cloumnValue,user,hpid,subCompanyId);
	String strmemo = "";
	int tmppos = doccontent.indexOf("!@#$%^&*");
	if (tmppos != -1) strmemo = doccontent.substring(0, tmppos);
	
	if (!fieldColumnList.contains("docdocsubject")){
		newTitle = "";
	} else {
		int tempPos=fieldColumnList.indexOf("docdocsubject");
		String tempFiledId=(String)fieldIdList.get(tempPos);
		//newTitle = hpu.getLimitStr(eid, tempFiledId,newTitle,user,hpid,subCompanyId);

		String imgNew="<IMG id='doclist_"+docId+"img' src='/images/ecology8/statusicon/BDNew_wev8.png' title='"+SystemEnv.getHtmlLabelName(18441,user.getLanguage())+"'  class='wfremindimg' border=0 align='absbottom'>";
		if(i<topDocCount){
			imgNew="<IMG src='/images/BDTop_wev8.gif'  border=0 align='absbottom'>";
		}else if(!dc.getIsNewDoc(docId, user.getLogintype(), ""+user.getUID(),doccreaterid,readCount)){ 
			imgNew="";
		}
		
		if ("1".equals(linkmode)) {
			newTitle = "<a class='ellipsis'  href='"+docshowlink+ docid+strAccess+ "' target='_self'>"+"<font class=font>"+newTitle+"</font>" +imgNew+ "</a>\n";
		} else {
			newTitle = "<a class='ellipsis'  href=\"javascript:openFullWindowForDoc('"+docshowlink+ docid+strAccess+ "','"+docid+"')\">"+ "<font class=font>"+newTitle+"</font>" +imgNew+ "</a>\n";
		}
	}
	if (!fieldColumnList.contains("doclastmoddate"))
		doclastmoddate = "";
	if (!fieldColumnList.contains("doclastmodtime"))
		doclastmodtime = "";
	if (!fieldColumnList.contains("summary")){
		strmemo = "";
	} else {			
		int tempPos=fieldColumnList.indexOf("summary");
		String tempFiledId=(String)fieldIdList.get(tempPos);			
		
		//strmemo = hpu.getLimitStr(eid, tempFiledId,strmemo,user,hpid,subCompanyId);
		if ("1".equals(linkmode)) {
			strmemo = "<a class='ellipsis'  href='"+docshowlink+ docid+ strAccess+"' target='_self'><font class=font>"+ strmemo + "</font></a>\n";
		} else {
			strmemo = "<a class='ellipsis'  href=\"javascript:openFullWindowForXtable('"+docshowlink+docid+strAccess+ "')\"><font class=font> "+ strmemo+ "</font></a>\n";
		}
	}
	if(perpage!=1) size=size - 1;
	if (showModeId == 2) { // \u4e0a\u56fe\u5f0f
		 //\u5f97\u5230\u56fe\u7247\u64ad\u653e
		
		if(imgType.equals("0")||imgType.equals("")){
			if (fieldColumnList.contains("img")) {
		strImg = hpes.getImgPlay(request,docId,doccontent,imgWidth,imgHeight,hpec.getStyleid(eid),eid);
			}
		}else{
			strImg = "<img src="+imgSrc+" height = "+imgHeight+" width="+imgWidth+" />";
		}
		if("".equals(newTitle )) imgSymbol="";
		returnStr += "<TD colspan=" + size+ " valign=top align=center>"+
				"<TABLE valign=top align=center cellPadding='0' cellSpacing='0'>" +
				"	<TR><TD  valign=top align=center>" + strImg+ "</TD></TR>" +
				"	<TR><TD  align=center>"+imgSymbol+ newTitle+ "</TD></TR>" +
				"	<TR><TD valign=top  align=center>" + strmemo+"</TD></TR>";
		if(!"".equals(doclastmoddate)||!"".equals(doclastmodtime))			
			returnStr+= "<TR><TD valign=top  align=center>" + "<font class=font>"+doclastmoddate + "&nbsp;"+ doclastmodtime+"</font>"+"</TD></TR>";
		returnStr+= "</TABLE></TD>";
		break;
	} else if (showModeId == 3){ // \u5de6\u56fe\u5f0f
		  //\u5f97\u5230\u56fe\u7247\u64ad\u653e
		strImg="";
	
		if(imgType.equals("0")||imgType.equals("")){
			if (fieldColumnList.contains("img")) {
		strImg = hpes.getImgPlay(request,docId,doccontent,imgWidth,imgHeight,hpec.getStyleid(eid),eid);
			}
		}else{
			strImg = "<img src="+imgSrc+" height = "+imgHeight+" width="+imgWidth+" />";
		}
		
		if("".equals(newTitle )) imgSymbol="";
		returnStr += "<TD colspan=" + size+ ">"+
			   "<TABLE   width='100%'>" + 
			   "<TR>" + 
			   "	<TD  rowspan=4 align=left valign=top>"+ strImg + "</TD>" +
			   "	<TD  width='100%'  valign=top>"+
				"		<table width='100%'   valign=top>"+
			   "		<tr>"+
				"	<td>"+imgSymbol+ newTitle+ "</td>"+
			   "		</tr>"+
			   "		<tr height=1px class='sparator' style='height:1px'>"+
				"	<td style='padding:0px'></td>"+
			   "		</tr>"+
			   "		<tr>"+
				"	<td>"+ strmemo+"</td>"+
			   "		</tr>";
			   
	    if(!"".equals(doclastmoddate)||!"".equals(doclastmodtime))	
			returnStr += "<tr><td>"+ "<font class=font>"+doclastmoddate+ "&nbsp;" + doclastmodtime+"</font>"+"</td></tr>" ;
		returnStr += "</table></TD></TR></TABLE></TD>";
		break;
	}
	
		}
		
	}
	if(showModeId==5){
		
		if(i==docIdList.size()-1){
	returnStr+="</tr>";
		}else{
	if(i%2==1){
		returnStr+="</tr>";
		returnStr += "<TR class='sparator' style='height:1px' height=1px><td style='padding:0px' colspan=" + (size + 1)*2
		+ "></td></TR>\n";	
	}else{
		//returnStr+="</tr>";
	}
		}
	}else{
		returnStr += "</TR>\n";
		rowcount++;
		if(perpage!=1&&rowcount<perpage+topDocCount)
	returnStr += "<TR class='sparator' style='height:1px' height=1px><td style='padding:0px' colspan=" + ((showModeId==2 || showModeId==3)?size:(size + 1))
		+ "></td></TR>\n";	//\u4e0a\u56fe\u5f0f \u5de6\u56fe\u5f0f\u6ca1\u6709\u5c0f\u5706\u70b9\u5217 \u8de8\u5217\u4e0d\u52a01
	}
	//returnStr += "</TR>\n";
		
}
returnStr += "</TABLE>\n";
if(showModeId == 4) {
		  returnStr +="     </td></tr></table>\n";
}
if(showModeId == 4) {
	if(fieldColumnList.size()==1&&fieldColumnList.indexOf("img")!=-1){
		returnStr = strImg;
	}
}
out.println(returnStr);

      out.write(_jsp_string8, 0, _jsp_string8.length);
      
if("Left".equals(rollDirection)||"Right".equals(rollDirection)||"Up".equals(rollDirection)||"Down".equals(rollDirection)) out.println("</MARQUEE>");

      out.write(_jsp_string9, 0, _jsp_string9.length);
      out.print((isremind));
      out.write(_jsp_string10, 0, _jsp_string10.length);
      out.print((eid));
      out.write(_jsp_string11, 0, _jsp_string11.length);
      if(showModeId == 2 ||showModeId == 3 ){
				for (int i=0;i<docIdList.size();i++) {
					String outEid = eid+"_"+Util.null2String(docIdList.get(i));
				
      out.write(_jsp_string12, 0, _jsp_string12.length);
      out.print((outEid));
      out.write(_jsp_string13, 0, _jsp_string13.length);
      out.print((outEid));
      out.write(_jsp_string14, 0, _jsp_string14.length);
      out.print((outEid));
      out.write(_jsp_string15, 0, _jsp_string15.length);
      out.print((outEid));
      out.write(_jsp_string16, 0, _jsp_string16.length);
      out.print((outEid));
      out.write(_jsp_string17, 0, _jsp_string17.length);
      out.print((outEid));
      out.write(_jsp_string18, 0, _jsp_string18.length);
      out.print((outEid));
      out.write(_jsp_string19, 0, _jsp_string19.length);
      out.print((outEid));
      out.write(_jsp_string20, 0, _jsp_string20.length);
      out.print((outEid));
      out.write(_jsp_string21, 0, _jsp_string21.length);
      out.print((outEid));
      out.write(_jsp_string22, 0, _jsp_string22.length);
      }
		}else if(showModeId == 4){
				String outEid = eid+"_";
				
      out.write(_jsp_string12, 0, _jsp_string12.length);
      out.print((outEid));
      out.write(_jsp_string13, 0, _jsp_string13.length);
      out.print((outEid));
      out.write(_jsp_string14, 0, _jsp_string14.length);
      out.print((outEid));
      out.write(_jsp_string15, 0, _jsp_string15.length);
      out.print((outEid));
      out.write(_jsp_string16, 0, _jsp_string16.length);
      out.print((outEid));
      out.write(_jsp_string17, 0, _jsp_string17.length);
      out.print((outEid));
      out.write(_jsp_string18, 0, _jsp_string18.length);
      out.print((outEid));
      out.write(_jsp_string19, 0, _jsp_string19.length);
      out.print((outEid));
      out.write(_jsp_string20, 0, _jsp_string20.length);
      out.print((outEid));
      out.write(_jsp_string21, 0, _jsp_string21.length);
      out.print((outEid));
      out.write(_jsp_string22, 0, _jsp_string22.length);
      }
      out.write(_jsp_string23, 0, _jsp_string23.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 1886798272571451039L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("page/element/compatible/NewsTabContentData.jsp"), 224759418508515145L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("homepage/element/content/Common.jsp"), 5648407096738041053L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("page/maint/common/initNoCache.jsp"), 3270256153856711871L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string21;
  private final static char []_jsp_string23;
  private final static char []_jsp_string9;
  private final static char []_jsp_string5;
  private final static char []_jsp_string15;
  private final static char []_jsp_string7;
  private final static char []_jsp_string14;
  private final static char []_jsp_string13;
  private final static char []_jsp_string17;
  private final static char []_jsp_string0;
  private final static char []_jsp_string22;
  private final static char []_jsp_string8;
  private final static char []_jsp_string4;
  private final static char []_jsp_string16;
  private final static char []_jsp_string19;
  private final static char []_jsp_string12;
  private final static char []_jsp_string6;
  private final static char []_jsp_string3;
  private final static char []_jsp_string1;
  private final static char []_jsp_string10;
  private final static char []_jsp_string11;
  private final static char []_jsp_string18;
  private final static char []_jsp_string20;
  private final static char []_jsp_string2;
  static {
    _jsp_string21 = " = setInterval(function(){showAuto('".toCharArray();
    _jsp_string23 = "\r\n\r\n	});\r\n</script>".toCharArray();
    _jsp_string9 = "\r\n\r\n<script>\r\n    //\u5904\u7406\r\n	var isremind='".toCharArray();
    _jsp_string5 = "\r\n\r\n	\r\n	".toCharArray();
    _jsp_string15 = "=null;\r\n				}\r\n				initDocPicSlide('".toCharArray();
    _jsp_string7 = "\" class=Econtent  width=100%>\r\n   <TR>\r\n	 <TD width=1px></TD>\r\n	 <TD width='*' valign=\"top\">\r\n	 \r\n	 ".toCharArray();
    _jsp_string14 = "=null;\r\n				}\r\n				catch (e) {\r\n					t_".toCharArray();
    _jsp_string13 = ");\r\n					t_".toCharArray();
    _jsp_string17 = "=setInterval(function(){showAuto('".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string22 = "')}, 2000);\r\n				});\r\n		".toCharArray();
    _jsp_string8 = "\r\n	</table>\r\n	</TD>    \r\n	<TD width=1px></TD>\r\n  </TR>\r\n</TABLE>\r\n".toCharArray();
    _jsp_string4 = "\r\n\r\n\r\n".toCharArray();
    _jsp_string16 = "');\r\n				t_".toCharArray();
    _jsp_string19 = "\").hover(function() {\r\n					clearInterval(t_".toCharArray();
    _jsp_string12 = "\r\n				try {\r\n					clearInterval(t_".toCharArray();
    _jsp_string6 = "\r\n<TABLE  id=\"_contenttable_".toCharArray();
    _jsp_string3 = "\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string1 = "\r\n".toCharArray();
    _jsp_string10 = "';\r\n	//\u8bbe\u7f6e\u63d0\u793a\u6837\u5f0f\r\n	if(isremind!==''){\r\n     	setRemindInfo(\"".toCharArray();
    _jsp_string11 = "\", isremind,\"docdetail\",\"docnamedetail\");\r\n	}\r\n	\r\n	function initDocPicSlide(eid) {\r\n		var n = 0;\r\n		var count = $('#banner_'+eid+' a').length;\r\n		//$('#banner_'+eid+' a').css('z-index','100')\r\n		$('#banner_'+eid).css('border','1px solid #707070')\r\n		$('#banner_'+eid+' .slidebox_list a:not(:first-child)').hide();\r\n		\r\n		$('#banner_'+eid+' .navitem').eq(0).toggleClass('on1');\r\n		\r\n		$('#banner_'+eid+' .navitem').click(function(e) {\r\n			var i = $(this).attr('_index') - 1; \r\n			n = i;\r\n			if (i >= count) return;\r\n			$('#banner_'+eid+' a').filter(':visible').fadeOut(500).parent().children().eq(i).fadeIn(500);\r\n			\r\n			$('#banner_'+eid+' .navitem').eq(i).toggleClass('on1');\r\n			$(this).siblings().removeClass('on1');\r\n			var event = $.event.fix(e);\r\n			event.stopPropagation();\r\n		});\r\n	}\r\n\r\n	function showAuto(eid) {\r\n		if($('#banner_'+eid+' a').length == 1){\r\n			return;\r\n		}\r\n		var n = $('#banner_'+eid+' .navitem.on1').attr('_index') - 1; \r\n		if(!n){\r\n			n = 0;\r\n		}\r\n		n = n >= ($('#banner_'+eid+' a').length - 1) ? 0 : ++n;\r\n		$('#banner_'+eid+' .navitem').eq(n).trigger('click');\r\n	}\r\n	$(document).ready(function() {\r\n		".toCharArray();
    _jsp_string18 = "')}, 2000);\r\n				$(\"#banner_".toCharArray();
    _jsp_string20 = ")\r\n				}, function() {\r\n					t_".toCharArray();
    _jsp_string2 = "\r\n\r\n".toCharArray();
  }
}
