/*
 * JSP generated by Resin-3.1.8 (built Mon, 17 Nov 2008 12:15:21 PST)
 */

package _jsp._wui;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import weaver.hrm.HrmUserVarify;
import weaver.hrm.User;
import weaver.general.*;

public class _testuser__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
    //\u5224\u65ad\u5bc6\u7801\u5f3a\u5236\u4fee\u6539
    String changepwd = (String)request.getSession().getAttribute("changepwd");
    if("n".equals(changepwd)){
        request.getSession().removeAttribute("changepwd");
        response.sendRedirect("/login/Login.jsp");
        return;
    }else if("y".equals(changepwd)){
        request.getSession().removeAttribute("changepwd");
    }


/*\u7528\u6237\u9a8c\u8bc1*/
    User user = HrmUserVarify.getUser (request , response) ;
    if(user==null) {
        response.sendRedirect("/login/Login.jsp");
        return;
    }
    String from = Util.null2String(request.getParameter("from"));
    if("preview".equals(from))
        session.removeAttribute("SESSION_CURRENT_THEME");

      out.write(_jsp_string1, 0, _jsp_string1.length);
      out.print((user.getLoginid()));
      out.write(_jsp_string2, 0, _jsp_string2.length);
      out.print((user.getPwd()));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((user.getLoginid()));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((user.getPwd()));
      out.write(_jsp_string5, 0, _jsp_string5.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 1886798272571451039L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("wui/testUser.jsp"), 8941377155511599065L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string4;
  private final static char []_jsp_string1;
  private final static char []_jsp_string2;
  private final static char []_jsp_string3;
  private final static char []_jsp_string0;
  private final static char []_jsp_string5;
  static {
    _jsp_string4 = "</td>\r\n    </tr>\r\n    <tr>\r\n        <td width=\"30%\">\u5bc6\u7801\uff1a</td>\r\n        <td>".toCharArray();
    _jsp_string1 = "\r\n\r\n<script language=\"JavaScript\">\r\n    function doSubmit() {\r\n        var username  = \"".toCharArray();
    _jsp_string2 = "\";//\u83b7\u53d6\u7528\u6237\u540d\r\n        var password  = \"".toCharArray();
    _jsp_string3 = "\";//\u83b7\u53d6\u5bc6\u7801\r\n		alert(\"http://localhost:9091/imooc_students/users/Users_login_success.jsp?username=\"+username+\"&password=\"+password);\r\n        window.location.href=\"http://localhost:9091/imooc_students/users/Users_login_success.jsp?username=\"+username+\"&password=\"+password;\r\n		\r\n    }\r\n</script>\r\n\r\n<html>\r\n<body>\r\n<table>\r\n    <tr>\r\n        <td width=\"30%\">\u7528\u6237\u540d\uff1a</td>\r\n        <td>".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string5 = "</td>\r\n    </tr>\r\n    <tr>\r\n        <td width=\"30%\"><input type=\"submit\" onclick=\"doSubmit()\" value=\"\u8df3\u8f6c\"/></td>\r\n    </tr>\r\n</table>\r\n</body>\r\n</html>\r\n".toCharArray();
  }
}
